### PR TITLE
Vue 3 Nuxtism Removal

### LINKED ISSUE #10491: Remove or replace Nuxt reference and logic for Vue3 migration
# Description

Some lingering code inherited form Nuxt is going to clash with the breaking changes from the Vue3 migrations.
These needs to be either corrected to match the syntax, removed if unnecessary or replaced with a new implementation.

## Context

Given [the deprecation of the emitters](https://v3-migration.vuejs.org/breaking-changes/events-api.html#event-bus), all these cases have to be handled as they will break for sure:
- [x] `$nuxt.$on`
- [x] `$nuxt.$off`
- [x] `$nuxt.$emit`

Other breaking cases:
- [x] `$nuxt.$nextTick` ([docs](https://v3-migration.vuejs.org/breaking-changes/global-api-treeshaking.html#global-api-treeshaking))
- [x] `Vue.util.defineReactive`, used in more places
- [x] `Vue.__nuxt__fetch__mixin__`
- [x] ~`Component = Vue.extend(Component);` ([docs](https://v3-migration.vuejs.org/breaking-changes/global-api.html))~ Can be removed in migration branch
- [x] `Vue[installKey]` ([lines](https://github.com/rancher/dashboard/blob/master/shell/initialize/index.js#L165-L178))
- [x] ~`vueDirective.apply(Vue, arguments);`  ([line](https://github.com/rancher/dashboard/blob/master/shell/initialize/index.js#L57))~ Can be removed in migration branch
- [x] `Vue.config.$nuxt.$nuxt = true;` and `Vue.config().$nuxt = {};` ([line](https://github.com/rancher/dashboard/blob/master/shell/initialize/client.js#L112-L114))
- [x] `vueApp.config().$nuxt`  ([line](https://github.com/rancher/dashboard/blob/master/shell/initialize/client.js#L73))
- [x] ~`nuxt.publicRuntimeConfig`, this is needed to start the app ([line](https://github.com/rancher/dashboard/blob/master/shell/initialize/client.js#L120))~ Seems can be left untouched

Optional other cases which would be nice to get rid of:
- [x] `$nuxt.$nuxt`
- [x] `$nuxt.$store`
- [x] `$nuxt.$route`
- [x] `$nuxt.$router`

### PR DESCRIPTION
**Pull request by codyrancher**
Fixes #10491

### CODE REVIEW

**Comment by cnotv** [comment]
At a first glance it seems to be all fine. Going to merge it to my branch and see if there's any leftovers after running my script and start the app.

**Comment by cnotv** [comment]
At a second glance I was not able to find anything else. I'll have to solve outstanding merge conflicts from my side before be able to try this on my branch as well.

**Review by cnotv — APPROVED** [review]
I was not able to merge it to my branch at the current state due other merge fix requirements. Since this is quite required, I'll rather approve the current state.

LGTM

**Comment by aalves08** [comment]
@cnotv I tested this against Kubewarden and Elemental and I haven't found any problems with the current "latest" build versions of it. Also did a search for `$nuxt` usage in all the extensions I could remember and found no hits, so I would say that from Extensions pov, this should be fine

FYI @nwmac

**Pull request merged**
