### PR TITLE
Add SortableTable to Storybook

### LINKED ISSUE #9285: Add SortableTable to Storybook
# Description

As major usage case of this element, add ~table in one of its own wrappers (`ResourceTable` or `SortableTable`)~ `SortableTable` to Storybook and display the different features.

List, to be updated:
- Styles and sections
  - Default view
  - Grouped
  - Simplified
  - Progressive loading
  - Messages and errors
  - Slots
  - Expandable
  - Extra row
- Functionalities
  - Search
  - Advanced filtering
  - Sorting
  - Action menu
  - Row/All selection and total counter (table actions)
  - Context menu
  - Pagination
  - ~Buttons~
    - ~Refresh~
    - ~Download~
    - ~Delete~
  - Shortcuts
  - Tooltips 
- Slots
  - loading	
  - title	
  - header-left	
  - header-middle	
  - header-right	
  - header-button	
  - no-rows	
  - no-results	
  - group-row	
  - group-by	
  - main-row	
  - 'main-row:' + (row.row.mainRowKey || i)	
  - 'col:' + col.col.name	
  - 'cell:' + col.col.name	
  - row-actions	
  - sub-row	
  - shortkeys

EDIT: Buttons are part of a wrapper called `ResourceTable`, so we'll handle this separately as it's not part of the design of the table itself.

Screenshot 2023-07-07 at 11 27 06

image

image

image

### PR DESCRIPTION
**Pull request by cnotv**
### Summary
Fixes #9285

### Occurred changes and/or fixed issues
Added all the listed cases in the issue.

I took also the chance to organize better the whole hierarchy, also based [on the guidelines](https://storybook.js.org/docs/7.0/react/writing-stories/naming-components-and-hierarchy).

image

- Since many components have enigmatic names, I changed them to a standard nomenclature 
- Removed WIP section and placed in the intended location: if it was WIP we should have not just publish it

### Technical notes summary
- Added shortkey plugin
- Added directives:
  - `clean-tooltip`
  - `trim-whitespace`
- Mocked store for progressive loading
- Allow to generate a `yarn.lock` file, so it does not take 10 minutes to start storybook

### CODE REVIEW

**Comment by cnotv** [comment]
@scures this PR is a fork of https://github.com/rancher/dashboard/pull/9340
I will rebase to master after that's merged, as the E2E is also failing and needs a rebase.

**Comment by kwwii** [comment]
The new menu hierarchy looks good to me, thanks!

**Comment by kwwii** [comment]
The new hierarchy looks good to me, thanks!

**Comment by cnotv** [comment]
@scures Was not better to make a comment directly to the story? 😬 

All the slots looks like that and are meant to be showed how are currently styled, so it's out of the scope of this issue to correct anything.
If it seems not enough clear the way I highlight the area, maybe we can think about something else, but out of the box I just want to show what area is involved.

Going for each point:
- Row selection: This should always work out of the box, so we should file an issue for it if you think is the case
- No Row slot: That's how it's styled and is out of scope to make it "look better"
- Header buttons slot: They are working fine, although you are using a dark theme and the buttons I copied are not synched with the color mode, looks like; I replace the buttons with another empty element to avoid mixing up
- Row actions menu: i inspected the whole logic and it seems to be just an event, it would need more investigation
- Sub rows slot: No idea how to enable it
- Expandable subrow: No idea how to enable it

PS: I did not post any preview, that's an image from the Storybook style guide 😅 

All in all, I do not know if we should go for EVERY functionality and we may have a second iteration to add the remaining ones. We do not do that pretty much for none of the components so far and for a reason: nobody knows all the ins and out in our team, which is also why I'm putting components here.

@kwwii 👍

**Comment by cnotv** [comment]
@scures [this is required ](https://github.com/rancher/dashboard/pull/9340)prior the table to be merged.

**Comment by cnotv** [comment]
> * **Sub rows slot**: No idea how to enable it
> * **Expandable subrow**: No idea how to enable it

ok NVM, I found out how to enable this, although there must be something better as it looks weird as it is.

**Comment by richard-cox** [comment]
As Giuseppe is away, and this has been approved, has a 2.7q3 milestone, and doesn't touch dashboard code, will merge

**Pull request merged**
