### PR TITLE
Safari 16+ support for shell

### LINKED ISSUE #9847: Shell doesn't work in Safari
**Setup**
- Rancher version:   v2.7.2
- Rancher UI Extensions:
- Browser type & version: Safari 16.6

**Describe the bug**
Shell doesn't work in Safari, because Safari <16 doesn't support webgl

**To Reproduce**
Open safari
Open cluster Workloads -> Pods -> click "Execute Shell" on any pod
Get an error

**Result**
Got an error 

**Expected Result**
Shell works in Safari

**Screenshots**
Error

### PR DESCRIPTION
**Pull request by cogor**
### Summary
Fixes #9847
Shell works in Safari

### Occurred changes and/or fixed issues
Updated xterm and addons [for support safari 16+](https://github.com/xtermjs/xterm.js/releases/tag/5.1.0)
Added `xterm-addon-canvas` addon, for browsers without webgl support(Safari <16)

### Steps to reproduce
Open safari
Open cluster Workloads -> Pods -> click "Execute Shell"  on any pod
Get an error

### Areas or cases that should be tested
Tested in Firefox 118, Chrome 117, Safari 16.6

### CODE REVIEW

**Comment by richard-cox** [comment]
@cogor Thanks for raising this PR. Would you be able to create an issue and link it to this PR? That will help process this change through to a release

**Comment by cogor** [comment]
> @cogor Thanks for raising this PR. Would you be able to create an issue and link it to this PR? That will help process this change through to a release

Of course

**Comment by cogor** [comment]
closes #9847

**Comment by aalves08** [comment]
@cogor can you rebase the latest master onto this PR? We've changed the e2e tests on our CI/CD pipelines and it needs to pass all the gates 🙏 Thank you

**Comment by aalves08** [comment]
Codewise LGTM and testing on Safari (15.4), Chrome, Firefox, Brave and Edge looked fine

**Review by torchiaf — APPROVED** [review]
There are no regressions on `ContainerShell`. LGTM

**Comment by cogor** [comment]
@aalves08 Done

**Comment by aalves08** [comment]
Closed as a duplicate of https://github.com/rancher/dashboard/pull/10245. @cogor I decided to recreate your PR because it needed changes on the e2e tests as well.

**Pull request closed without merging**
