### PR TITLE
Fix workspace filtering

### PR DESCRIPTION
**Pull request by richard-cox**
Part 1
- This was broken by https://github.com/rancher/dashboard/pull/6261
- The `activeNamespaceCache` depends on the product (fleet requires workspaces, everything else namespaces)
- This needs updating when going to or from fleet

Part 2
- When changing the filter (workspace or namespace) switching between selections that contain the same number of results/rows wouldn't change the rows. 
- This is more obvious on the fleet/workspace world where the filter switches between two values, rather than the explorer/namespace filter which toggles values on or off  (making it unlikely to go from one state to another with the same amount of rows)
- The fix is to ensure the lists take into account the ns filter, alongside things like row count, sort settings, etc)

NOTE - On `head` (but not `ui-dashboard-index` `latest`) refreshing on the explorer pods page does not show the correct namespace filtered pods - see https://github.com/rancher/dashboard/issues/6525

Small tidyup for `activeNamespaceCache` and `activeNamespaceFilters` getters

### CODE REVIEW

**Comment by aalves08** [comment]
BE: from 6 weeks ago
FE: your branch

@richard-cox I gave it a round of testing and came up with the following issues:

**Comment by richard-cox** [comment]
> BE: from 6 weeks ago FE: your branch
> 
> @richard-cox I gave it a round of testing and came up with the following issues:
> 
>     * Not filtering fleet cluster groups
>     * Slow reactivity (delay) filtering fleet git repos
Weird, for me it doesnt work with 1 in each workgroup.... but does if there is two in one workgroup 
>     * after a page refresh, under deployments, deployments are not filtered correctly (unfiltered)
>     * after a page refresh, coming from home, deployments are not filtered correctly (unfiltered)
Covered by https://github.com/rancher/dashboard/issues/6525

**Comment by aalves08** [comment]
> > BE: from 6 weeks ago FE: your branch
> > @richard-cox I gave it a round of testing and came up with the following issues:
> > ```
> > * Not filtering fleet cluster groups
> > * Slow reactivity (delay) filtering fleet git repos
> > ```
> 
> Weird, for me it doesnt work with 1 in each workgroup.... but does if there is two in one workgroup
> 
> > ```
> > * after a page refresh, under deployments, deployments are not filtered correctly (unfiltered)
> > * after a page refresh, coming from home, deployments are not filtered correctly (unfiltered)
> > ```
> 
> Covered by #6525

Lingering issues:
* Not filtering fleet cluster groups -> R: my scenario has 1 item on each workspace
* Slow reactivity (delay) filtering fleet git repos

The other two issues are covered by #6525

**Comment by aalves08** [comment]
I can confirm that toggling the workspace on fleet cluster groups, with a total of 3 (2 on one workspace, 1 on another) works. 
Strangely, with a total of 4 (2 on each workspace) it doesn't work again. 💦

**Comment by mantis-toboggan-md** [comment]
> Weird, for me it doesnt work with 1 in each workgroup.... but does if there is two in one workgroup

> I can confirm that toggling the workspace on fleet cluster groups, with a total of 3 (2 on one workspace, 1 on another) works.
> Strangely, with a total of 4 (2 on each workspace) it doesn't work again. 💦

ResourceTable filteredRows updates correctly (and passes the updated rows to SortableTable) but SortableTable `displayRows`, which is what it renders, is not updated...SortableTable uses a chain of computed props: arrangedRows -> filteredRows -> pagedRows -> groupedRows -> displayRows

`arrangedRows` calculates whether a change has actually occurred and uses `cachedRows` if not (which are exactly what they sound like) 
```
if ( this.sortGenerationFn ) {
        key = `${ this.sortGenerationFn.apply(this) }/${ this.rows.length }/${ this.descending }/${ this.sortFields.join(',') }`;
        if ( this.cacheKey === key ) {
          return this.cachedRows;
        }
      }
```
The fleet resources appear to be using the default sortGenerationFn:
```
export const defaultTableSortGenerationFn = (schema, $store) => {
  if ( !schema ) {
    return null;
  }

  const resource = schema.id;
  const inStore = $store.getters['currentStore'](resource);
  const generation = $store.getters[`${ inStore }/currentGeneration`]?.(resource);

  if ( generation ) {
    return `${ resource }/${ generation }`;
  }
};
```

So that's not gonna change when we switch workspaces. If we have the same number of resources in each workspace, `${ this.sortGenerationFn.apply(this) }/${ this.rows.length }/${ this.descending }/${ this.sortFields.join(',') }` wont change, and SortableTable wont update. I checked my understanding of the bug by slapping the workspace into the `key`, doesn't seem like a particularly good solution to actually implement but it does solve the issue on fleet list views:

```
const workspace = this.$store.getters['workspace'];

      if ( this.sortGenerationFn ) {
        key = `${ this.sortGenerationFn.apply(this) }/${ this.rows.length }/${ this.descending }/${ this.sortFields.join(',') }${ workspace }`;
        if ( this.cacheKey === key ) {
          return this.cachedRows;
        }
      }
```
I also noticed SortableTable rows re-calculating every 1-2 seconds on the GitRepo page. Could be related to the performance issues?

(I'd propose a better solution to the table issue but it's 5pm I can't work late today, sorry)

**Comment by richard-cox** [comment]
@mantis-toboggan-md Good sleuthing, that was the one. Our tables do not take in to account the namespace filter when it changes. The table's only update because the row count changes. This is almost always hidden in the explorer because the ns filter control toggles values rather than switches between them (like fleet workspace's control)... so it's rare to get the scenario of going between selections that have the same amount of rows in the table.

The fix is to update `defaultTableSortGenerationFn` to take in to account the activeNamespaceCache (aka selected namespaces).

**Review by aalves08 — APPROVED** [review]
given that

* after a page refresh, under deployments, deployments are not filtered correctly (unfiltered)
* after a page refresh, coming from home, deployments are not filtered correctly (unfiltered)

are covered by https://github.com/rancher/dashboard/issues/6525

The latest round of tests all check out, afaik. LGTM

FYI @nwmac

**Pull request merged**
