### PR TITLE
Update CN community links

### PR DESCRIPTION
**Pull request by huacheng-git**
### Summary
Fixes https://github.com/rancher/dashboard/issues/9105

### Occurred changes and/or fixed issues

1. When the zh-hans language is selected, display the link to the Chinese forum
2. Replace the latest WeChat QR code.

### Screenshot/Video

image
image

### CODE REVIEW

**Comment by momesgin** [comment]
@huacheng-git It might be good to add a test for it as well, but the code itself looks good to me.

**Review by momesgin — CHANGES_REQUESTED** [review]
It might be good to add a test for it as well, but the code itself looks good to me

**Comment by momesgin** [comment]
Thanks @richard-cox idk how I forgot to do that!

**Review by momesgin — CHANGES_REQUESTED** [review]
could you please also add a unit test to check if the link exists when the language is zh-hans?

**Review by momesgin — APPROVED** [review]
Thanks for adding the unit test! LGTM

**Review by momesgin — APPROVED** [review]

**Review by momesgin — APPROVED** [review]

**Review by rak-phillip — APPROVED** [review]

**Pull request merged**
