### PR TITLE
HARVESTER: Fix can not load Harvester plugin on Harvester cluster page

### PR DESCRIPTION
**Pull request by n313893254**
### Summary
Fix "export 'default' was not found when building plugins

### Occurred changes and/or fixed issues

Reproduce Steps:
1. Run `yarn build-pkg harvester && yarn serve-pkgs` under rancher/dashboard repo.
2. The terminal will throw two warrings: `"export 'default' (imported as 'advancedWorkerConstructor') was not found in '@shell/plugins/steve/worker/web-worker.advanced.js'` and `"export 'default' (imported as 'basicWorkerConstructor') was not found in '@shell/plugins/steve/worker/web-worker.basic.js'`
3. Login to the Rancher and import a Harvester cluster
4. Go to the Global setting. Set `ui-dashboard-index` to `https://releases.rancher.com/dashboard/latest/index.html`. Set `ui-offline-preferred` to `Remote`.
5. Login to the Harvester UI, and go to settings. Set `ui-plugin-index` to `http://127.0.0.1:4500/harvester-1.1.0/harvester-1.1.0.umd.min.js`. Set `ui-source` to `External `
6. Open the Rancher UI and try to go to the imported Harvester cluster

### Technical notes summary

- Fix "export 'default' was not found when building plugins

### Screenshot/Video

image

### CODE REVIEW

**Comment by n313893254** [comment]
Hi, @mantis-toboggan-md. There have a PR that needs you to review, Thx!

**Comment by richard-cox** [comment]
Something isn't quite right here, these worker files are handled differently from standard files.

**Comment by richard-cox** [comment]
Closing in favour of https://github.com/rancher/dashboard/pull/8170

**Comment by richard-cox** [comment]
@n313893254 The alt fix https://github.com/rancher/dashboard/pull/8170 has now been merged

**Pull request closed without merging**
