### PR TITLE
Disallow `v-html` usage

### PR DESCRIPTION
**Pull request by rak-phillip**
### Summary

This replaces the use of the `v-html` directive with a custom `v-clean-html` directive that uses the `DOMPurify` library to sanitize HTML input before rendering it. `v-html` usage is discouraged[^1] in the Vue documentation, and should only be used on trusted content. Our widespread usage of `v-html` makes this difficult to guarantee safe usage across the board, so it's better to disallow `v-html` and sanitize existing usages in Rancher Dashboard.

### Occurred changes and/or fixed issues

- Disallows use of `v-html` with `eslint`
- Adds new `v-clean-html` directive that only allows existing tags used in `en-us.yaml`
- Replaces all existing instances of `v-html` with `v-clean-html` 

### Technical notes summary

The current implementations contains a list of allowed tags for use with `v-clean-html`:

```javascript
const ALLOWED_TAGS = [
  'code',
  'li',
  'a',
  'p',
  'b',
  'br',
  'ul',
  'pre',
  'span',
  'div',
  'i',
  'em',
  'strong',
];
```

These tags are derived from a list of unique tags obtained from `en-us.yaml`. An alternative approach might be to replace this list of allowed tags with the `DOMPurify` `html` profile[^2], which should allow all safe HTML (e.g. `DOMPurify.sanitize(dirty, {USE_PROFILES: {html: true}});`)

### Areas or cases that should be tested

We need to identify at least one instance for each of the allowed tags to ensure that content is rendered properly.

[^1]: https://v2.vuejs.org/v2/guide/syntax.html#Raw-HTML
[^2]: https://github.com/cure53/DOMPurify#can-i-configure-dompurify

### CODE REVIEW

**Comment by rak-phillip** [comment]
@mantis-toboggan-md I requested a review from you because this change modifies Harvester code

**Comment by rak-phillip** [comment]
@aalves08 I'm requesting a review from you because this modifies extensions

**Comment by rak-phillip** [comment]
@nwmac you are included on this PR more for an FYI

**Review by mantis-toboggan-md — DISMISSED** [review]
LGTM - tracked down instances of the allowed tags and verified that they still render correctly

**Comment by rak-phillip** [comment]
@jordojordo requesting a review from you at the recommendation of @aalves08. We might want to make sure that nothing regresses on Kubewarden as a result of this change.

**Comment by rak-phillip** [comment]
@jordojordo @mantis-toboggan-md rebased on top of `master` to resolve merge conflicts with `shell/dialog/GenericPrompt.vue`

**Review by jordojordo — APPROVED** [review]

**Review by aalves08 — COMMENTED** [review]
@rak-phillip I've found an issue with this branch (non-reproducible on a branch derived from `release-2.7.2` nor in `master`) in an `ActionMenu` item on the extensions panel. The rest seems good to me. I tested install, uninstall, update, rollback, etc, and all worked fine.

Screenshot 2023-03-22 at 15 59 06

**Comment by rak-phillip** [comment]
> @rak-phillip I've found an issue with this branch (non-reproducible on a branch derived from `release-2.7.2` nor in `master`) in an `ActionMenu` item on the extensions panel. The rest seems good to me. I tested install, uninstall, update, rollback, etc, and all worked fine.
> 
> Screenshot 2023-03-22 at 15 59 06

> 

This error has been traced back to #8232

**Pull request merged**
