### PR TITLE
The section referenced has been removed from the docs for a while now

### PR DESCRIPTION
**Pull request by Tejeev**
It's still useful but it's a dead link and links should not be to dynamic `latest` pages.  I've updated it to point to 1.9 as this doc still has the info

### CODE REVIEW

**Comment by nwmac** [comment]
@Tejeev I think this is the correct document https://istio.io/latest/docs/setup/additional-setup/customize-installation/

**Comment by Tejeev** [comment]
> @Tejeev I think this is the correct document https://istio.io/latest/docs/setup/additional-setup/customize-installation/

My point is that it's a dynamic link and in a few versions it may not be

**Comment by brendarearden** [comment]
I believe the new link should be `https://istio.io/latest/docs/setup/additional-setup/customize-installation/#patching-the-output-manifest` - I don't like the idea of linking to a specific istio version so we should continue to point to a "latest" url

**Comment by Tejeev** [comment]
@brendarearden I think the link should be in the manifest readmes and point to the appropriate version doc.  From we already saw, I feel we can't really link to dynamic docs because they change and the sections being referenced get removed

**Review by catherineluse — APPROVED** [review]
I added Brenda's link. @Tejeev Both the versioned and `latest` docs are both at risk of going out of date and breaking links. But I'd say the `latest` link is at somewhat lower risk.

**Review by brendarearden — APPROVED** [review]
Looks good - I agree with the decision to change the url and point it to the latest version of the url.

**Pull request merged**
