### PR TITLE
feat(workload/storage): support add emptyDir volume

### LINKED ISSUE #7533: [Bug] Rancher 2.6 is missing emptyDir from volume types.
Duplicating issues:
https://github.com/rancher/rancher/issues/34638
https://github.com/rancher/rancher/issues/36760

**Setup**
- Rancher version: 2.6.*
- Browser type & version: FF, Chrome, latest

**Describe the bug**
If you create a deployment and want to add an emptyDir volume, you cannot select that from volume type dropdown
```
      volumes:
      - emptyDir: {}
        name: somename
```

**To Reproduce**
1. Create a deployment
2. Storage -> Add Volume
3. emptyDir not existent

1. Import a deployment with an empty dir
2. update the deployment
3. storage, you are unable to change the name of the emptyDir mount, no field available

**Result**

**Expected Result**
1. EmptyDir is available in dropdown
2. EmptyDir name can be changed on update of an deployment

**Screenshots**
grafik
grafik

### PR DESCRIPTION
**Pull request by ly5156**
### Summary
Fixes #7533

workload support add emptyDir volume

ref: https://kubernetes.io/docs/concepts/storage/volumes/#emptydir

### Occurred changes and/or fixed issues

https://github.com/rancher/dashboard/issues/7533

### CODE REVIEW

**Comment by richard-cox** [comment]
@ly5156 Our go forward branch for 2.6 has recently been created and is `release-2.6`

**Comment by aalves08** [comment]
@ly5156 code and test look fine but as Richard mentioned the branch to merge in is `release-2.6`. Can you change the target branch and give it another test please? Thank you 🙏

**Review by aalves08 — COMMENTED** [review]
@ly5156  code and test look fine but as Richard mentioned the branch to merge in is release-2.6. Can you change the target branch and give it another test please? Thank you 🙏

**Comment by ly5156** [comment]
@aalves08 
The new PR address：https://github.com/rancher/dashboard/pull/7700

**Comment by aalves08** [comment]
closed in favor of https://github.com/rancher/dashboard/pull/7700

**Pull request closed without merging**
