### PR TITLE
Validate Harvester clusters

### PR DESCRIPTION
**Pull request by torchiaf**
### Summary
Fixes https://github.com/harvester/harvester/issues/4350

### Technical notes summary

This is meant to add Machine Pools validation before editing Yaml file; the yaml Validation is triggered after the user clicks on 'Edit as YAML' button and saves the Machine Configurations:

image

### CODE REVIEW

**Comment by richard-cox** [comment]
@torchiaf can you update the milestone?

**Comment by gaktive** [comment]
We'll need to find someone with a Harvester setup to help with reviews. @torchiaf is there something you use that others could hop onto? If so, then once they gain access, we can add a reviewer again.

Otherwise, looks like a rebase is required now.

**Comment by torchiaf** [comment]
> We'll need to find someone with a Harvester setup to help with reviews. @torchiaf is there something you use that others could hop onto? If so, then once they gain access, we can add a reviewer again.
> 
> Otherwise, looks like a rebase is required now.

@gaktive sure, I can share with the reviewer my environment (with a Harvester downstream cluster)
@mantis-toboggan-md could you help with this?

**Comment by mantis-toboggan-md** [comment]
This is preventing the user from switching to the yaml view if there are other form validation errors in the cluster, eg I can't switch to yaml without a cluster name defined. Validating the machine pools makes sense to me because they're saved before switching to yaml view, but I'm not sure about requiring the rest of the form to be valid, was that intentional @torchiaf?

**Comment by torchiaf** [comment]
> This is preventing the user from switching to the yaml view if there are other form validation errors in the cluster, eg I can't switch to yaml without a cluster name defined. Validating the machine pools makes sense to me because they're saved before switching to yaml view, but I'm not sure about requiring the rest of the form to be valid, was that intentional @torchiaf?

You are right, the cluster name validation should not be included in the machine pool validation. I've fixed it, thanks!

**Review by mantis-toboggan-md — APPROVED** [review]

**Pull request merged**
