### PR TITLE
Add support for `Bandwidth Manager` config for `Cilium`

### PR DESCRIPTION
**Pull request by masap**
### Summary

Fixes: #10049.

Internal Reference: SURE-7195

### Occurred changes and/or fixed issues

Added support for `Bandwidth Manager` config for `Cilium`

I have tested it when enabled `Bandwidth Manager`.

```
$ kubectl -n kube-system get cm cilium-config -o json | jq '.data."enable-bandwidth-manager"'
"true"

$ kubectl -n kube-system delete pod cilium-xxxxx

$ kubectl -n kube-system exec ds/cilium -c cilium-agent -- cilium status | grep BandwidthManager
BandwidthManager:                                   EDT with BPF [CUBIC] [ens5]
```

I have tested it when disabled Bandwidth Manager.

```
$ kubectl -n kube-system get cm cilium-config -o json | jq '.data."enable-bandwidth-manager"'
null

$ kubectl -n kube-system delete pod cilium-xxxxx

$ kubectl -n kube-system exec ds/cilium -c cilium-agent -- cilium status | grep BandwidthManager
BandwidthManager:        Disabled
```

### Screenshot/Video
cilium-bandwidth

### CODE REVIEW

**Comment by richard-cox** [comment]
@masap This will need a rebase from `master` too?

**Comment by masap** [comment]
@richard-cox I rebased it, fixed a conflict and retested it.

**Comment by masap** [comment]
Fixed conflict because `Basics.vue` has been moved.

**Comment by nwmac** [comment]
Closed in favour of https://github.com/rancher/dashboard/pull/10320 which adds tests and updates with latest code changes for the ipv6 setting.

**Pull request closed without merging**
