### PR TITLE
Updating the logging chart to use tabs for each provider

### PR DESCRIPTION
**Pull request by codyrancher**
rancher/dashboard#1027
Screen Shot 2020-08-18 at 1 21 37 PM
Screen Shot 2020-08-18 at 1 21 45 PM
Screen Shot 2020-08-18 at 1 21 52 PM

### CODE REVIEW

**Comment by vincent99** [comment]
- The dropdown for disabled/enabled on each driver and some other bool fields seems sort of odd vs a `[ ] Enabled` checkbox.
- Since there's nothing else in the tab I'd probably go with the options (host, port, etc) are always shown, but disabled if !enabled
- Host / Scheme / Port should go in logical order, and possibly as one row... `[scheme http]://[host foo.com]:[port 443]`

**Comment by codyrancher** [comment]
> * The dropdown for disabled/enabled on each driver and some other bool fields seems sort of odd vs a `[ ] Enabled` checkbox.

To me this looks pretty odd. I'm fine to make the change but here's a screenshot. Let me know if you'd still like this change.
Screen Shot 2020-08-18 at 2 27 55 PM

> * Since there's nothing else in the tab I'd probably go with the options (host, port, etc) are always shown, but disabled if !enabled

That's actually what I originally did but our enabled vs disabled doesn't look very distinct to me and the show vs hide made it very evident that you needed to enable things first. But I'll make the change if that's what you'd like.
Screen Shot 2020-08-18 at 2 25 30 PM
Screen Shot 2020-08-18 at 2 35 45 PM



> * Host / Scheme / Port should go in logical order, and possibly as one row... `[scheme http]://[host foo.com]:[port 443]`

Done. Definitely looks better. 
Screen Shot 2020-08-18 at 2 33 18 PM

**Comment by deniseschannon** [comment]
@codyrancher @vincent99 after talking with @paynejacob, it seems the provider configuration should be moved out of the helm deployment and into individual CRD pages as helm upgrades will override any changes in the CRDs. But the work in these tickets should be pushed to the individual CRD pages for cluster outputs.

**Comment by vincent99** [comment]
Alright well that eliminates the need for enabled flags altogether.. @codyrancher can you update this PR to show whatever options are still supposed to be there on install of the chart.  You can leave the individual provider config code orphaned for future crd work..

**Comment by codyrancher** [comment]
Yeah. I'll go ahead and update once I find out what the options are going to be.

**Comment by deniseschannon** [comment]
@codyrancher I think the options are being simplified a lot, but @paynejacob should provide input on what is expected.

**Comment by codyrancher** [comment]
I'm just going to orphan this PR and dot he work elsewhere.

**Pull request closed without merging**
