### PR TITLE
Show both internal and external IP in list of nodes

### PR DESCRIPTION
**Pull request by catherineluse**
Fixes https://github.com/rancher/dashboard/issues/6371

This PR changes the "IP Address" column in the list of nodes for a cluster in Cluster Management.

Previously, it only checked for internal IPs. Now it uses the existing table header for showing both internal and external IPs, which matches the UX in Cluster Explorer on the Nodes page.

To test this PR,

1. I provisioned a single-node EC2 cluster
2. Logged into the EC2 console and checked the external IP of the new node
3. Confirmed that the external IP was shown in the list of cluster nodes

Then to make sure I didn't mess up the internal IP display,

1. I provisioned a single-node Digital Ocean cluster, for which an external IP is not available out-of-the-box
2. Confirmed that the internal IP was shown in the list of cluster nodes

### CODE REVIEW

**Review by Shavindra — CHANGES_REQUESTED** [review]
For cluster management > cluster detail you need to update here for RKE1 clusters.
https://github.com/rancher/dashboard/blob/92c81e6d14657cad83e8be6c63e09504e828994c/shell/models/management.cattle.io.node.js#L128?

code you changed is only for RKE2 clusters

I also noticed this… may be we can create a ticket. Feels this might be better approach. - I noticed this myself right now - Something for future?

image

**Comment by catherineluse** [comment]
I'm closing this PR because it seems unnecessary - I have found that the bug is no longer reproducible in master.

**Comment by catherineluse** [comment]
# QA Template
## Root cause
There are two class models for nodes:`shell/models/management.cattle.io.node.js`, which is used to represent nodes in RKE1 cluster provisioning, and `cluster.x-k8s.io.machine.js`, which is used to represent nodes in V2 cluster provisioning for RKE2/K3s. Both of these class models used an `ipaddress()` getter to represent the IP. This was inconsistent with how the IP is displayed in Cluster Explorer, because in Cluster Explorer, the table header always includes both internal and external IPs, not just one IP.
 
## What was fixed, or what changes have occurred
I have modified the class models to replace the single ipAddress getter with two separate getters for internal and external IPs. The appearance of the internal/external address column in cluster management is now supposed to be identical to the one in Cluster Explorer.
 
## Areas or cases that should be tested
RKE2 and RKE1 clusters should be provisioned in EC2 to make sure the IP is consistent across cluster management and cluster explorer.
 
## What areas could experience regressions?
RKE2 and RKE1 clusters should also be provisioned in Digital Ocean - there should be no difference for any IP address column between cluster management and cluster explorer.

**Comment by Shavindra** [comment]
> The appearance of the internal/external address column in cluster management is now supposed to be identical to the one in Cluster Explorer.

image

@catherineluse I am not seing `None` in the cluster explorer. Is it expected?

on a side note and personal level I feel `-` is better than a `None`.

**Comment by catherineluse** [comment]
@Shavindra In that case, what happened is that the external IP and internal IP were the same. If both IPs are the same, the UI intentionally hides one of them to avoid showing the duplicate. I think we should just show both of them though, for consistency across the board.

**Comment by kwwii** [comment]
Stating "Same as external make it easier to identify those with the same external and internal IPs (without having to compare the numbers).

**Comment by catherineluse** [comment]
I made it say "Same as External." Screenshot 2022-12-08 at 10 31 29 AM

**Review by codyrancher — APPROVED** [review]

**Pull request merged**
