### PR TITLE
Add Download CLI links to About Page

### PR DESCRIPTION
**Pull request by richard-cox**
- Addresses #2905

### CODE REVIEW

**Comment by richard-cox** [comment]
As discussed in the sprint demos, this could be reduced vertically by only displaying the link related to the client's OS (instead of all mac, win and linux). Alternatively they could be moved somewhere less prominent. Had a thought overnight, the new About page has some download links already (for image lists), that section could be expanded with these CLI download links.

**Comment by nwmac** [comment]
@richard-cox Yeah - let's move this to the About page for now

**Comment by richard-cox** [comment]
Moved content to the about page into a download table with image lists. Now blocked on #2919. The git history is a bit off, after that PR is merged will update this one.

image

**Review by nwmac — APPROVED** [review]
If I was being really picky, it would look ever so slightly better if the OS icons were before the platform name in the lists (with the same width)

**Pull request merged**
