### PR TITLE
Migrating the persistentvolume pages

### PR DESCRIPTION
**Pull request by codyrancher**
rancher/dashboard#2186

I intend to add the PVC field to the list and details as a part of https://github.com/rancher/dashboard/issues/2212 since I haven't looked at them yet.

image
image
image
image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by vincent99** [comment]
The default nodeAffinity is invalid and fails:
image

Default capacity has no unit so it will end up as 10 bytes;

```
spec:
  capacity:
    storage: '10'
```

**Comment by codyrancher** [comment]
@vincent99 for the nodeAffinity what do you think an appropriate default value is? I'm thinking we should just make it a required field. It fails on ember too.

image

**Comment by codyrancher** [comment]
I ended up adding node selectors as a required field. If you think you have a default we should use let me know and I'll add it.
image

**Comment by vincent99** [comment]
Local was a bad example to screenshot, it was failing for every volume type. It is indeed required for `local`, but not for other types.

**Comment by codyrancher** [comment]
@vincent99 I took care of each of the issues you mentioned. I made the node selectors a requirement for just local and now properly omit the nodeAffinity if no matches have been entered.

**Pull request merged**
