### PR TITLE
Remove initial-empty-row from ArrayListGrouped.

### LINKED ISSUE #7656: VolumeMount Now Required For Deployments
**Setup**
- Rancher version: `v2.7-head (c35f112)`
- Browser type & version: `Chrome Version 108.0.5359.94 (Official Build) (arm64)`

**Describe the bug**
When trying to deploy an image on `v2.7-head (c35f112)`, an error appears stating the volumeMount is a requirement. Previously this has not been a requirement and I haven't been able to find any ticket that changes this to a requirement. Once a volumeMount is set the deployment does process as expected.

`Deployment.apps "test3" is invalid: [spec.template.spec.containers[0].volumeMounts[0].name: Required value, spec.template.spec.containers[0].volumeMounts[0].name: Not found: "", spec.template.spec.containers[0].volumeMounts[0].mountPath: Required value]`

**To Reproduce**
1. Create a Rancher HA on `v2.7-head`
2. Create a downstream cluster (or do this on local)
3. In the left side nav, go to Workloads > Deployments
4. Click Create in the upper right of the page
5. Give the deployment a name and image (such as nginx:latest)
6. Click the `Create` button 

**Result**
Error message appears stating a volumeMount is required to finish creating the deployment

**Expected Result**
Deployment is created whether or not there's a volumeMount.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Shavindra**
### Summary
Fixes #7656 

### Technical notes summary
`:initial-empty-row="true"` Creates empty row in Workload > Pod > Storage and Workload > Container > Storage.
All though optional If added then nested fields are mandatory required.

### CODE REVIEW

**Review by catherineluse — DISMISSED** [review]

**Review by cnotv — DISMISSED** [review]
LGTM

**Comment by cnotv** [comment]
@Shavindra Why are we changing the tests if it already passed before? 🤔

**Comment by cnotv** [comment]
Checks are not there for some reasons 🤔

**Review by gennitdev — APPROVED** [review]

**Review by cnotv — APPROVED** [review]
Passed checks and was able to create a workload.

LGTM

**Pull request merged**
