### PR TITLE
create/edit/remove sidecars init container

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
#975 

Screen Shot 2021-02-01 at 3 14 46 PM
Screen Shot 2021-02-01 at 3 18 21 PM
Screen Shot 2021-02-01 at 3 14 40 PM

### CODE REVIEW

**Review by lvuch — COMMENTED** [review]
I reviewed this with @mantis-toboggan-md via slack and found the process a little confusing. I created a workload but can't create a side care while making a workload so I have to revisit the list page and go to the action menu then create a sidecar. Then once the sidecar is created it just...disappears...where did it go? The workload detail page? No not there... I have to again revisit the action menu and "config" which is _different_ than "config" view of a workload detail page. Overall I think the create page and view pages are fine but the flow as a whole is hard. I had to ask nancy for a play by play because I kept getting stuck.

**Review by richard-cox — CHANGES_REQUESTED** [review]
I haven't dived into the code/functionality too much yet, but I've played around with Deployments and think there's some issues

- Deployments with multiple containers aren't handled well (existing issue in master, but relevant to PR)
  - When creating a Deployment only one container can be added
  - When editing a Deployment with multiple containers only the first can be edited (and in view mode only the first is shown)
    - The container tab also has the pod level properties of label & annotations which i think apply to all containers
- Deployments with multiple sidecars cannot be edited
  - When editing a deployment with multiple sidecars/containers ... the user gets to select a sidecar and then taken to the edit deployment page... however with just edit sidecar tabs
  - When editing a deployment with a single sidecar user is taken to the normal edit deployment page
- The use of 'container' and 'sidecar' terms leads to a confusing experience (this mostly matches Ember's handling of sidecars)
  - `container` is used ..
    - When creating/viewing/editing a deployment 
  - `sidecar` is used ..
    - Before user gets to the edit deployment page they get to choose a `sidecar`
    - In the action menu for a deployment the user can Add a `sidecar`

I think the second two are blockers. In addition...

- Cannot set the name of a container, either in create or edit (existing issue in master)
- Height of fields in the Deployment / Container (tab) Ports rows are different (existing issue in master?)
- When editing a deployment the user is prompted to select a sidecar from a list of all sidecars (containers). I don't think these should all labelled as sidecars. In Ember the first one is described as the 'Primary' instead, however I don't think this is always right.

To move this on I think we need a call with Neil & Lauren. Here's my 2 pence...
- I don't think there's a way to specifically identify a 'sidecar' container, in some ways it feels we should drop the term sidecar entirely and only use container?
- View/Edit/Add/Remove deployment containers/sidecars via the the Deployments Container tab
  - Tab shows a list of containers, user can remove containers via this list
  - User can click 'Add' / an existing container to see form below (either empty or populated)
  - Changes to containers are saved like any other edit to Deployments
- Edit Pod level properties (such as labels/annotations) in their own Deployment tab
  - Pull out pod specific info from the container tab and move to it's own 'pod' tab

What I haven't done
- Looked at all workload types to see if the issues/fixes apply to all
- Researched fully if there's a way that sidecars should officially be declared (I think the term is just conceptual)

**Comment by mantis-toboggan-md** [comment]
I should have left a note here or pinged you when I asked for review, that's my bad. The questionable UX of sidecars has come up in meetings a couple times and we decided not to change that for 2.5.8. Since this is the UX that's been in Ember for some time its....'good enough'. Having said that I think there's also some confusion here about bugs vs bad UX

>   * When editing a Deployment with multiple containers only the first can be edited

I think I'm misunderstanding you; I don't see this bug. When I edit a deployment with multiple containers, I get a container-picker view and any container can be edited.
>     * The container tab also has the pod level properties of label & annotations which i think apply to all containers

Pod labels and annotations only appear there for the main container, but I agree that if it's outside the container scope it should be on a different tab. Related to that, I think having a 'container' tab and then several other tabs that are also within the container spec is a little off so I think names/tab content in general could be improved. 

>   * When editing a deployment with multiple sidecars/containers ... the user gets to select a sidecar and then taken to the edit deployment page... however with just edit sidecar tabs

I think this is just a case of confusing UX. All the deployment fields should be present when editing the primary container (if that's not the case then yes, pretty bad bug)

> * The use of 'container' and 'sidecar' terms leads to a confusing experience (this mostly matches Ember's handling of sidecars)

Agreed, I think we should revisit this along with tab naming/content. Sidecars are just containers.

 
> * Cannot set the name of a container, either in create or edit (existing issue in master)

You can't set the name of the "primary" container. You should be able to set the name of additional containers, if not that's a bug.

> * I don't think there's a way to specifically identify a 'sidecar' container, in some ways it feels we should drop the term sidecar entirely and only use container?

Yeah from what I've read, there's really no formal way of distinguishing them. Sidecars are just one of a few multi-container workload patterns. I think we'll need input from more seasoned kubernetes people than me to decide how we want to present the concept of multi-container workloads, though even we can see pain points with the experience and I think you've got some good ideas going on here. My objection is merely that it's outside the scope of this PR.

**Comment by mantis-toboggan-md** [comment]
Updated to remove primary/sidecar distinction and show deployment-wide config options regardless of which container is being edited. I also added a container select and the ability to add/remove containers to the edit config form:

Screen Shot 2021-04-12 at 7 52 59 AM

Screen Shot 2021-04-12 at 7 53 19 AM

**Review by richard-cox — CHANGES_REQUESTED** [review]
- The recent changes resolve the two blocking issues from https://github.com/rancher/dashboard/pull/2275#pullrequestreview-632379519
- Merging this PR will mean users can manage workloads with multiple containers, though the UX needs improving (#2683)
- There's a few minor comments from looking through the code, I'll attempt to fix those and give the feature a proper test tomorrow

**Comment by richard-cox** [comment]
I've given everything a basic test and think this is almost ready to merge, only two things blocking it
- The automated changes to en-us.yaml need reverting and a re-review. This is debatable, however could produce a lot of churn
- My changes need a review by Nancy. They look ok and work, though might need

**Comment by mantis-toboggan-md** [comment]
Your changes look good to me, only 2 minor adjustments:
* I updated the v-if logic for the remove container button from `isEdit` to `!isView` so it can show up when initially creating a container
* removed ContainerSelect since it's no longer used

Additionally, I reverted linting on en-us.yaml so changes there should be much easier to review.

**Review by richard-cox — APPROVED** [review]
Ship it!

**Pull request merged**
