### PR TITLE
Allow for `jsyaml.dump()` Options in `dumpBlock`

### LINKED ISSUE #10044: Configmaps in Rancher 2.7.6 becomes corrupted after saving via GUI
Internal reference: SURE-7215
Reported in 2.7.6

Issue description:
When a user tries to edit configmap from the Rancher UI, it corrupts the data after saving it by adding new line breaks.

Business impact:
This impacts the applications using the configmap as the application configurations are being read from these configmaps and when the get corrupt, the applications are not able to load them and they start to fail.

Troubleshooting steps:
Unable to troubleshoot the issue from the UI as we do not know why the line breaks are appended to the configmaps in the backend when edited from the UI. Not sure what payload the UI is sending to the backend once we save the configmap.

Repro steps:

Scenario 1:

- Login to rancher
- choosing namespace where the configmaps has to change (Storage > ConfigMaps > click on the three dots > Edit config)
- Click on "save" without making any changes to the configmap.
- Edit the configmap again and we would be able to see that the configmap data are appended with new line breaks.

Scenario 2:

- Login to rancher
- choosing namespace where the configmaps has to change (Storage > ConfigMaps > click on the three dots > Edit config)
- Click on "remove" on this part of the configmaps which should be replaced
- at the buttom: Use the button "read from file" and choose the new file
- click on "save" button after upload the new file

After that the complete configmaps (include all other parts of the configmaps which not replaced) could not read from the application anymore because new sections have been added in all lines. 

Compare with how it looked originally. The difference is clearly visible.

After that, the only solution is to delete the complete CM and redeploy via kubectl.
This approach is unfortunately not a solution for all their developers because they can only work via Rancher.

Workaround:
Edit the configmap via CLI.

Actual behavior:
Editing configmaps via UI adds new line breaks to the data section corrupting the object and making it unusable for the applications.

Expected behavior:
Editing the configmap from the UI should not corrupt the configmaps.

Files, logs, traces:
Logs available via the SURE reference.

Additional notes:
Support was able to reproduce the same issue in their lab cluster.

### PR DESCRIPTION
**Pull request by rak-phillip**
### Summary

This introduces the capability to customize `jsyaml.dump` options in the `dumpBlock` function, allowing developers to supply all of the dump options specified by `jsyaml.dump()`.

Fixes #10044 

### Occurred changes and/or fixed issues

- Utilize options in `jsyaml.dump` when they are provided to `dumpBlock()`
- Specify `lineWidth: -1` in the `yamlModifiers()` for `configmap.vue`
- Create new e2e test for `configmap`
- Update unit tests for `create-yaml`

### Areas or cases that should be tested

- Creating/Editing/Viewing config maps
- Other areas of Rancher Dashboard that might focus on creating/editing yaml

### CODE REVIEW

**Comment by rak-phillip** [comment]
@yonasberhe23 @izaac I requested a review from either one of you because I touched some e2e tests in this PR. I would definitely appreciate some feedback 🙂

**Comment by rak-phillip** [comment]
It might be easier to review these changes on a commit-by-commit basis.

**Review by yonasberhe23 — APPROVED** [review]
@rak-phillip I've only reviewed the e2e portion of this pr as I'm not familiar with the unit test code. Would probably be best for a second review/approval before merging. e2e portion looks great btw. 
Funny thing is I was working on something similar to your `CodeMirror` po for MachineSets tests but I like yours better. Looking forward to utilizing this code. Thanks!

**Comment by richard-cox** [comment]
@rak-phillip Does this also fix https://github.com/rancher/dashboard/issues/10066 and https://github.com/rancher/dashboard/issues/9841?

**Comment by rak-phillip** [comment]
@richard-cox This PR should fix #10066 as the issue is written in the description, but comments have mentioned that this behavior could be reproduced in other areas of Rancher that deal with YAML. I would like to leave that one open for more investigation and potentially a follow-up PR.

#9841 Doesn't look related to this PR.. I assigned myself to it so that I could take a closer look.

**Review by eva-vashkevich — APPROVED** [review]
lgtm

**Comment by torchiaf** [comment]
I wasn't able to reproduce the issue with `Ingress` objects using 2.7.7 UI version, as some users reported in the comments here https://github.com/rancher/dashboard/issues/10066.
Conversely, the behavior is the same of Config maps when chomping options were not applied, aka: the new lines at the end of the file blocks are stripped, since the block styled applied in `ingress.annotations` is just `|` instead of `|-`.
Morover, the `value` fields in annotations area are simple `InputField` components instead of `TextArea`, so the value field is not visible when the value has more than 2/3 lines.

**Pull request merged**
