### PR TITLE
7582 fix clusterrolebindings

### PR DESCRIPTION
**Pull request by Shavindra**
### Summary
Fixes rancher/dashboard#8554
 

### Occurred changes and/or fixed issues
- Cluster membership list can be grouped by Role
- Project membership is grouped by Project by default
   - All Roles of a user in a project is listed.
   - Each role can be deleted
   - If view in API setting is enabled clicking on role would take the user to View In API
   - Row actions removed

#### Cluster Membership
1. Navigate Explore Cluster > Cluster e.g. local > Cluster & Project members
2. With Cluster Membership tab selected Click add on top right
3. Add a user with a role
4. If you wish you can add same user with different roles
5. In the Cluster Membership list page click on the different grouping options on top right. 
6. Views should change appropriately

#### Project Membership
1. Navigate Explore Cluster > Cluster e.g. local > Cluster & Project members
2. Select Project Membership 
3. For each Project click add using the button on the right hand side
4. If you wish you can add same user with different roles e.g. Custom Role with different roles sleected
5. In the Project Membership list page you'd notice that all roles are grouped together.
6. Clicking on a `X` for each role should remove that role from the user

#### Cluster role bindings
1. Navigate Explore Cluster > Cluster e.g. local > More resources > RBAC > Cluster Role bindings
2. List page should show users, groups and service accounts

### Areas which could experience regressions
- Cluster Membership
- Project Membership
- RBAC cluster role bindings

### Screenshot/Video
image

image

image

### CODE REVIEW

**Comment by richard-cox** [comment]
Adding milestone

**Comment by mantis-toboggan-md** [comment]
@Shavindra is this PR linked to the right issue? #7582 looks like a bug in the Ember UI

**Review by mantis-toboggan-md — CHANGES_REQUESTED** [review]
I see that the cluster membership table allows grouping roles by namespace: does that make sense here? The clusterroletemplatebinding resource does have `metadata.namespace` defined, but from what I can tell, this namespace corresponds to the id of the mgmt cluster currently being viewed. In other words, there is only ever one namespace in this table.

Something else I noticed was that the list of cluster members didn't automatically refresh to include a newly added member when grouped by namespace or role.

**Comment by mantis-toboggan-md** [comment]
> I did think about this. It would require some modifications to ResourceTable component. groupby namespace / flatlist is hardcoded in. I was bit apprehensive to make the change there. If you think I should remove it and should do within this PR. I will do it

I think since the table is used in sooo many places and it'd would take time to validate any changes to it, it would be fine to file a follow-up issue to stop hardcoding group by namespace.

> I couldn't quite replicate this?
Ahhh ok I tried again if I wait on the page it shows up in a few seconds, I guess the cluster I was using was just slower than yours.

**Review by mantis-toboggan-md — APPROVED** [review]

**Pull request merged**
