### PR TITLE
add k3s provisioning as GA in 2.7.0

### LINKED ISSUE #7361: What's New in 2.7.0: add k3s provisioning is GA
Need to add "k3s provisioning going GA" as a new thing in 2.7.0. This will appear in What's New.

### PR DESCRIPTION
**Pull request by gaktive**
Signed-off-by: Gary A Korhonen <gkorhonen@suse.com>

### Summary
Fixes #7361 

### Occurred changes and/or fixed issues

What's New for 2.7.0 now includes mention of k3s provisioning being GA

### Areas or cases that should be tested

Load What's New and ensure that k3s provisioning as GA appears.

### CODE REVIEW

**Review by richard-cox — APPROVED** [review]

**Review by deniseschannon — COMMENTED** [review]
We shouldn't have merged this as this needs more flowery language from @leflambeur

**Comment by richard-cox** [comment]
Apologies, didn't see any additional reviewers and on a mission to branch for 2.7.0.

@gaktive Can you make sure any updates go in to `release-2.7.0` and `master`?

**Comment by richard-cox** [comment]
Just noticed, the what's new page has `title: What's New in 2.6`, which should probably just be `What's New in 2.6`?

**Comment by gaktive** [comment]
Will file a new PR upon updates from @leflambeur

**Comment by leflambeur** [comment]
### k3s provisioning is GA (x86 Only)

- Provisioning K3s clusters on x86 clusters has graduated to GA!

   The fully compliant Kubernetes distribution is simplified, secure and at less than 60mb is perfect for Edge.

**Pull request merged**
