### PR TITLE
backup create page

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
#1124 
Screen Shot 2020-09-04 at 11 59 50 AM
Screen Shot 2020-09-04 at 12 00 00 PM
Screen Shot 2020-09-04 at 12 00 10 PM

### CODE REVIEW

**Comment by vincent99** [comment]
FYI after design meeting today the types for this feature are changing from namespaced to not-namespaced, so you'll end up not having a namespace choice here.

A generated name makes sense for Restores, but the Backups should get the full NameNsDescription (with namespaced=false).  It's a long-lived resource that you may want to go back and edit, you refer to the names of them as part of the restore, it probably becomes part of the filenames written to the backup target.

Resource Set Name -> Resource Set
Insecure TLS Skip Verify -> (needs padding) Skip TLS Verifications
Credential Secret Name -> Credential Secret
Encryption Config Name -> Encryption Config Secret
`* * * * ?` cron placeholder -> `0 * * * *` -- Suggest once an hour instead of once a minute. `*` vs `?` doesn't appear to be relevant to the parser used.

Setting up encryption is not going to be obvious, so I'd pull that out into its own section:

Encryption
(x) Store the contents of backups unencrypted
( ) Encrypt backups using an [Encryption Config Secret] (linking to docs page explaining how to make one based on https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#understanding-the-encryption-at-rest-configuration)
[ Encryption Config Secret |v| ]
```

@mrajashree Does the secret have to have exactly a `encryptionConfig.yaml` key in it?  If so we can use that to only show you relevant secrets.

Move the S3 header above the radios and call it something like "Storage Target" so that's a description of what the radios are for too
Use the backup... -> Use the the default storage target configured during installation
Specify details... -> Use a S3-compatible object store

**Comment by mrajashree** [comment]
Another change from yesterday's design meeting is accepting a field for credentialSecretNamespace in the s3 details. So along with Credential Secret Name there will be another field for Credential Secret Namespace.

@vincent99 even if `Credential Secret Name` is changed to `Credential Secret` in UI, the yaml fields are still `credentialSecretName` and `credentialSecretNamespace` right?
Same question about `Credential Secret Name` changing to `Credential Secret`, the yaml field can still be `encryptionConfigSecretName` right?

Can the cron placeholder show two examples? The golang cron parser library accepts it in two formats, so can we display them both:
```
Descriptors: '@midnight'
Standard crontab specs: 0 0 * * *
```

**Comment by vincent99** [comment]
> Can the cron placeholder show two examples?

Sure @mantis-toboggan-md  can do `placeholder="e.g. @midnight or 0 0 * * *`, though I think few people know about/use the at version...  Ideally we'd have a better control that validates the input, parses it and shows you a human-readable version ("Every Tuesday at 12:45am") or the next few times it will fire, but that's unlikely for now.

<hr/>

> the yaml fields are still credentialSecretName and credentialSecretNamespace right?

Yes, `[thing]Name` is the standard way to name the fields in k8s but we don't label the fields in the UI that way.  The user is selecting a "thing", not a "thing name".

<hr/>

> no the filename ... doesn't always have to be encryptionConfig.yaml ... Right now the operator gets the first key from secret ... should we expect secret to have a particular filename

Yes I think the operator should expect a particular key, and look for only that key.
  - This is easier to explain and deterministic on the backend.
  - And on the frontend @mantis-toboggan-md can further filter the list down to Secrets which have the appropriate key, and link the user to docs on how to make one/disable the encryption option if there aren't any.

<hr/>

> So moving S3 header above radio buttons might not make it clear? Can we say Storage Location above radio buttons instead?

Yes (that's roughly what I suggested):

> Move the S3 header above the radios **and call it something like "Storage Target"** so that's a description of what the radios are for too

> Also I'm not sure I understand the Description box, is it something we expect users to input? and I think maybe we don't need it for these CRDs?

(Almost) all resources in the UIs have a description field for the user to add  their own notes, warnings to others that might try and edit the resources, or whatever else they want.  It's just stored as an annotation.

**Comment by mrajashree** [comment]
@vincent99 
> Yes I think the operator should expect a particular key, and look for only that key.
Okay, the operator can expect the secret to have one key, with name "encryption-provider-config.yaml" then. 

> Yes (that's roughly what I suggested):
>> Move the S3 header above the radios and call it something like "Storage Target" so that's a description of what the radios are for too
ah, my bad I misread that.

**Comment by mantis-toboggan-md** [comment]
Updated per feedback here:
* re-add name and description fields
* remove namespacing
* set credentialSecretName and credentialSecretNamespace from credential secret field
* filter encryption secrets by presence of `encryption-provider-config.yaml` field
* move encryption to its own section with descriptive radio options
* update schedule field with better placeholders
* updated several input labels

Screen Shot 2020-09-08 at 3 50 15 PM
Screen Shot 2020-09-08 at 3 50 26 PM

**Comment by mrajashree** [comment]
@mantis-toboggan-md to confirm, the dropdown for Encryption Config lists secres only from cattle-resources-system namespace.

And the dropdown for credentials shows secrets across all namespaces right? and based on what the user selects, the yaml fields for credentialSecretName and credentialSecretNamespace get populated?

**Comment by mantis-toboggan-md** [comment]
I didn't know the encryption config secret still needed to be namespaced; updating now

**Pull request merged**
