### PR TITLE
Change from api.neuvector.com to permission.neuvector.com api group

### PR DESCRIPTION
**Pull request by williamlin-suse**
The 1st NeuVector/Rancher SSO design uses a CR for each NeuVector permission.
It causes Rancher UI to display the raw nv-perm.xyz strings in the resource drop-down menu of Role creation pages:
(see https://github.com/rancher/dashboard/pull/11184)
```
nv-perm.all-permissions
nv-perm.admctrl
nv-perm.audit-events
nv-perm.authentication
nv-perm.authorization
nv-perm.ci-scan
nv-perm.compliance
nv-perm.events
nv-perm.fed
nv-perm.reg-scan
nv-perm.rt-policy
nv-perm.rt-scan
nv-perm.security-events
nv-perm.config
nv-perm.vulnerability

```
This PR is to change NeuVector apiGroup from api.neuvector.com to permission.neuvector.com and leverage one CRD per NeuVector permission:
```
> kubectl api-resources | grep permission.neuvector.com
admissioncontrol                                 permission.neuvector.com/v1            false        AdmissionControl
auditevents                                      permission.neuvector.com/v1            false        AuditEvents
authentication                                   permission.neuvector.com/v1            false        Authentication
authorization                                    permission.neuvector.com/v1            false        Authorization
ciscan                                           permission.neuvector.com/v1            false        CIScan
cluster                                          permission.neuvector.com/v1            false        Cluster
compliance                                       permission.neuvector.com/v1            false        Compliance
events                                           permission.neuvector.com/v1            false        Events
federation                                       permission.neuvector.com/v1            false        Federation
namespace                                        permission.neuvector.com/v1            false        Namespace
registryscan                                     permission.neuvector.com/v1            false        RegistryScan
runtimepolicy                                    permission.neuvector.com/v1            false        RuntimePolicy
runtimescan                                      permission.neuvector.com/v1            false        RuntimeScan
securityevents                                   permission.neuvector.com/v1            false        SecurityEvents
systemconfig                                     permission.neuvector.com/v1            false        SystemConfig
vulnerability                                    permission.neuvector.com/v1            false        Vulnerability
```
In this way, the NeuVector options in the resource drop-down menu will be more readable to users

### CODE REVIEW

**Comment by richard-cox** [comment]
Once merged this will need backporting to the `release-2.9` branch

**Comment by williamlin-suse** [comment]
If it's late to merge this change to Rancher 2.9 branch, NV 5.4 will support both approaches.
Let us know the decision so that we can update NV code accordingly.

**Comment by selvamt94** [comment]
> @williamlin-suse We might be able to get this in to 2.9.0, would someone your side be able to QA the change?

@richard-cox I am from NeuVector QA team. We will do the testing for this change. I have been testing this feature on Rancher 2.9.0 alpha7 build. Please give us some detail which image need to be tested. Thanks!.

**Comment by richard-cox** [comment]
Given some issues e2e test wise lets go with the suggestion from https://github.com/rancher/dashboard/pull/11527#issuecomment-2250230396 . 

1. Update goes in to v2.10.0 (this PR) (rancher/dashboard master branch)
2. Update goes in to v2.9.next1 (next feature release after 2.9.0) (rancher/dashboard release-2.9 branch ... to merge after 2.9.0 is released).

That gives us plenty of time to discuss (given question in slack), review, merge and QA the changes

**Comment by richard-cox** [comment]
https://github.com/rancher/dashboard/pull/11531 has merged, this PR will need to rebase from `master` and then the gates should pass

**Pull request merged**
