### PR TITLE
Embed project monitoring metric dashboards

### LINKED ISSUE #7286: Missing metrics tabs on workloads for project members with project monitoring v2
**Is your feature request related to a problem? Please describe.**
Project members/owners, that have access to a project with project monitoring v2 installed, but that do not have access to the cluster monitoring v2, should be able to see the workload and pod metrics dashboards from the project monitoring directly in the Rancher UI on the workload and pod detail pages.

**Describe the solution you'd like**
If a user does have access to a project monitoring, but not access to the cluster monitoring, the UI should embed the Grafana dashboards from the project monitoring.

Project monitoring v1 also did this.

**Describe alternatives you've considered**
Is workararound available and implemented? kind of, but with bad usability
What is the workaround: From a workload or pod page, you'd need to go to Monitoring -> Project monitoring -> Choose your project -> open Grafana -> find the right dashboard -> choose the namespace in the dashboard -> choose the workload or pod

SURE-5474

### PR DESCRIPTION
**Pull request by bashofmann**
### Summary
This embeds the project monitoring Grafana metric dashboards if they are present and user has no access to cluster monitoring.

Fixes #7286

### Technical notes summary
To test:
* Create a cluster
* Install cluster monitoring
* Install project federator
* Install project monitoring into the default project
* Create a user in Rancher that only has access to the default project in the cluster as a project member
* Deploy a workload into the default project
* Check that the limited user can see grafana dashboards under the pod detail page and workload detail page metrics tabs

### Areas or cases that should be tested
Pod detail page and workload detail page.

### Areas which could experience regressions
Embedding of Grafana metrics dashboards on pod and workload detail pages

### Screenshot/Video
Bildschirmfoto 2023-06-09 um 16 25 20

### CODE REVIEW

**Comment by richard-cox** [comment]
@bashofmann A merge conflict has popped up. Can you take a look? @codyrancher @rak-phillip if it's a simple can you address?

**Comment by rak-phillip** [comment]
Branding e2e tests failed. Attempting another run

```
  1 failing

  1) Branding
       Private Label:

      Timed out retrying after 60000ms
      + expected - actual

      -'Rancher e2e'
      +'Rancher'
```

**Comment by rak-phillip** [comment]
@bashofmann can you provide a little more detail for the testing steps? 

It appears that I can't get any grafana dashboards to render in my environment. I'm not 100% sure what "Install project monitoring into the default project" and I want to make sure I'm testing this properly.

**Comment by rak-phillip** [comment]
rerunning tests due to another unrelated e2e error

```
  1 failing

  1) User can update their preferences
       Can navigate to Preferences Page:
     AssertionError: Timed out retrying after 60000ms: Expected to find element: `.tooltip.popover.vue-popover-theme`, but never found it.
      at UserMenuPo.isOpen (https://127.0.0.1/__cypress/tests?p=cypress/e2e/tests/pages/user_menu/preferences.spec.ts:1323:34)
      at Context.eval (https://127.0.0.1/__cypress/tests?p=cypress/e2e/tests/pages/user_menu/preferences.spec.ts:1346:30)
```

**Comment by bashofmann** [comment]
@rak-phillip For the general project monitoring docs see https://ranchermanager.docs.rancher.com/v2.7/pages-for-subheaders/prometheus-federator-guides

**Review by rak-phillip — APPROVED** [review]
LGTM - running into issues against `2.7-head` that make testing this change nearly impossible, but these issues are unrelated to this PR.

Testing in 2.7.5 demonstrates the functionality sufficiently.

## Issues

- https://github.com/rancher/dashboard/issues/9336
- https://github.com/rancher/dashboard/issues/9352

**Comment by rak-phillip** [comment]
Rerunning failed validate job before merging

**Pull request merged**
