### PR TITLE
Remove deprecated Nuxt components

### LINKED ISSUE #11273: Nuxt references in components to be reviewed and renamed
# Description

References in components to be reviewed and renamed
  - Nuxt folder
    - Build indicator (can be abstracted) https://github.com/rancher/dashboard/blob/master/shell/components/nuxt/nuxt-build-indicator.vue
    - Error page (can be abstracted) https://github.com/rancher/dashboard/blob/master/shell/components/nuxt/nuxt-error.vue
    - NuxtChild (TBD use) https://github.com/rancher/dashboard/blob/master/shell/components/nuxt/nuxt-child.js
    - Link (TBD use) https://github.com/rancher/dashboard/blob/master/shell/components/nuxt/nuxt-link.client.js
    - Loading (can be abstracted) https://github.com/rancher/dashboard/blob/master/shell/components/nuxt/nuxt-loading.vue
  - Carousel (not sure if used) https://github.com/rancher/dashboard/blob/master/shell/components/Carousel.vue#L183

### PR DESCRIPTION
**Pull request by rak-phillip**
### Summary

Fixes #11273

This removes Nuxt components that are either unused or deprecated and unsupported in Vue3.

#### Deprecated

- shell/components/nuxt/nuxt-link.client.js
- shell/components/nuxt/nuxt-child.js

#### Unused

- shell/components/nuxt/nuxt-build-indicator.vue
- shell/components/nuxt/nuxt-error.vue
- shell/components/nuxt/nuxt-loading.vue

### Technical notes summary

- `NuxtLink` should have been replaced with `router-link`
- `NuxtChild` should have been replaced with `router-view`

### Areas or cases that should be tested

My primary concern is extensions at this point. We will need to ensure that they do not have any instances of 

- `NuxtLink`
- `nuxt-link`
- `NLink`
- `n-link`
- `NuxtChild`
- `nuxt-child`
- `NChild`
- `n-child`

### Checklist
- [ ] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [ ] The PR has a Milestone 
- [ ] The PR template has been filled out
- [ ] The PR has been self reviewed 
- [ ] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [ ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Comment by cnotv** [comment]
> My primary concern is 
... Harvester 😅 

Given the current state of the art and version matrix, we may well go ahead with this one.

**Review by codyrancher — APPROVED** [review]
There are definitely still references in kubewarden https://github.com/search?q=repo%3Arancher%2Fkubewarden-ui+n-link&type=code

I haven't checked elemental. I'm fine if we just want to consider it a part of migrating to vue3.

**Comment by cnotv** [comment]
> I haven't checked elemental. I'm fine if we just want to consider it a part of migrating to vue3.

Yeah, they have to be converted into router links anyway.

**Comment by jordojordo** [comment]
I'm fine with this change, I have a growing list of issues to fix with Kubewarden and getting rid of `n-link` wouldn't be much to add. It would be nice to have some documentation for extensions with alternative solutions.

**Comment by cnotv** [comment]
> I'm fine with this change, I have a growing list of issues to fix with Kubewarden and getting rid of `n-link` wouldn't be much to add. It would be nice to have some documentation for extensions with alternative solutions.

The replacement of Nuxt links is probably something overly specific to extensions that used Nuxt prior to migration, although it has already been removed in 2.9. I am not entirely sure we would need to make a documentation for Nuxt, am I wrong?

For related replacement, it's quite straightforward and you could reference the related PR: https://github.com/rancher/dashboard/commit/7e703b4c740b7c01173a8066aea46d227d66f770

**Review by torchiaf — APPROVED** [review]
LG

**Pull request merged**
