### PR TITLE
Fix dashboardExists monitoring installation check

### LINKED ISSUE #6977: Dashboard requests grafana URLS even when v2 monitoring is not installed
Look at the browser log - we fetch grafana URLs even when v2 monitoring is not installed.

Should only make those requests if v2 monitoring is enabled.

### PR DESCRIPTION
**Pull request by jordojordo**
### Summary
Fixes #6977 

### Occurred changes and/or fixed issues

Replaced the check for a monitoring installation within `dashboardExists`. The original check was looking for a schema for `monitoring.coreos.com.servicemonitor` which exists regardless if monitoring is installed.

### Areas or cases that should be tested

- Any place where `allDashboardsExists` is called
  - Cluster explorer page
  - Node detail
  - Pod detail
  - Workload detail
  - Harverster list page
  - Harverster `kubevirt.io.virtualmachine` detail

### CODE REVIEW

**Review by aalves08 — APPROVED** [review]
gave a proper round of tests, no error on console in the areas mentioned for testing. LGTM

**Review by aalves08 — CHANGES_REQUESTED** [review]
taking a look at an issue... will provide more feedback

**Comment by aalves08** [comment]
Hey @jordojordo , so there's an issue within your branch (this one) where if you want to check `POD` details view you get a blocking error on the console (check screenshots). Also, it's loading the `details/workload` view rather than `details/pods`.

I believe that the problem is that this branch is not up-to-date. I think Shavin did some work around this area a few days ago. Can you rebase and check this?

Otherwise, code and testing it all LGTM 🙏 

Thanks!

**This branch**
Screenshot 2022-10-03 at 09 29 42

**my master**
Screenshot 2022-10-03 at 11 04 45

**Comment by jordojordo** [comment]
@aalves08 I've updated the branch and tested the pod detail page, everything appears to be working as it should.

**Review by aalves08 — APPROVED** [review]
LGTM

**Pull request merged**
