### PR TITLE
Auth wizard - active directory

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
#827 

I'd like some feedback on what people think of the nav experience here. As it is now, the 'manage access' section of the app routes to 'Manage Site Access' if an auth provider is configured, otherwise, to the wizard. Would also like to know what people think should be in the side nav here.

Screen Shot 2020-07-14 at 8 58 29 AM
Screen Shot 2020-07-14 at 8 58 36 AM
Screen Shot 2020-07-14 at 8 58 58 AM
Screen Shot 2020-07-14 at 8 59 05 AM
Screen Shot 2020-07-14 at 9 01 09 AM

### CODE REVIEW

**Comment by deniseschannon** [comment]
When selecting "Manage Access", it should default to the Auth page, which is either the wizard with no auth configured or the page that has site access. 

The left side nav for when selecting Manage Access should look like:
```
Authentication
Users
Groups
RoleBindings
```

Can we add in icons for each provider like we did for the ember UI? @lvuch can you help make an icon that works in dark and light mode?

**Comment by vincent99** [comment]
I will get users/groups/rolebindings on the left if you just want to handle the Auth provider one.

The basic flow seems fine to me, agree on icons and the gradient bars need more text or they're kind of pointless.  The test page needs to talk about how you're tying the account you login as to the [local] user you are currently logged in as, so you should use "you" and not a random service account or someone else's account.

**Comment by deniseschannon** [comment]
Proposed Text, which most is taken directly from the Ember UI. 

```
Step 1: 
Select an external authentication provider. By connecting to an external authentication provider, Rancher can use the users and groups to apply role bindings. 

Step 2: 
Configure an Active Directory Server. Enter the address, port, and protocol to your Active Directory server. `389` is the standard port for insecure, `636` for TLS. 

Step 3:
Customize Schema. If your schema does not match the standard ActiveDirectory format, you can customize it. 

Step 4: 
Test and enable authentication. Check that everything is configured correctly by testing authentication with your Active Directory account.
```

WitIn a warning banner above the username/password fields for test & enable. 

```
When testing and enabling external authentication, Rancher will associate the Active Director user (i.e. external principal) with the current user's local identity (i.e. who is currently logged in, which is usually the "Default Admin"). In other words, the Active Directory user will receive all role bindings of the currently logged in user. 
```

@vincent99 thoughts on above?

**Comment by deniseschannon** [comment]
@mantis-toboggan-md Before merging, I want to update the wizard to be using the button layout/style that @lvuch will cover with you.

**Pull request closed without merging**
