### PR TITLE
Secrets UX update

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
#720 
#498 (requires https://github.com/rancher/rancher/pull/29792)
#1702 
Screen Shot 2020-10-28 at 3 28 29 PM
Screen Shot 2020-10-28 at 3 28 52 PM
Screen Shot 2020-10-28 at 3 29 36 PM
Screen Shot 2020-10-28 at 3 29 15 PM
Screen Shot 2020-10-28 at 3 29 24 PM
Screen Shot 2020-10-28 at 3 29 44 PM

Remaining issues (@deniseschannon  @vincent99):
* should cert/ssh data be hidden too? What should that look like? Matching the other secret types (big block of asterisks) would be pretty ugly
* need descriptions for secret subtypes in CruResource's first step

### CODE REVIEW

**Review by lvuch — CHANGES_REQUESTED** [review]
re: "should cert/ssh data be hidden too" yes.

vince and I discussed yesterday cases that need sensitive info handling which i will mock and attach to related issues as well as this pr
-if long….toggle view and snippet box with copy to clipboard
-if short dot font and copy to clipboard

**Comment by vincent99** [comment]
You don't have to construct a version of the string consisting of only `*` 's;  there's a `dotsfont` (in assets/styles/fonts/_dots) that is a font where all the non-whitespace characters are displayed as`•`.

I thought we were doing a buttongroup or checkbox toggle or similar to choose whether to show or hide the value?

For non-opaque types (Cert, SSH key, basic, ...) you could show the "public" part (certificate, public key, username) and only obscure the private one (private key, password)

Yes there should be a copy button on each row, or click value to copy or similar (@lvuch)

It doesn't look like newlines in the value are being turned into `<br>` s, ---- END CERT... isn't on it's own line.

The values would probably look better in monospaced fonts

The field on cert titled "CA Certificate" should just be "Certificates".

These examples look ok but if there's short keys and long wide values the table (/non-table-grid-flexbox thing) should adjust so that the value can get most of the width instead of having chasms of empty space on a 50% width key field.

For the table of key/values version (opaque), the key name should be top-aligned (with the first line of the the value) instead of centered (where it's harder to tell which value it belongs to)

FWIW the pictured SSH key isn't a SSH key; (this doesn't really matter but ssh-pub-keys are parsed and teh comment is shown in the list view if found)

**Comment by lvuch** [comment]
https://xd.adobe.com/view/3cf0dddb-70e3-4309-885f-f8d847399a0d-69a3/

**Review by lvuch — COMMENTED** [review]
pushed a few visual tweaks and new icons

**Pull request merged**
