### PR TITLE
[INT] Replaced vue-clipboard2 library with clipboard-polyfill

### LINKED ISSUE #9536: Replace vue-clipboard2 with Vue3 compatible lib
# Description

Replace current library `vue-clipboard2` with alternative, e.g. [useClipboard](https://vueuse.org/core/useClipboard/) as component.

## Context

As identified in the [migration report](https://github.com/rancher/dashboard/issues/9028#issuecomment-1582565599), it is not possible to use the same library for clipboard functionalities.

As defined in https://github.com/rancher/dashboard/issues/9842 we have 2 components for this and we may take the chance to deal with that as well.

The replacement should affect pretty much 3 places: Vue setup, Jest setup and component.

### PR DESCRIPTION
**Pull request by eva-vashkevich**
### Summary
Fixes #9536 

Replaced vue-clipboard2 library with clipboard-polyfill as recommended by @nwmac.
clipboard-polyfill was chosen because it is supported by older browser versions. In the future, this library is unlikely to continue being maintained and should be eventually replaced by navigator.clipboard.writeText(...)

### Occurred changes and/or fixed issues

Replaced all uses of $copyText with a new function. Everything that needs to copy to clipboard is affected
 
### Areas or cases that should be tested

Verify that the following copies content to the clipboard
1. Go to 'Cluster management' -> select a cluster -> click 'Copy KubeConfig to Clipboard'
2. Go to 'Users & User administration' -> 'Create' -> 'Generate a random password' -> Copy
3. Harvester -> Virtual machine image -> Copy image URL
4. First time login -> Both commands should be copied to clipboard on click.
5. Any other areas that allow copying to clipboard 

### Areas which could experience regressions

There should be no change in the behaviour.

### CODE REVIEW

**Review by nwmac — APPROVED** [review]
LGTM

**Comment by eva-vashkevich** [comment]
> Have you tried to merge all the components into one and replace the markup with the component? It is so inconvenient to have it in so many places and the part of the migration would include at least to try to reduce the number. If it turned complex we may obviously deal in a separated issue, but would be great if you could create it so you can add directly there the report. E.g. the style is different, so we put a screenshot of the 2 versions.

@cnotv sorry, which markup are you referring to?

**Comment by cnotv** [comment]
> @cnotv sorry, which markup are you referring to?

The markup in `shell/components/form/Password.vue`, although I remembered just a moment after that we have already an issue for that, so forget what I say. Sorry 🙇

**Review by mantis-toboggan-md — APPROVED** [review]
lgtm

**Pull request merged**
