### PR TITLE
Fixed icon size

### LINKED ISSUE #7496: Correct icon sizes after updated library
# Description

Some icons have been changed in size after the update of `rancher/icons`.

## Context

Since update to `rancher/icons#v2.0.8`, some icons have been changed in size due custom values in the CSS.
E.g. 
- close icon ([Banner](https://rancher.github.io/storybook/?path=/docs/components-banner--primary), BannerGraphic, NamespaceFilter), 
- chevron down ([Select](https://rancher.github.io/storybook/?path=/docs/components-form-select--select))
- info and alert ([LabeledInput](https://rancher.github.io/storybook/?path=/docs/components-form-input--labeled-input))
- checkmark (`/c/local/settings/management.cattle.io.feature`)
- plus (Tab)

List of the icons can be found in [this commit](https://github.com/rancher/icons/commit/e3ca53a36c60cabd69d53ecc86e9f4be6e6a8cbf)1.

Please ensure components quality also through the [styleguide](https://rancher.github.io/storybook).

### PR DESCRIPTION
**Pull request by bisht-richa**
### Summary
Fixes #7496

Fixed icon size in following components:

close icon (Banner BannerGraphic, NamespaceFilter),
chevron down (Select)
info and alert (LabeledInput)
checkmark (/c/local/settings/management.cattle.io.feature)
plus (Tab)

### CODE REVIEW

**Review by cnotv — CHANGES_REQUESTED** [review]
The issue was about investigate for further icons before fix, including:
- Opening Storybook and checking all the components there
- Searching all the changed icons inside the codebase and ensure the view is correct, as some components are not in Storybook

Some error example caught in the first case:

Screenshot 2022-11-28 at 12 07 27
Screenshot 2022-11-28 at 12 08 43

Some (which were already mentioned tbh) while navigating for missing stories, like the namespace filter in the navigation for the cluster:

Screenshot 2022-11-28 at 12 15 19

**Comment by cnotv** [comment]
While reviewing the Growl PR I also noticed there the close icon is not properly scaled.
Please at least search in the code for all the `icon-close` cases, since are 100% all broken and used widely.

**Comment by nwmac** [comment]
@bisht-richa This needs rebasing - the commit history is not right.

**Review by cnotv — APPROVED** [review]
LGTM

**Pull request merged**
