### PR TITLE
Updates following `release-2.9` branch

### PR DESCRIPTION
**Pull request by richard-cox**
References to `v2.9-head` will need updating when there's a rancher 2.10 build

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Review by aalves08 — COMMENTED** [review]
I think we are missing the changes in `package.json` for the e2e tests for `docker:local:start`:

https://github.com/rancher/dashboard/pull/10189/files

**Comment by richard-cox** [comment]
@aalves08 there's no 2.10 build yet. once rancher/rancher has branched we can update

**Review by aalves08 — APPROVED** [review]
LGTM

**Comment by richard-cox** [comment]
@aalves08 made a couple of tweaks, one was causing e2e to fail (we test against latest which is 2.9... but expecting what's new text to contain 2.10)

**Review by torchiaf — APPROVED** [review]
LGTM

**Review by aalves08 — APPROVED** [review]
LGTM

**Pull request merged**
