### PR TITLE
Fix rendering raw html content

### LINKED ISSUE #11689: Vue3: Namespace Selector with multiple namespaces has wrong hover
After selecting 3+ namespaces we stop displaying individual namespaces and instead show a number with a popdown. The popdown shows html instead of a list of namesapces.

https://github.com/user-attachments/assets/d3fdb621-07d5-48bc-8600-60d38b8db52f

## Acceptance Criteria

- [ ] The hover should display the appropriate text.
image

### PR DESCRIPTION
**Pull request by momesgin**
### Summary
Fixes #11689 

### Technical notes summary

After migrating from `v-tooltip` library to `floating-vue` the default value for rendering tooltip's html content has changed to `false`. This PR fixes the issue by setting `html: true` globally.
For more info refer to the library's [migration doc](https://floating-vue.starpad.dev/migration/migration-from-v2).
### Screenshot/Video

https://github.com/user-attachments/assets/5f641741-c1d0-4a0c-86f5-e30dc24886cc

There are some styling discrepancies compare to Vue2 that'll be fixed by #11763  

### Checklist
- [ ] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [ ] The PR has a Milestone 
- [ ] The PR template has been filled out
- [ ] The PR has been self reviewed 
- [ ] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [ ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Review by codyrancher — DISMISSED** [review]

**Comment by rak-phillip** [comment]
Before merging this, can we see if updating the floating vue options in `shell/initialize/install-plugins.js` will fix the issue? If that works, we won't have to address each instance individually.

**Comment by codyrancher** [comment]
> Before merging this, can we see if updating the floating vue options in `shell/initialize/install-plugins.js` will fix the issue? If that works, we won't have to address each instance individually.

Sounds like a good catch

**Review by codyrancher — APPROVED** [review]
Wondering if we should do the same code sharing with config.

**Comment by codyrancher** [comment]
> > Wondering if we should do the same code sharing with config.
> 
> not sure if I understand your point, could you please explain?

Nothing I want you to change here. 

I just noticed we duplicate the config for the ShortKey plugin and we could use what you did here to have one config we import in both places.

**Comment by momesgin** [comment]
> > > Wondering if we should do the same code sharing with config.
> > 
> > 
> > not sure if I understand your point, could you please explain?
> 
> Nothing I want you to change here.
> 
> I just noticed we duplicate the config for the ShortKey plugin and we could use what you did here to have one config we import in both places.

Oh I see, btw sorry I had to fix a lint warning, need your re-approval

**Review by codyrancher — APPROVED** [review]

**Pull request merged**
