### PR TITLE
[UI] Export manifest as Yaml file

### PR DESCRIPTION
**Pull request by torchiaf**
### Summary
Fixes https://github.com/epinio/ui/issues/227

### CODE REVIEW

**Comment by torchiaf** [comment]
> This just changes the file extension, the contents remain json.
> 
> 1. To keep things neat get the manifest data via `resource.fetchPart('manifest')`. This is already in YAML so just needs saving as such
> 2. To confirm - YAML manifest can be uploaded when creating an app (`onManifestFileSelected` uses `jsyaml.load` which i think accepts yaml?)

Thanks Richard, just updated to download the Yaml file using the `manifest` API. There is a bug in the manifest payload, `Kind` property is missing @enrichman

**Comment by enrichman** [comment]
The `Kind` field is internal and it should not be available actually.

We should drop it also from the JSON.

**Comment by torchiaf** [comment]
> 2\. onManifestFileSelected

Ok, I though we would receive it since it is part of `ApplicationOrigin` type.

**Comment by richard-cox** [comment]
> The `Kind` field is internal and it should not be available actually.
> 
> We should drop it also from the JSON.

Would that be soon, and is there an issue to track the work @enrichman? There's a single place in the UI that we use it, think we can make that work without though (by determining which properties are populated).

**Pull request merged**
