### PR TITLE
Fix plugin pkg tsconfig

### PR DESCRIPTION
**Pull request by nwmac**
- Fixes various issues with plugins in standalone repositories.
- Moved the files for the creators into a `files` folder.
- Added a new creator to help update an existing extension to latest shell version
- Generated type definitions when publishing shell - addresses typescript issues when developing outside of dashboard repo

### CODE REVIEW

**Review by richard-cox — COMMENTED** [review]
This make sense in theory and I've done a desktop review. However I failed to test it. My aim was to try my `example` plugin from https://github.com/rancher/ui-plugin-examples/pull/1 but hit some snags

- Building shell and publishing to veradaccio
  - My global yarn packages weren't on my path, had to add that manually to get the `veradaccio` command to be recognised. I'll update docs with this info when i'm back
  - The publish-shell command fails with `couldn't publish shell after publishing other packages`. 
    - First attempt i'd installed the creator packages before running the script. After removing `~/.local/share/verdaccio/storage/@rancher` i still got the same error
- Manually running `typegen.sh` and yarn linking shell to the ui-plugin-examples world
  - script succeeds with i think the right output
  - running `yarn run build-pkg homepage` succeeds
  - running `yarn run build-pkg example` fails
    - Cannot find module '@components/Banner/Banner.vue'
    - import xor from 'lodash/xor';
    - No overload matches this call ('Vue' in TS component)
    - Cannot find module '@rancher/auto-import'

**Comment by richard-cox** [comment]
1) from this branch `yarn link` `./shell`, from ui-plugin-examples `yarn link @rancher/shell`, `API=xyz yarn dev`
    ```
    ERROR  Failed to compile with 169 errors                                                                                                                                                
    friendly-errors 12:00:08
  
    These dependencies were not found:                                                                                                                                                       
    friendly-errors 12:00:08
                                                                                                                                                                                           friendly-    errors 12:00:08
    * @components/BadgeState in ./node_modules/cache-loader/dist/cjs.js??ref--6-0!./node_modules/thread-loader/dist/cjs.js??ref--6-1!./node_modules/babel-loader/lib??ref--6-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/components/Carousel.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--6-0!./node_modules/thread-loader/dist/cjs.js??ref--6-1!./node_modules/babel-loader/lib??ref--6-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/components/ResourceDetail/Masthead.vue?vue&type=script&lang=js& and 4 others
    * @components/Banner in ./node_modules/cache-loader/dist/cjs.js??ref--6-0!./node_modules/thread-loader/dist/cjs.js??ref--6-1!./node_modules/babel-loader/lib??ref--6-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/chart/istio.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--6-0!./node_modules/thread-loader/dist/cjs.js??ref--6-1!./node_modules/babel-loader/lib??ref--6-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@rancher/shell/chart/monitoring/prometheus/index.vue?vue&type=script&lang=js& and 36 others
    ```
2) `yarn link / yarn link @rancher/shell` shell as per step 1, `yarn build-pkg extension-crd`
   ```
     ERROR  Failed to compile with 2 errors                                                                                                                                                                    12:12:46
    
    These dependencies were not found:
    
    * @components/Form/Checkbox in /home/richard/dev/github/rancher/ui-plugin-examples-richard/node_modules/cache-loader/dist/cjs.js??ref--14-0!/home/richard/dev/github/rancher/ui-plugin-examples-richard/node_modules/thread-loader/dist/cjs.js!/home/richard/dev/github/rancher/ui-plugin-examples-richard/node_modules/babel-loader/lib!/home/richard/dev/github/rancher/ui-plugin-examples-richard/node_modules/cache-loader/dist/cjs.js??ref--2-0!/home/richard/dev/github/rancher/ui-plugin-examples-richard/node_modules/@vue/cli-service/node_modules/vue-loader/lib??vue-loader-options!/home/richard/dev/github/rancher/dashboard-neil/shell/components/SortableTable/index.vue?vue&type=script&lang=js&

   ```
3) After running through https://rancher.github.io/dashboard/guide/plugins for `create-app` (with `verdaccio`) i get the following errors when trying to run `API=xyz yarn dev`
    ```
     ERROR  in ./node_modules/vue-resize/dist/vue-resize.css                                                                                                                                 friendly-errors 12:09:18
    
    Module build failed (from ./node_modules/css-loader/dist/cjs.js):                                                                                                                        friendly-errors 12:09:18
    ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
     - options.modules has an unknown property 'compileType'. These properties are valid:
       object { auto?, mode?, exportGlobals?, localIdentName?, localIdentRegExp?, context?, hashPrefix?, getLocalIdent? }
        at validate (/<snip>/my-app/node_modules/schema-utils/dist/validate.js:98:11)
        at Object.loader (/<snip>/my-app/node_modules/css-loader/dist/index.js:36:28)
    ```

**Comment by nwmac** [comment]
@richard-cox Fixed 1 and 2.

**Comment by nwmac** [comment]
@richard-cox I could not reproduce (3) - so either its fixed or we will need to take a look together.

**Review by richard-cox — APPROVED** [review]

**Comment by rak-phillip** [comment]
I'm testing this PR out to see if it fixes some issues I've been having with linking `@rancher/shell` in Rancher Desktop. Before testing in Rancher Desktop, I'm testing against the Rancher Plugins Examples repo. 

It looks like we receive a lot of linting errors related to Rancher Components, for example:

```
ERROR in ../rancher-dashboard-pr/pkg/rancher-components/src/components/Form/Radio/RadioButton.vue
Module Error (from ./node_modules/eslint-loader/dist/cjs.js):

/home/phillip/Development/rancher-dashboard-pr/pkg/rancher-components/src/components/Form/Radio/RadioButton.vue
   15:8   warning  Trailing spaces not allowed                             no-trailing-spaces
   17:8   warning  Trailing spaces not allowed                             no-trailing-spaces
   23:8   warning  Trailing spaces not allowed                             no-trailing-spaces
   25:8   warning  Trailing spaces not allowed                             no-trailing-spaces
   33:8   warning  Trailing spaces not allowed                             no-trailing-spaces
  132:5   error    Disallow self-closing on HTML void elements (<input/>)  vue/html-self-closing
  159:49  error    'class' should be on a new line                         vue/max-attributes-per-line
  160:34  error    ':k' should be on a new line                            vue/max-attributes-per-line

✖ 8 problems (3 errors, 5 warnings)
  3 errors and 5 warnings potentially fixable with the `--fix` option.
```

I'm wondering if it makes sense to attempt completing work associated with updating our `@rancher/component` imports (#7425) to see if we can't resolve issues like this.

**Review by richard-cox — APPROVED** [review]

**Pull request merged**
