### PR TITLE
Add docs and comments on how Rancher handles Helm chart values

### PR DESCRIPTION
**Pull request by catherineluse**
This PR contains no code changes. It addresses https://github.com/rancher/dashboard/issues/5904 by adding developer docs and comments about Helm chart values in Rancher.

## Background

I created this documentation for two reasons:

- As part of the work that needs to be done for project monitoring, Sean needs to create a component that allows users to manipulate values in a `ProjectHelmChart` custom resource. We didn't include that component in Rancher v2.6.5 because we weren't sure how much logic from the regular Helm chart install/upgrade process also applied to what the user experience should be for editing the `ProjectHelmChart`. These docs should help us figure out how to either tailor this component to the needs of the `ProjectHelmChart` or to helm create a much simplified version of the component just for that purpose.
- Arvind requested docs on specifically what values Rancher injects into Helm chart values so that in the future, we can move toward a Helm chart upgrade process in which Rancher injects values into a ConfigMap and the Helm chart app itself can use the values from there. That process would place more control into the hands of chart developers and could help prevent problems when upgrading Helm chart apps.

## Summary

The original issue mentioned a four-way merge for upgrading Helm chart apps, but I didn't find evidence of a four-way merge. The logic seems to be simpler than that. If you are upgrading a Helm chart app, the Rancher UI fetches the standard values.yaml for the source chart and compares them with the actual values. It takes the difference and assumes all differences are "user values" or user-customized values. Then when you select a chart version to upgrade to, it applies the customizations of the old chart onto the new chart to set up the default values of the values.yaml form. That's the most complicated thing that happens.

## New developer docs

The upshot of what I found is added to the new developer docs here: https://github.com/rancher/dashboard/blob/c9c09b34af9a7613795ef2ba17cccb21fbf03326/docs/developer/helm-chart-apps.md

## Tech debt

While documenting this logic I found some opportunities to clean up the code and opened a tech debt issue about it. https://github.com/rancher/dashboard/issues/6069

### CODE REVIEW

**Comment by mantis-toboggan-md** [comment]
It looks like this build is failing because of a couple added console.logs causing lint warnings, otherwise LGTM: your explanation aligns with my understanding of this functionality.

**Comment by mantis-toboggan-md** [comment]
It looks like this build is failing because of a couple added console.logs causing lint warnings, otherwise LGTM: your explanation aligns with my understanding of this functionality.

**Review by mantis-toboggan-md — CHANGES_REQUESTED** [review]
Minor request: console.logs need to be removed or have `// eslint-disable-line no-console` added, otherwise this is great

**Comment by catherineluse** [comment]
Removed the console.logs

**Review by mantis-toboggan-md — APPROVED** [review]

**Pull request merged**
