### PR TITLE
Auto focus propt remove

### PR DESCRIPTION
**Pull request by scures**
### Summary
Fixes # https://github.com/epinio/ui/issues/151

### Technical notes summary

Replaced the html `input` element with the `LabeledInput` component that already handles the `AutoFocus` functionality
The changes are under the `PromptRemove` component.

### Areas or cases that should be tested

Reproduce the steps according to https://github.com/epinio/ui/issues/151, a new behavior should be observed where the input it's automatically focused.

### CODE REVIEW

**Comment by mmartin24** [comment]
Test on branch seems to work: https://github.com/epinio/ui/issues/151#issuecomment-1261024649

**Comment by nwmac** [comment]
@scures I think this needs to be rebased with master to fix the failing check

**Comment by richard-cox** [comment]
This adds an auto focus to the base modal we show when removing resources. We don't do this anywhere else and my concern is that it will open the flood gates for requests to apply this everywhere. @nwmac / @kwwii should we still make this change?

**Review by richard-cox — APPROVED** [review]
Spoken to Neil, we'll get this in and face the fallout when/if it comes in

**Pull request merged**
