### PR TITLE
ui-banners, ui-pl, ui-logos settings page

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
#2893 #2896 #2894
Screen Shot 2021-05-10 at 7 13 38 AM

### CODE REVIEW

**Comment by codyrancher** [comment]
A couple things I noticed that I think need to be addressed.
1. The logo isn't appearing in the slide out for me.
2. Uploading the light logo doesn't seems to silently fail when uploading an image that's too large.

logo
too-large

**Review by codyrancher — APPROVED** [review]
LGTM. One thing you may want to add is putting a max-width max-height on the branding image because as is it can overflow it's container.

image

**Comment by mantis-toboggan-md** [comment]
> When I upload logos the page won't scroll so I can't save

Nice catch; I broke scrolling everywhere :) should be fixed now.

**Comment by nwmac** [comment]
@mantis-toboggan-md This looks good to me - I think there are a few tweaks we could make to layout of the Branding settings page, but I think we should go ahead and get this in. Can you resolve the conflict.

My minor suggestions are:

- Put the issues URL input under the private label
- Move the info box for issues URL and for Fixed banners out of tooltips and show them under the heading/control
- Under logo, add a text line saying where the logo is used, max file size
- Preview box for logo - can get quite large - I would have a max width/height on these
- For fixed banners, make the text box full width and move the colour selectors underneath (users may want quite long text, so nice to see it all)
- There is an <input type="color"> control that has a build-in color picker - we should create a color chooser control that uses this and use it for the color boxes for banner text color and background color
- Can we add a heading "Branding" to the config page (same as on settings and feature flags)

**Pull request merged**
