### PR TITLE
10027: add e2e test

### LINKED ISSUE #10027: Charts List - Using the filters removes entries from the carousel
**Setup**
- Rancher version: 2.7.?? (probably since carousel came in)

**Describe the bug**
- Filtering by either repo, category or text query affects entries in the carousel
- If the user types text, or toggles a repo this can lead to large areas of the page that flash around
- The carousel should be free of those filters, with a fixed set of entries 

**To Reproduce**
- Nav to any cluster --> Apps --> Charts
- Enter a random string in the text filter

**Result**
- Carousel blips whilst it removes entries on type... and then disappears completely

**Expected Result**
- Carousel remains static

**Screenshots**

Content is broken when searching
image

No carousel given user search term
image

### PR DESCRIPTION
**Pull request by aalves08**
### Summary
Fixes #10027 

### Occurred changes and/or fixed issues

- add e2e test where filtering by either repo, category or text query should not affect entries in the carousel, as per description of #10027 

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Comment by aalves08** [comment]
@richard-cox  if this goes in, we can remove the label `automation-candidate` and remove the label `QA-manual-test`

**Review by yonasberhe23 — CHANGES_REQUESTED** [review]
this test looks good to me but maybe we add some checks for the other filter methods (filter by repos and categories). what do you think?

**Comment by aalves08** [comment]
> this test looks good to me but maybe we add some checks for the other filter methods (filter by repos and categories). what do you think?

test updated @yonasberhe23

**Review by yonasberhe23 — APPROVED** [review]
LGTM thanks @aalves08 !

**Pull request merged**
