### PR TITLE
--taints and not --taint

### PR DESCRIPTION
**Pull request by Typositoire**
This caused me a lot of trouble today... Not a big fix, but can drive someone crazy

### CODE REVIEW

**Review by avanier — APPROVED** [review]

**Review by richard-cox — COMMENTED** [review]
@Typositoire It looks like the script accepts both 

```
        "--taint" | "--taints"
```

Are there issues when using just `--taint`?

**Comment by vincent99** [comment]
Yes these should do exactly the same thing and singular matches the other options better.  If it doesn't do the same thing, that should be addressed in the script, not the Ui.

**Comment by Typositoire** [comment]
> @Typositoire It looks like the script accepts both
> 
> ```
>         "--taint" | "--taints"
> ```
> 
> Are there issues when using just `--taint`?

There might be another issue then. Documentation specify `taints` not `taint`. But when using `taint` nodes were not tainted upon registering.

**Comment by richard-cox** [comment]
@Typositoire Can you raise an issue over at https://github.com/rancher/rancher detailing the problems with `--taint`? Please reference this issue, and also feel free to tag me and I'll raise it internally.

**Pull request closed without merging**
