### PR TITLE
Container component

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
#596 

Command tab
Screen Shot 2020-05-18 at 4 25 04 PM

Resources tab
Screen Shot 2020-05-18 at 4 25 14 PM

Healthcheck tab - no probes
Screen Shot 2020-05-18 at 4 25 27 PM

Healthcheck tab - HTTPS, TCP, command probes as readiness, liveness, and startup checks respectively
Screen Shot 2020-05-18 at 4 25 40 PM

Security tab
Screen Shot 2020-05-18 at 4 25 50 PM

Multiple containers
Screen Shot 2020-05-18 at 4 26 10 PM

### CODE REVIEW

**Comment by vincent99** [comment]
- Tabs inside of tabs on top of other containers with more tabs is super-weird.  
  - I wish this would have been discussed before implementing; we specifically chose not to do this in 2.x because having multiple simultaneous UI-defined containers is not a hugely demanded task.
  - But we also have other patterns from 1.x and ideas in consideration for Fleet that could work better for this.
  - Rio Service has the same pattern and should be consistent, but hasn't been updated.
  - Sub-tabs having a different background makes all the inputs have no contrast and look disabled.
  - Sub-tab components don't know to not update the window hash, so whatever the last tab you touch is what's winning right now.

- This is missing initContainers, and design consideration for them.
  - The order of initContainers is also significant, so they need to be arrangeable.

- Add/remove
  - If you accidentally add, the remove button is a mile away in the top-right.
  - Unclear why REMOVE buttons are the only ones that are yelling (but it is consistent...)
  - The page scrolls to a random place on add, so I'm _immediately_ lost with more than 1 container. (likely because there's temporarily no tab contents and the page height becomes small, then position isn't restored when the contents comes back).

- Health checks have vertical dividers even when dividing nothing.  HTTP(S) checks are unbalanced and waste half the row for cramped headers next to empty divided white space.
- Ports are missing `name` (which are sometimes used) and hostIP (which probably shouldn't be).
  - Ports was pulled out from the tab section before because to give it more prominence when they were also defining the service; if you're going to have many of them on top of each other it would look less confusing if they were just another tab.
- The replica count(or cron schedule, etc) is floating out in space in the middle third of a second row.
- Security context has totally different headers and controls style than every other tab.
- Node scheduling
  - Has a default empty require all row
  - Uses "-" and "x" instead of "REMOVE" like everywhere else.
  - "Run all pods on specific node" doesn't work/know about any nodes.
- Environment variables from resources
  - Source options aren't limited to things that are in the selected namespace.
  - At less than ~1500px wide the remove button on env from resources is floating out of the tab.
- `(i)` info bubbles everywhere are unreadably tiny and look superscript/like copyright symbols

**Comment by deniseschannon** [comment]
We reviewed a couple of other design options to avoid tabs in tabs, but the amount of content that needs to be displayed in workloads with containers, this was the best design option. @vincent99 If you have a suggestion, please let us know what could be used as a design instead. We tried combinations of putting the container component outside the tab so it was 2 sets of tabs and a mix of accordion vs. tab, but this was the most appealing of these other options given the set of requirements. 

@mantis-toboggan-md I forgot to ping you earlier today, but I had adjusted the ports requirements in the ticket and got @lvuch to update the mocks in the containers component ticket, but didn't directly message you. I didn't realize you were about to submit something. The mocks already have updated on what a port rule should look like. 

InitContainers is on the known issue list, but wanted to first get workloads into a place where container/pod template/workload spec were not all mixed together and try to make it closer to the API itself, before digging into initContainers. 

@vincent99 I'm not sure what this was referring to. Is it the containers component or something else?
> The replica count(or cron schedule, etc) is floating out in space in the middle third of a second row.

Node Scheduling shouldn't have been touched in this issue and should be fixed as part of https://github.com/rancher/dashboard/issues/637. We are still finalizing the mocks of all the tabs, but @lvuch should be adding them into the issue as we go along. 

Issues from the mocks based on the containers issue requirements/feedback from Vince:

# Updates for @lvuch 

- [ ] Review how to handle contrast of tab within tabs 
- [ ] Review how the info bubbles look. Note: I found them really hard to hover over whenever I've tried to look at one. 
- [ ] Review how/where could we put the `REMOVE` for the container. 
- [ ] Review how to add/drop capabilities, ensure there is bottom padding from the capability:
Screen Shot 2020-05-18 at 9 39 12 PM


# Updates for @mantis-toboggan-md 

- [ ] Container name and image show "null" if you focus and blur it. Both should be marked required.


## Ports
- [ ] Move it into it's own tab
- [ ] There isn't enough spacing between the inputs
- [ ] Update based on the changes in mocks for adding `Name` and making `Host Port` less prominent

## Command tab
- [ ] The space between working dir textbox and env variables is too much. Is there a way to reduce it?
- [ ] Update for Environment variables from resources
    - [ ] Source options aren't limited to things that are in the selected namespace.
    - [ ]  At less than ~1500px wide the remove button on env from resources is floating out of the tab.

## Resources tab
- [ ] The padding under the last set of inputs seems much bigger than compared to the one from command tab. Can we have them match the amount of space between the bottom of the last field and the edge of the tab between all the tabs?

## Healthcheck Tab
- [ ] The padding under the last set of inputs seems much bigger than compared to the one from command tab. Can we have them match the amount of space between the bottom of the last field and the edge of the tab between all the tabs?
- [ ] Hide the vertical dividing bar until a type is selected
- [ ] For HTTPs types, move the request headers to the right side so that it's aligned with `Path`

## Security Context
- [ ] Update Headers to match other input types
- [ ] The padding under the last set of inputs seems different than compared to the one from command tab. Can we have them match the amount of space between the bottom of the last field and the edge of the tab between all the tabs?

**Comment by vincent99** [comment]
>@vincent99 I'm not sure what this was referring to. Is it the containers component or something else?
>> The replica count(or cron schedule, etc) is floating out in space in the middle third of a second row.

image


> We reviewed a couple of other design options to avoid tabs in tabs, but the amount of content that needs to be displayed in workloads with containers, this was the best design option. @vincent99 If you have a suggestion, please let us know what could be used as a design instead. We tried combinations of putting the container component outside the tab so it was 2 sets of tabs and a mix of accordion vs. tab, but this was the most appealing of these other options given the set of requirements.

Tabs in tabs is.. just.. bad.  And beyond that, the outer level of tab isn't even being used to switch between the containers, so there's a really a third invisible level deep of tab with an array of components which each have their sub-tabs repeated.  This is cramming far too much into one screen.

The contents of one container is so long that if you have more than one you can't see which one you're editing anymore and it's very easy to get lost and accidentally edit the wrong container (current scrolling bugs in this PR _guarantee_ this will happen to you, but even without that).

You already know this and don't like it, but I continue to think a good option is not having this in the normal flow at all and using a "Add Sidekick/Container" action and edit interstitial to allow managing multiple containers for the people that need it.  (And again if you're not going to do that, Rio needs to be updated to match as well.)

Otherwise the pattern we established is:

```
Identity: Name/Description/Type
---
Primary config: Inline fields for the most important part of the resource
---
Tabs: for the rest of the stuff you can do with the resource
```

So for a workload the definition of the containers would be the middle inline section, and then the rest of the options for the deployment below that, which removes one layer of tabbing.

Then trying to show all the containers in that section is problematic, so.. don't do that.
  - There's also 2-3 different kinds of containers to handle (regular, init and ephemeral), and you need to be able to set the order of init containers because it matters.
  - All of this should be unobtrusive to the 90%+ use-case of one deployment = one container.
  - On edit, auto-injected things like istio sidecars can probably be ignored/hidden by default since the user didn't really ask for them and probably doesn't want to touch them.

Multicluster Apps have a similar situation (multiple sets of answers for different clusters * multiple tabs of questions to answer) so we're planning to do this:

Untitled

Untitled2

This would give you one container without having to name it by default, and an option to manage multiple and see one of them at a time if you need it (like 1.x, but with a better control); you'd need Add to be a dropdown to choose what kind of container.  Segment the container list by type; Init containers always go first and can be dragged within their section and/ or `Λv` buttons to arrange.

The workload tabs are still going to be a long way down the page so they'd probably need a header or divider above them to clarify you're leaving the container management zone.

But this is all still a LOT on one page so it would probably make more sense to convert this whole thing into the wizard style of (also somewhat pictured): 

1. Name, description, pick a controller type (this could then also be a bigger control that explains what the heck the difference between the 7 choices is), type-specific options
2. Container definition (as above)
3. The rest of the option tabs for the controller (as current, minus Containers)
4. Review, optionally view and make arbitrary edits as YAML, deploy.

**Comment by mantis-toboggan-md** [comment]
pr feedback changes:
Screen Shot 2020-05-20 at 9 10 46 AM
Screen Shot 2020-05-20 at 9 10 58 AM
Screen Shot 2020-05-20 at 9 11 38 AM
Screen Shot 2020-05-20 at 9 12 20 AM
Screen Shot 2020-05-20 at 9 12 31 AM
Screen Shot 2020-05-20 at 9 18 31 AM

**Comment by deniseschannon** [comment]
#330  Ports Tab

- [ ] The ports component doesn't seem to be aligned with the `Add port` button

## Health Check Tab
- [ ] Startup Check needs tooltip text `Containers will wait until this check succeeds before attempting other health checks.`


@vincent99 Let's plan on merging in the Containers component as is and not be used yet while we work separately on how/where we're going to use this component. Regardless of how the workloads creation/flow is, we would still want this component to be available for at least the initial set of how containers should be used. 

I'd say most of your feedback regarding workloads can be tracked in the actual workloads ticket (https://github.com/rancher/dashboard/issues/637), where as we are trying to isolate the containers component for now. We're currently working on new mocks for it.

**Comment by mantis-toboggan-md** [comment]
pr feedback changes:
Screen Shot 2020-05-21 at 11 58 27 AM
Screen Shot 2020-05-21 at 11 58 15 AM

**Pull request merged**
