### PR TITLE
continued refinement, buttons and inputs

### PR DESCRIPTION
**Pull request by lvuch**
https://github.com/rancher/dashboard/issues/2278
https://github.com/rancher/dashboard/issues/2306
https://github.com/rancher/dashboard/issues/2315
https://github.com/rancher/dashboard/issues/2316
https://github.com/rancher/dashboard/issues/2323

### CODE REVIEW

**Comment by lvuch** [comment]
Screen Shot 2021-02-10 at 2 32 51 PM
Screen Shot 2021-02-10 at 2 32 46 PM

**Comment by lvuch** [comment]
line height/spacing cutting of descenders 
Screen Shot 2021-02-10 at 3 42 22 PM

**Comment by nwmac** [comment]
@lvuch There's still some issues - there's a lot in here, so its difficult to see what's going on - I think we may have go to the point where we need to take a step back.

For now, I still see issues on Chrome & Firefox on Linux - the input and multiline input are 1 pixel off from the select.

A couple of other things:

- The cluster selector dropdown wobbles when focused - it uses a 2 pixel focus border where as the namespace dropdown uses a 1 pixel focus border.
- Buttons should be the same size here:
Buttons

- The action menu button near the top right looks too big

**Comment by nwmac** [comment]
@lvuch If you add this to `vue-select.scss`, that fixes the wobble issue and border consistency in the header:

```
header {
  .unlabeled-select {
    padding: 0;

    &.focused {
      border: 0;
    }
  }
}
```

**Review by nwmac — CHANGES_REQUESTED** [review]
See my comments

**Comment by richard-cox** [comment]
Noticed the tooltip icon is misaligned for `Selects` with no label.

image

**Comment by lvuch** [comment]
> @lvuch If you add this to `vue-select.scss`, that fixes the wobble issue and border consistency in the header - it also fixes another issue where the alignment of the product in the top left is off.
> 
> ```
> header {
>   .unlabeled-select {
>     padding: 0;
> 
>     &.focused {
>       border: 0;
>     }
>   }
> }
> ```

added here `14bb6c1`

**Comment by nwmac** [comment]
@lvuch This is looking good - one thing - they vertical alignment on some buttons - e.g. create buttons - see below - is slightly off - can be fixed by changing the line-height on `.btn` to 40px instead of 38px in `_button.scss`:

ButtonAlignment

**Review by nwmac — APPROVED** [review]
LGTM

**Comment by richard-cox** [comment]
Had a final click around, noticed one minor issue and another more important one
- Main header `Import YAML` & `KubeCtl Shell` button tooltips are misaligned
- In  `design-system/form-controls` switching to `view` mode breaks the selects in a couple of places
  - Selects with no label shrink and don't show value
  - Inputs with Select are similar, no value is shown. Clicking on the empty select area results in white screen and `Cannot read property 'searchEl' of undefined` error in console

**Pull request merged**
