### PR TITLE
Preventing receiver deletion when a route depends on the receiver

### PR DESCRIPTION
**Pull request by codyrancher**
- Updated some of the styling on the PromprRemove with help of Lauren.
   - Added spacing between sections
   - Removed the warning styling
   - Added spacing between the action buttons
   - Aligned the action buttons to the right

- Fixed a problem where preventDelete was never reset so if it got set to true no other resources could be deleted.

   rancher/dashboard#1707

image

### CODE REVIEW

**Review by vincent99 — CHANGES_REQUESTED** [review]
I believe InfoBox is correct (@lvuch ?), guessing you were resolving conflict or fixing the problem where it temporarily showed nothing yesterday by going back to Card

**Comment by codyrancher** [comment]
I thought it was an unfinished change. I saw it was a WIP branch https://github.com/rancher/dashboard/commit/4f4b8ed2e6590c464409cc7df49a0a22a2fa090f.

The fix that was put in yesterday still omits the title, seems to have small spacing and looks plain.
image

I'm willing to switch it back to infobox but I think we should address those issues.

**Review by lvuch — COMMENTED** [review]
@codyrancher is correct it shouldn't be infobox and i had a WIP going but basically it should be a pretty simple box meaning no blue left border

**Comment by codyrancher** [comment]
I updated the style based on @lvuch's feedback.

**Pull request merged**
