### PR TITLE
enhancement use dynamic store

### PR DESCRIPTION
**Pull request by WuJun2016**
### Summary
When in the harvester cluster, we should request `schema` from the harvester store.

Fixes #

- https://github.com/harvester/harvester/issues/3537

### CODE REVIEW

**Comment by WuJun2016** [comment]
Hi， @mantis-toboggan-md   This is a block issue, which requires merging in v2.7.2，  PTAL, thanks

**Review by richard-cox — COMMENTED** [review]
There are a couple more places that `haveV2Monitoring` is called and don't have the custom store name passed through (`ifHave`, `monitoringStatus`). Is it not needed for them?

There is a helper that should be able to retrieve if the current context is `harvester` or `cluster`
```
const inStore = this.$store.getters['currentProduct'].inStore;
```
Would that help for these cases?

**Review by richard-cox — CHANGES_REQUESTED** [review]
See questions/comment in https://github.com/rancher/dashboard/pull/8254#pullrequestreview-1315938206

**Comment by WuJun2016** [comment]
> There are a couple more places that `haveV2Monitoring` is called and don't have the custom store name passed through (`ifHave`, `monitoringStatus`). Is it not needed for them?
> 
> There is a helper that should be able to retrieve if the current context is `harvester` or `cluster`
> 
> ```
> const inStore = this.$store.getters['currentProduct'].inStore;
> ```
> 
> Would that help for these cases?

@richard-cox  `this.$store.getters['currentProduct'].instore` cannot be called in `haveV2Monitoring`, which would result in nested calls, resulting in an endless loop。  So I use a new function to get the `storeName` of the current `activeProduct`.

Can you help to see if this will cause any other problems ？  thanks

**Review by richard-cox — APPROVED** [review]
Ok, I understand now, the reliance of `haveV2Monitoring `--> `currentProduct` / `currentStore` --> `activeProduct` --> `ifHave` --> `haveV2Monitoring`.

I had a quick look to see how easy it was to add all the plumbing in for `inStore` as a param and there would be a lot for `allDashboardsExist`.

This solution is more generic and will have less impact

**Pull request merged**
