### PR TITLE
Change the way we get up to date catalog information to be more performant

### PR DESCRIPTION
**Pull request by codyrancher**
### Summary
fixes: #10448

### Occurred changes and/or fixed issues
No longer force reload catalog in most areas. Now force reload verisonInfo in all areas.

### Technical notes summary
Digging a little deeper it became evident that the original problem was actually that we had stale versionInfo instead of catalog info. It just so happens that doing a force load of the catalog would also update the versionInfo.

This fix removes the versionInfo caching and forces a reload at that location. There was one critical path which occurs in rke2.vue but that component is already caching the versionInfo on it's own. This means that rke2 could have stale data but I'm not sure it's worth updating and if it is I think we should do it in a separate change.

image

### Areas or cases that should be tested
Chart installation if there's a change to the chart version. We should follow the testing instructions here https://github.com/rancher/dashboard/pull/7672

Testing if adding/removing a chart from an existing repository and the refreshing the repo will cause any issues to arise.

### Areas which could experience regressions
Same as above

### Screenshot/Video
N/A

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Comment by codyrancher** [comment]
> The change results in a blocking http request to fetch a specific chart version whenever it's requested. In some cases this will be two sequential blocking requests - e.g. fetching a chart and it's matching crd one. This is a massive improvement on before, but I think the change can be more targeted to the issue, instead of being universal.
> 
> Think the solution is in that version cache, but maybe a better approach would be to just empty it whenever the user manually refreshes via `shell/models/catalog.cattle.io.clusterrepo.js` `refresh`?

I don't think this suggestion is sufficient. It can result in the exact same stale issue that I mention could be present in rke2. If two users or two tabs are open at the same time only one tab will get the refresh unless we force a refresh when the data is needed.

You're right that it will result in two blocking requests, but not in any of the critical paths. I don't think we care if it's slower when installing or viewing extensions. This change will make sure that navigating around rancher will be faster (I believe this was the original motivation for this issue) and that when the data is needed it will be correct. 

This quote feels awfully relevant 
> _There are only two hard things in Computer Science: cache invalidation and naming things._

**Comment by richard-cox** [comment]
The [original issue](https://github.com/rancher/dashboard/issues/7668) revolved around the user manually refreshing repos and not receiving updates to existing chart versions. That's a super weird use case, as a specific version of a chart should be immutable (I'm guessing they were developing a chart, specifically questions.yaml).

In the normal world charts would not change. New chart versions may be introduced by they would come in via a manual repo refresh. 

So i'm not convinced we need to put in blocking requests to all of below in production for an edge case used by developers where a browser refresh or updating the current repo refresh would solve the issue
- create/edit rke initial load
- viewing a chart detail page
- chart install page x 2
- extension install modal
- extension detail slide in 

Given the original issue, just clearing the cache manually on repo refresh should do it

**Comment by richard-cox** [comment]
I've got a [PR](https://github.com/rancher/dashboard/pull/10853) up with the required changes. It's not quite ready yet, i'd like to write some e2e tests after https://github.com/rancher/dashboard/pull/10773 merges

**Comment by codyrancher** [comment]
Closing in favor of https://github.com/rancher/dashboard/pull/10853

**Comment by richard-cox** [comment]
Errant project bot re-opened, closing

**Pull request closed without merging**
