### PR TITLE
Support "target=_blank" in A links via clean-html directive

### LINKED ISSUE #9920: target="_blank" doesn't work in the UI with v-clean-html
**Setup**
- Rancher version: Any
- Rancher UI Extensions: 2.8-head (master)
- Browser type & version: Any

**Describe the bug**

A link using `v-clean-html` and with a `target="_blank"` doesn't open in a new tab because of the `v-clean-html` directive that removes the `target` attribute.

**To Reproduce**

Add a HTML element to a Vue view like (just as an example... find another translation string with an anchor `<a>` inside:
```
<p
    v-if="role.id === 'restricted-admin'"
    v-clean-html="t('rbac.globalRoles.role.restricted-admin.deprecation', { releaseNotesUrl }, true)"
    class="deprecation-notice"
  />
```
click on it via the UI

**Result**
Doesn't open the link in a new tab

**Expected Result**

Should open the link in a new tab

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by nwmac**
Fixes #9920

To test:

Go to User Mgmt and the Restricted Admin role page.

Click on 'Release Notes' in the top banner and verify that this now opens in a new tab.

### CODE REVIEW

**Review by aalves08 — APPROVED** [review]
LGTM! Tested and it works. I thought you weren't into the hooks thing but it was more about the sanitisation logic.

**Review by richard-cox — CHANGES_REQUESTED** [review]
This works fine on the role detail page.

This didn't work for me on the role list page. Looks like something is removing the `target` attribute... but adding console output to hooks (and directive inserted, etc functions) in `clean-helm-directive` provides no output ... as if the directive code was not running. 

Also checked the create user page and that also removes the target attribute.

I figure something's off locally but can't work out what

Edit: Apart from above, code looks good

**Review by aalves08 — APPROVED** [review]
I tested these latest changes with Elemental installed and we don't have Elemental overriding this, so I would say LGTM. This will be needed for links to open in a new tab on markdown files https://github.com/rancher/dashboard/pull/9956

**Comment by nwmac** [comment]
@richard-cox I can't reproduce the issues you see

**Review by richard-cox — APPROVED** [review]
Could not reproduce the issue i saw in https://github.com/rancher/dashboard/pull/9928#pullrequestreview-1680586192

**Pull request merged**
