### PR TITLE
cleaning up authenticated middleware

### LINKED ISSUE #8627: Removal of authentication middleware from Rancher Dashboard
Removal of `authentication` middleware from Rancher Dashboard is, hopefully, an important part of the simplification of the initialisation procedure for Rancher Dashboard. Should be a good issue to tackle before the reorder of the loading steps for extensions and most of the code that runs on the `authentication` middleware, imo, should run on the `beforeEach` route guard.

A tech debt issue should be created to tackle the optimisation of the load procedure that happens on this new logic (some of the stuff might be initialised on a higher level and only run once).

The ideia was to cupcake this so that we don't introduce too many changes at once in the codebase for such a delicate area.

### PR DESCRIPTION
**Pull request by aalves08**
Fixes #8627 
- Removal of `authenticated` middleware and moving the code to route navigation guard `beforeEach`

### Test cases covered
- [x] Moving in and out of routes inside the app (mouse click, even from extensions to internal products and vice versa)
- [x] Refresh page on different routes
- [x] Log out user then try to navigate to home page (redirect to login)
- [x] Creating a new Rancher instance and checking first login page and setting up password
- [x] Entering gibberish as URL param (Ex: `<!--- BASE-URL---->/asdasdsasadasd`)
- [x] Hitting refresh control when Extension has been installed
- [x] Navigating to and from the old Ember interface
- [x] Setup and login via LDAP
- [x] Setup and login via Github (didn't work via localhost, but I am unsure it's supposed to)
- [ ] Opening a Harvester Cluster older than 1.1.0 (plugin included in Dashboard)
- [ ] Opening a Harvester Cluster later/younger than 1.1.0 (externally loaded)

> Note: There are quite a few logs that need to be deleted from the code. For testing purposes, I'll leave them for now and remove it from the PR if it get an approval

PS: If there are more scenarios to be tested, let me know

### CODE REVIEW

**Comment by richard-cox** [comment]
There were a lot of issues related to timing of actions when dynamically loading harvester plugins. Need to test
1. Loading inline & standalone Harvester UI
2. Dashboard loads embedded Harvester plugin
3. Dashboard loads Harvester plugin served by Harvester cluster

There's some comments within `authentication` as well about timings, need to understand those and test around them.

Flicking between routes with a cluster context (explorer) and those that kind of need one but not one specifically (cluster manager) would be good. When returning to the original explorer there should be no new requests made (as the previous cluster wasn't cleared)

Also need to test the setup process, both from fresh and if the browser loads after the first step.

General question, haven't gone through the code yet, but how do we associate layouts with the need to authenticated? Do we now associated routes to guards?

**Comment by aalves08** [comment]
> There were a lot of issues related to timing of actions when dynamically loading harvester plugins. Need to test
> 
> 1. Loading inline & standalone Harvester UI
> 2. Dashboard loads embedded Harvester plugin
> 3. Dashboard loads Harvester plugin served by Harvester cluster
> 

Good test cases around Harvester. Thanks for the info @richard-cox 

> There's some comments within `authentication` as well about timings, need to understand those and test around them.
> 
> Flicking between routes with a cluster context (explorer) and those that kind of need one but not one specifically (cluster manager) would be good. When returning to the original explorer there should be no new requests made (as the previous cluster wasn't cleared)

I believe that flicking between routes with a cluster context scenario is already covered by my test cases, but an extra set of 👀  would be appreciated

> Also need to test the setup process, both from fresh and if the browser loads after the first step.

Do you mean after provisioning a new Rancher instance and first time setup? If so, I've tested it and it's working

> General question, haven't gone through the code yet, but how do we associate layouts with the need to authenticated? Do we now associated routes to guards?

The authentication logic is now assigned to a general route guard `beforeEach`, which will run for all routes. This should handle the redirect to unauthenticated routes when needed.

With this work we don't associate layouts with the need to be authenticated explicitly like we had before with the middleware  definition on each layout. The route guard should handle that for us and also handle redirect logic before we load certain parts.

PS: Adding @mantis-toboggan-md to this PR because I will need some help with the Harvester test cases

**Comment by richard-cox** [comment]
> > Flicking between routes with a cluster context (explorer) and those that kind of need one but not one specifically (cluster manager) would be good. When returning to the original explorer there should be no new requests made (as the previous cluster wasn't cleared)
> 
> I believe that flicking between routes with a cluster context scenario is already covered by my test cases, but an extra set of eyes would be appreciated

This is a specific use case to catch how the blank cluster is handled

> > General question, haven't gone through the code yet, but how do we associate layouts with the need to authenticated? Do we now associated routes to guards?
> 
> The authentication logic is now assigned to a general route guard `beforeEach`, which will run for all routes. This should handle the redirect to unauthenticated routes when needed.
> 
> With this work we don't associate layouts with the need to be authenticated explicitly like we had before with the middleware definition on each layout. The route guard should handle that for us and also handle redirect logic before we load certain parts.

Do we have test cases for the layouts that don't currently use the authenticated middleware (unauthenticated and error)?

**Comment by aalves08** [comment]
> > > Flicking between routes with a cluster context (explorer) and those that kind of need one but not one specifically (cluster manager) would be good. When returning to the original explorer there should be no new requests made (as the previous cluster wasn't cleared)
> > 
> > 
> > I believe that flicking between routes with a cluster context scenario is already covered by my test cases, but an extra set of eyes would be appreciated
> 
> This is a specific use case to catch how the blank cluster is handled

From my tests, these look good, but again an extra set of 👀 would be nice

> 
> > > General question, haven't gone through the code yet, but how do we associate layouts with the need to authenticated? Do we now associated routes to guards?
> > 
> > 
> > The authentication logic is now assigned to a general route guard `beforeEach`, which will run for all routes. This should handle the redirect to unauthenticated routes when needed.
> > With this work we don't associate layouts with the need to be authenticated explicitly like we had before with the middleware definition on each layout. The route guard should handle that for us and also handle redirect logic before we load certain parts.
> 
Do we have test cases for the layouts that don't currently use the authenticated middleware (unauthenticated and error)?

the pages that use the `unauthenticated` layout are: `login`, `logout`, `setup` and `verify`. I am sure I haven't covered the `verify` one, although I have covered login in via `LDAP` and `Github`.

As for the `error` layout, that has been covered (show error page).

**Review by codyrancher — COMMENTED** [review]
As is, I think I'd be comfortable with this going in as long as harvester and performance changes were verified to still work.

**Comment by aalves08** [comment]
Closed as it's draft. Record will be kept and used as the basis for a new PR to remove the auth middleware.

**Pull request closed without merging**
