### PR TITLE
Add missing parameters to SAML auth request

### PR DESCRIPTION
**Pull request by torchiaf**
### Summary
Fixes https://github.com/rancher/dashboard/issues/9608

### Areas or cases that should be tested

- Login using the token command from rancher CLI

### How to test

Internal reference: confluence - Okta SAML setup Creation

0. Enable the SAML authentication on your rancher instance

    - Internal reference: confluence - Okta SAML setup Creation
    - docs: https://developer.okta.com/docs/guides/build-sso-integration/saml2/create-your-app/
    - video: https://www.youtube.com/watch?v=Kqn3YHyIBdk
    - Rancher reference: https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/okta/

1. Install the [rancher cli](https://ranchermanager.docs.rancher.com/reference-guides/cli-with-rancher/rancher-cli#docusaurus_skipToContent_fallback).
2. Using the Rancher cli, attempt to generate a token using rancher token --server=$RANCHER_HOST --cluster=$CLUSTER --user=$USER (replace $RANCHER_HOST with your rancher hostname, and $CLUSTER with the cluster that you want to generate a token for).
3. If SAML login is enabled in your cluster, the cli will present the SAML authentication option, select this option.
4. Attempt to go to the generated URL in your browser. the cli command  blocks until the user login to Rancher

    -   The link to the Vue UI will be correctly generated once https://github.com/rancher/rancher/issues/41651 will be resolved.
    To properly test the login in the new UI, the link generated by the CLI needs to be manually changed:
    `/login` --> `/dashboard/auth/login `

5. Once you are logged in Rancher the command should return without no errors.

### Technical notes summary

How to test local UI instance:

- Run the UI locally, https://localhost:8005
- Links for Saml configurations on Okta.dev and Rancher should point to localhost
image (10)
image (11)

### CODE REVIEW

**Comment by mantis-toboggan-md** [comment]
Do you have a way of testing this with the Rancher CLI changes too? I think it'll require a custom build of the cli

**Comment by torchiaf** [comment]
> Do you have a way of testing this with the Rancher CLI changes too? I think it'll require a custom build of the cli

I tested it with Rancher CLI, version `v2.7.0`, by manually changing the login link to `/dashboard/auth/login/`. I'll update the description with the replication steps ASAP.

**Review by mantis-toboggan-md — APPROVED** [review]
lgtm

**Comment by eliyamlevy** [comment]
Has a new dashboard rc been cut to test this with the latest v2.8-head?

**Comment by mantis-toboggan-md** [comment]
@eliyamlevy this is available in v2.8.0-alpha2

**Comment by eliyamlevy** [comment]
Successfully validated the fix from the cli end. See more details [here](https://github.com/rancher/rancher/issues/41651#issuecomment-1743525596)

**Pull request merged**
