### PR TITLE
Fix `Conditions` tab, and Fleet Cluster `Resources` column

### LINKED ISSUE #11154: Fleet: Clusters: Resources column does not show summary graph
**Setup**
- Rancher version: v2.8, v2.9
- Rancher UI Extensions:
- Browser type & version: Any

**Describe the bug**
Resources column does not show summary graph on fleet clusters page.

**To Reproduce**

1. provision a cluster and wait for it to be active
2. go to fleet > git repos tab
3. click 'Add Repositories'
4. input repo URL ('https://github.com/rancher/fleet-examples.git')
5. click 'Add Path'
6. input path ('simple')
7. click Next
8.  target: newly created cluster or all clusters
9. click 'Create'
10. wait until it is in Active state
11. navigate to fleet clusters list page
12. notice Resources column is blank `-` 

**Result**
Resources column does not show summary graph.
**Expected Result**
Resources column does not show summary graph.

**Screenshots**
Screenshot 2024-05-30 at 10 14 47 AM

**Additional context**

NOTE: I'm currently working on e2e tests to cover this specific scenario.

### LINKED ISSUE #11155: Fleet: Git Repos: Conditions tab missing from details view
**Setup**
- Rancher version: v2.9
- Rancher UI Extensions:
- Browser type & version: Any

**Describe the bug**
The Conditions tab is missing from Fleet cluster details view.

**To Reproduce**
2. go to fleet > git repos tab
3. click 'Add Repositories'
4. input repo URL ('https://github.com/rancher/fleet-examples.git')
5. click 'Add Path'
6. input path ('simple')
9. click 'Create'
10. wait until it is in Active state
12. navigate to git repo details page
13. notice Condition tab is missing

**Result**
The Conditions tab is missing from Fleet git repos details view.

**Expected Result**
The Conditions tab is displayed on Fleet git repos details view.

**Screenshots**
Screenshot 2024-05-30 at 9 58 47 AM

**Additional context**
Note: 
- this also affects the fleet cluster details view
- scenarios are covered by the below e2e tests (will enable them once this fix is merged ):
  - cypress/e2e/tests/pages/fleet/gitrepo.spec.ts > 'check all tabs are available in the details view'.
  - cypress/e2e/tests/pages/fleet/fleet-clusters.spec.ts > 'check all tabs are available in the details view'.
-

### PR DESCRIPTION
**Pull request by richard-cox**
### Summary
Fixes #11154
Fixes #11155

### Occurred changes and/or fixed issues
1. Unreleased Regression - Ensure the Resource Tabs Conditions tab correctly shows
   - The `Conditions` tab shows when the resource's schema says the resource contains conditions
   - Following the schema diet change this info isn't in the base schema, so we need to fetch the resources schema definition
   - If not found we currently only print a warning to indicate the owning component needs to call `fetchResourceFields`. This was done to avoid making the request for every resource detail page. This resulted though in a number missed places (nodes, some fleet resources, etc)
   - To avoid this we'll now make the request to fetch schema definitions on every resource tabs usages (with some caveats)
2. Legacy broken feature - Fleet Cluster List `Resources` column failed to show the summary graph

### Areas or cases that should be tested
- Detail page for cluster, node, deployments and fleet fgit repo resources all show the Conditions
- Fleet Cluster List `Resources` column should show summary graph

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
  - @yonasberhe23 Will be covering automated tests separately 
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Review by aalves08 — COMMENTED** [review]
Using the example on the issues (https://github.com/rancher/fleet-examples.git branch `master` path `simple`) I ran into the following issue:


Screenshot 2024-06-03 at 15 04 43
Screenshot 2024-06-03 at 15 04 48

Changing `fleet.cattle.io.bundle` model from:

´´´
get repoName() {
    return this.metadata.labels['fleet.cattle.io/repo-name'];
  }
´´´
to:

´´´
get repoName() {
    return this.metadata?.labels?.['fleet.cattle.io/repo-name'];
  }
´´´

seems to have done the trick for me. After this small change, I could check that your changes are good and also codewise it lgtm

**Comment by richard-cox** [comment]
@aalves08 I couldn't reproduce the issue. Adding the repo and going straight to the git repo (or waiting) always resulted in the detail page rendering correctly. Would you be able to provide more info?

**Comment by aalves08** [comment]
> @aalves08 I couldn't reproduce the issue. Adding the repo and going straight to the git repo (or waiting) always resulted in the detail page rendering correctly. Would you be able to provide more info?

Not really... The thing is that after I removed the git repo, then added it again, it worked fine... I don't know if it was in a weird state or something. Nevertheles, imho, I don't think it would be a bad practice to add optional chaining. At least we would be on the safe side.

But the fact is: after I removed it and added it again, it worked fine.

**Comment by richard-cox** [comment]
@aalves08 Strange.

Kind of inclined to keep as is. I went through the code and the changes seem disconnected from where the error occurred, and the line that failed suggests something else is wrong (all bundles should have `metadata` and hiding it will masks another bug).

**Review by aalves08 — APPROVED** [review]
lgtm

**Pull request merged**
