### PR TITLE
Implementing logging overview

### PR DESCRIPTION
**Pull request by codyrancher**
- Made a generic CountGauge
- Made ResourceGauge a specialization of CountGauge
- Swapped the cluster overview page to using the counts instead of requesting the resources

rancher/dashboard#1089

Screen Shot 2020-09-03 at 5 23 08 PM

### CODE REVIEW

**Comment by paynejacob** [comment]
This looks good but we will need a cluster output column on the bottom table when we upgrade the chart version.

https://github.com/rancher/charts/pull/608
https://github.com/banzaicloud/logging-operator/releases/tag/3.6.0

**Comment by lvuch** [comment]
Screen Shot 2020-09-08 at 10 33 33 AM

**Comment by lvuch** [comment]
Screen Shot 2020-09-08 at 10 58 20 AM

**Comment by codyrancher** [comment]
I updated to reflect the new design. I did leave in the resource gauge changes since I think it could be useful in the future.

**Pull request merged**
