### PR TITLE
fix(LabelSelect):fix repeated triggering of input events

### PR DESCRIPTION
**Pull request by ly5156**
### Summary
Fixes #

https://github.com/rancher/dashboard/issues/5979
https://github.com/rancher/dashboard/issues/5984

Reference vue2 api: https://v2.vuejs.org/v2/api/#vm-listeners

### CODE REVIEW

**Comment by richard-cox** [comment]
Removing this line will most probably break other functionality. @catherineluse You tweaked this recently, I don't think it caused the two referenced issues but could you review this PR?

**Comment by catherineluse** [comment]
I introduced this bug in this PR https://github.com/rancher/dashboard/pull/5850 in which I made the LabeledInput component emit an event that was used by the new SimpleSecretSelector component. The event could have been named anything. I could have called it 'eventSpecificallyForSelectingReceiverSecret', but instead I went with the name 'input' on the reasoning that the component was supposed to be generic.

But it turns out the former name would have been better, because emitting the 'input' event more times has created this bug. Apparently another component was listening for the input event and it didn't expect the same argument that I was passing it.

So I created this PR https://github.com/rancher/dashboard/pull/5999 the event to "selecting", which still sounds generic but is not used anywhere else in the dashboard. Renaming it (instead of removing it) is needed to fix the bug while retaining functionality for the secret selector.

I tested this PR by following the steps to reproduce https://github.com/rancher/dashboard/issues/5984 and it worked.

However, I could not validate if my PR fixes https://github.com/rancher/dashboard/issues/5979 because that issue doesn't have steps to reproduce it. @ly5156 do you have steps to reproduce it?

**Comment by ly5156** [comment]
@catherineluse 
Steps to reproduce the issue：https://github.com/rancher/dashboard/issues/5979
1. go to the preferences page, change date-formate
2. then go to the pod page, view a pod logs, An incorrect date format will be displayed
3. then go back the the preferences page, the incorrect date format will be displayed
WeChatfecb9276c284e03b89a5f2056a735541
WeChat5addbe1f557a0111b5fa330a56bc47cc
WeChatf17602b1fa2dea41cdea53a0b136ce0c

**Comment by catherineluse** [comment]
@ly5156 Thank you. I reproduced that bug in master and confirmed in my local setup that my PR fixes that one too. 

@richard-cox can you please review https://github.com/rancher/dashboard/pull/5999?

**Comment by richard-cox** [comment]
Resolved via #5999

**Pull request closed without merging**
