### PR TITLE
HARVESTER: Modify the design of some harvester pages

### PR DESCRIPTION
**Pull request by WuJun2016**
### Summary

Modify the design of some harvester pages，  and bug fix

Fixes #

### CODE REVIEW

**Comment by WuJun2016** [comment]
Hi, @richard-cox  @mantis-toboggan-md   I added a few commits to fix some bugs.   PTAL,  thanks.

**Comment by richard-cox** [comment]
@oxr463 This is a PR that's showing the same issue as the one that was blocking the 2.6.8-patch1. It's for 2.6.9 and we'd like to merge it soon, however we can hold off for 24 hours if you'd like to investigate?

**Comment by richard-cox** [comment]
@WuJun2016 Just to clarify, these are Harvester 1.1.0 changes right, we should assume anything 1.0.3 related will be a separate PR in the `release-harvester-plugin-v1.0.3` branch right?

**Comment by WuJun2016** [comment]
> these are Harvester 1.1.0 changes right
This is a change from v1.1.0, it's just a UI enhancement or UI bug fix, no backend changes involved.    So these changes will also be committed to the master branch, I just cherry-pick them from the master branch to the release-harvester-plugin-v1.0.3 branch.

>  we should assume anything 1.0.3 related will be a separate PR in the release-harvester-plugin-v1.0.3 branch right ?
Yes，  This means that the pr you submit to rancher/master may need to submit a separate pr here if it involves a fix to a plugin feature.

**Comment by richard-cox** [comment]
Sorry, my bad, hadn't checked the target branch.

**Comment by WuJun2016** [comment]
> Sorry, my bad, hadn't checked the target branch.

haha, I don't have permission to add a label to indicate the target branch, but in the future, I'll leave a comment in there identifying which branch issue this pr is fixing.

**Review by mantis-toboggan-md — APPROVED** [review]
LGTM - once we get the CI check sorted this can be merged

**Pull request merged**
