### PR TITLE
Replace `nuxt-link` with `router-link`

### PR DESCRIPTION
**Pull request by rak-phillip**
### Summary
This removes the `NuxtLink` & `NLink` components from Dashboard. If an extension or outside component attempts to use `NuxtLink` or `NLink`, a deprecation warning should print to the console and `router-link` will be used instead.

### Technical notes summary

I'm attempting to make this change in a way that will be more backwards compatible with extensions that might relay on `NuxtLink` or `NLink`. This is done by replacing the `NuxtLink` component with an alias that will print a deprecation warning in the console.

### Areas or cases that should be tested

This affects all routing throughout dashboard. 

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Comment by rak-phillip** [comment]
@torchiaf I'm requesting a review from you so that you can test with Harvester. I want to avoid another situation where we might need to revert a portion of this PR like we did in #10676

**Review by codyrancher — APPROVED** [review]
As long as tests pass this LGTM.

**Review by codyrancher — APPROVED** [review]

**Review by cnotv — APPROVED** [review]
I think you covered everything, but please wait for @torchiaf about Harvester, otherwise this will get reverted anyway.

LGTM

**Review by torchiaf — APPROVED** [review]
Harvester router seems to be working correctly.
If possible, I would remove the warning message when loading Harvester.
LGTM

**Comment by rak-phillip** [comment]
> If possible, I would remove the warning message when loading Harvester.

@torchiaf can you expand on why we would want to make an exception for Harvester? If we are flagging features as deprecated in v2.9 of Dashboard, would we not want to warn all extension authors that this will break in later versions after said features are removed?

**Comment by torchiaf** [comment]
> > If possible, I would remove the warning message when loading Harvester.
> 
> @torchiaf can you expand on why we would want to make an exception for Harvester? If we are flagging features as deprecated in v2.9 of Dashboard, would we not want to warn all extension authors that this will break in later versions after said features are removed?

 In general, I think you are right, but in the Harvester's case, those warnings would be visible only when using Rancher + Harvester older versions embedded.
 We will have to port this code in the next Harvester version, including the warning logic - in theory the Harvester plugin would take care of showing the warnings then (even in standalone mode).

Anyway, this is really a non-issue I think, sorry, I was a little pedantic here :smiley:

**Pull request merged**
