### PR TITLE
Bump `@aws-sdk/client-ec2` & `@aws-sdk/client-iam` to 3.658.1

### LINKED ISSUE #12088: fast-xml-parser: >=4.2.4

### PR DESCRIPTION
**Pull request by rak-phillip**
### Summary
This gets the transitive `fast-xml-parser` to >=4.2.4 by bumping `@aws-sdk/client-ec2` & `@aws-sdk/client-iam` to 3.658.1.

Fixes #12088 

### Occurred changes and/or fixed issues

- Bump `@aws-sdk/client-ec2` to 3.658.1
- Bump `@aws-sdk/client-iam` to 3.658.1 

### Technical notes summary

`fast-xml-parser` is a transitive dependency in Dashboard. Bumping `@aws-sdk/client-ec2` & `@aws-sdk/client-iam` to the latest versions gets us to a version of `fast-xml-parser` that's acceptable for the project.

```
➤ yarn why fast-xml-parser

yarn why v1.22.19
[1/4] Why do we have the module "fast-xml-parser"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "fast-xml-parser@4.4.1"
info Reasons this module exists
   - "shell#@aws-sdk#client-ec2#@aws-sdk#core" depends on it
   - Hoisted from "shell#@aws-sdk#client-ec2#@aws-sdk#core#fast-xml-parser"
info Disk size without dependencies: "292KB"
info Disk size with unique dependencies: "328KB"
info Disk size with transitive dependencies: "328KB"
info Number of shared dependencies: 1
Done in 0.59s.
```

We can also consider bumping `@aws-sdk/client-eks` and `@aws-sdk/client-kms`, but I opted to keep this PR focused on the dependencies that would target `fast-xml-parser`.

### Areas or cases that should be tested

- Cluster provisioning on AWS

### Areas which could experience regressions

- Cluster provisioning on AWS

### Checklist
- [ ] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [ ] The PR has a Milestone 
- [ ] The PR template has been filled out
- [ ] The PR has been self reviewed 
- [ ] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [ ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Review by mantis-toboggan-md — CHANGES_REQUESTED** [review]
I was not able to run the dashboard locally with these changes. I ran:
`rm -rf node_modules && yarn cache clean && yarn && yarn mem-dev`
And I hit the same error that's showing up here: https://github.com/rancher/dashboard/actions/runs/11132837952/job/30937596503?pr=12089#step:4:97


I think it may be much the same as this person's issue: https://stackoverflow.com/questions/76784232/yarn-issues-with-html-webpack-plugin-and-cypress-webpack-dev-server

**Comment by rak-phillip** [comment]
@mantis-toboggan-md thanks for the heads up - I also ran into that issue when I added a `vueuse` dependency while drafting my original solution for #12076. I'll take a closer look to see how we can resolve.

**Comment by richard-cox** [comment]
@rak-phillip @mantis-toboggan-md  This PR and issue are tagged as 2.10.1?

**Comment by rak-phillip** [comment]
@richard-cox it looks like a clerical error during issue creation. If we look at the history, we can see that 2.10.0 was the intended milestone before it got modified by the bot:

image

The epic that this issue was spawned from also has a 2.10.0 milestone - #9648.

The milestones have been corrected.

**Pull request merged**
