### PR TITLE
fix support links tests

### PR DESCRIPTION
**Pull request by yonasberhe23**
### Summary
Handles https://github.com/rancher/dashboard/issues/9417

- 'Docs' link test: 
  - I've added `.skip` on the test which simply skips the test until we have a fix for the root of the issue. The actual fix will need to come from resolving the uncaught exception (err message: MktoForms2 is not defined) which I've reported [here](https://github.com/rancher/rancher-docs/issues/727). 
  - I've tried adding exception handling as a temporary workaround but no dice.
  
- 'Forums', 'Slack', and 'File an Issue' link tests: 
  - re-enabled tests
  - added `chromeWebSecurity: false` to cypress.config file which disables web security. This allows us to access cross-origin iframes that are embedded in our application and navigate to any superdomain without cross-origin errors.
  - see https://docs.cypress.io/guides/guides/web-security#Set-chromeWebSecurity-to-false

### CODE REVIEW

**Review by richard-cox — CHANGES_REQUESTED** [review]
This will reload the dashboard 5 times instead of 1. There's a problem where that load can take a long time in CI so we're trying to keep them to a minimum. Can they be in one test again, or the tests in this re-arranged such that each `it` does not execute a beforeEach with the load in?

**Comment by yonasberhe23** [comment]
> This will reload the dashboard 5 times instead of 1. There's a problem where that load can take a long time in CI so we're trying to keep them to a minimum. Can they be in one test again, or the tests in this re-arranged such that each `it` does not execute a beforeEach with the load in?

It is possible to have it so that the dashboard is not reloaded 5 times and still have the tests split up by setting the "testIsolation" config to false on the test suite level (the config just preserves the brower state instead of clearing it before each test). 

Here are the pros & cons of using this config:

Pros:
- each of the support link test will be independent. It would be easier to make it one test again, however if there is an issue with the first link, then the test will fail and the remaining links will not be tested.
- it would be beneficial to have "testIsolation" config at our disposal (Cypress v10.11.0 does not support it on the suite level)

Cons:
- "testIsolation" config is only available on Cypress v11.1.0 due to this [issue](https://github.com/cypress-io/cypress/issues/23911), so we would need to update our version.

If we were to update Cypress, home.spec would look like this:
```
describe('Home Page tests', () => {
	beforeEach(() => {
              cy.login();
              HomePagePo.goToAndWaitForGet();
        });
        it('Test 1', () => {
    	   // test code
	})
 
	it('Test 2', () => {
    	   // test code
	})
})

describe('Support Links', { testIsolation: false }, () => {
        before(() => {
              cy.login();
       });
        beforeEach(() => {
              HomePagePo.goToAndWaitForGet();
       });
	it('Test 1', () => {
    	   // test code
	})
 
	it('Test 2, which now inherits state from Test 1', () => {
    	   // test code
	})
})
```

**Comment by richard-cox** [comment]
I was thinking in a more isolated way, for example..
```
describe(x)
  describe(y) 
    beforeEach (with page load)
  describe(z)
    beforeAll(with page load)
```
But your comment on testIsolation rang a bell. I think I looked at this at one point to just use a navTo style function (no page load) instead of goTo (page load). 

We have experimentalSessionAndOrigin enabled which means we need testIsolation set to legacy (https://github.com/cypress-io/cypress/pull/23040). That change was released in 10.5.0 (https://docs.cypress.io/guides/references/changelog#10-5-0). Looks like there was a fix to `suite` stuff in 10.8.0. 

We're currently on 10.11.0.

However there's TS fixes in 11.1.0 (that's the one i think you've discovered) and weirdly an announcement in 12.0.0 about a new testIsolation setting. From the release notes it looks like they've got rid of experimentalSessionAndOrigin and changed how testIsolation works / it's values.

Options... we can either
- just have them in a single test for efficiency purposes
- bump cypress to 11.x and use the older version of testIsolation (if this can be done at the `describe` level)
- bump cypress to 12.x and use new version of testIsolation

**Comment by yonasberhe23** [comment]
> * bump cypress to 11.x and use the older version of testIsolation (if this can be done at the `describe` level)

I went with the second option.
However the cypress upgrade to v11.1.0 caused e2e-tests job to error out. Eventually i figured out that `cy2` bump was required. e2e-test job is running as expected after the bump and all checks.

**Review by richard-cox — APPROVED** [review]

**Pull request merged**
