### PR TITLE
fix(steve/actions): fix missing type attribute of secret resource

### LINKED ISSUE #9280: Downloading or editing secret resource as yaml, the data is missing the type attribute
**Setup**
- Rancher version: v2.7.5...v2.8.0
- Browser type & version:  Chrome 114.0.5735.198 arm64

**Describe the bug**

Downloading or editing secret resource as yaml, the data is missing the type attribute

**To Reproduce**

1. Create a secret of type Opaque or other type
2. `Download Yaml` or `Edit Yaml`

image
image

**Result**

1. You will see that the type attribute is missing from the yaml data
2. If I want to execute the apply command using the secret yaml on the UI, it will fail if the type is not Opaque

**Expected Result**

The yaml data should contain the type attribute
Refer to the documentation:
https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/

https://kubernetes.io/docs/concepts/configuration/secret/#secret-types

### PR DESCRIPTION
**Pull request by ly5156**
### Summary
Fixes #9280

### CODE REVIEW

**Comment by nwmac** [comment]
@ly5156 Could you add unit and/or e2e tests for this, please.

**Comment by richard-cox** [comment]
@ly5156 There will be some changes requested, there should be / we should make a way to do this without referencing specific resources in the action

**Comment by ly5156** [comment]
@richard-cox 
Add a map to the `cleanForDownload` method that maps kind to the root keys to be removed(as shown in the code below)，otherwise we might need to modify the file in the screenshot.

image

### `cleanForDownload` action

```javascript
// secret resource contains the type attribute
// ref: https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/
// ref: https://kubernetes.io/docs/concepts/configuration/secret/#secret-types
const removedRootKeysMap = {
Secret: [
'id',
      'links',
      'type',
      'actions'
]
}
// remove fields added by steve before showing/downloading yamls
  cleanForDownload(ctx, yaml) {
    if (!yaml) {
      return;
    }
    let rootKeys = [
      'id',
      'links',
      'type',
      'actions'
    ];
    const metadataKeys = [
      'fields',
      'relationships',
      'state',
    ];
    const conditionKeys = [
      'error',
      'transitioning',
    ];
    const obj = jsyaml.load(yaml);

   rootKeys = removedRootKeysMap[obj.kind] ?? rootKeys;

    dropKeys(obj, rootKeys);
    dropKeys(obj?.metadata, metadataKeys);
    (obj?.status?.conditions || []).forEach((condition) => dropKeys(condition, conditionKeys));

    return jsyaml.dump(obj);
  }
};
```

**Review by richard-cox — CHANGES_REQUESTED** [review]
I've pushed some changes which should follow the existing pattern of customisation via the resource models. Would you be able to give that a review and test your side, and update tests as required?

Once done and you're happy, i'll give the review a green tick and we can get this merged

**Comment by ly5156** [comment]
@richard-cox 
Thanks a lot for reviewing and modifying the code.
I've updated the unit test code and it runs as expected!

**Review by richard-cox — APPROVED** [review]
@aalves08 mentioned there's an issue with our storybook gate that he's looking in to. Once resolved, pr rebased and gates pass we can get this in

**Comment by ly5156** [comment]
@aalves08 
I've rebased the code, and all checks have passed.

**Pull request merged**
