### PR TITLE
Feature: Services Wizard

### PR DESCRIPTION
**Pull request by westlywright**
Adds Wizard component to Services:

Note: I disabled the port validation because i need to improve it a bit more and my next ticket is service validation.

Create Page 1:
Screen Shot 2020-07-24 at 10 17 28-fullpage

Create Page 2:
Screen Shot 2020-07-24 at 10 17 37-fullpage

Create Page 3:
Screen Shot 2020-07-24 at 10 17 49-fullpage

Edit Page 1:
Screen Shot 2020-07-24 at 10 25 55-fullpage

Edit Page 2:
Screen Shot 2020-07-24 at 10 20 25-fullpage

### CODE REVIEW

**Comment by westlywright** [comment]
@mantis-toboggan-md will have Wizard style changes in her coming pr, her and I will sync when we're ready to merge if there are any conflicts.

**Comment by westlywright** [comment]
Moved back to a draft because I am adding `Preview Yaml` modal to the steps as indicated in the workload mocks. I would still like a review so I can address feedback sooner rather then later though.

**Comment by vincent99** [comment]
Most of the my same general comments in [#902](https://github.com/rancher/dashboard/pull/902#issuecomment-664695483) apply and can probably be addressed in just one PR..

- For the combo button/dropdown, the entire row should be clickable, not just the `<a>`.  The primary action (left half of the button) should either consistently be or not be in the list of dropdown choices (Create buttons have it, Next doesn't).

- Circles leave something to be desired..
image

- Next is half-disabled?
image

- These notes are obnoxious, especially with multiple of them; info bubbles or the blue header?
image

**Comment by deniseschannon** [comment]
@westlywright Here are the description for each type and each step:

Types: Primarily taken from: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types

```
ClusterIP:
Exposes the service on a cluster-internal IP. Choosing this value makes the service only reachable from within the cluster. This is the default type.

LoadBalancer:
Exposes the service externally using a cloud provider's load balancer. 

NodePort: 
Exposes the service on each node's IP at a static port (the `NodePort`). You'll be able to contact this type of service, from outside the cluster, by requesting `<NodeIP>:<NodePort>`.

External Name:
Maps the service to the contents of the `externalName` field (e.g. foo.bar.example.com), by returning a CNAME record with its value. No proxying of any kind is set up.

Headless:
Neither a cluster IP or load balancer is defined. These are used to interface with other service discovery mechanisms outside of Kubernetes implementation. A cluster IP is not allocated and kube-proxy does not handle these services. 

```

Steps:

```
Step 1:
Select the type of [service](https://kubernetes.io/docs/concepts/services-networking/service/). A service defines how to access a set of pods and the policy to access them. A service typically targets pods by a selector. 

Step 2:
Define the [service](https://kubernetes.io/docs/concepts/services-networking/service/). Define how to access the pods, which pods to target and how to identify your service.

Step 3:
Define the advanced options. Rancher recommends reading more about these fields before attempting to configure them. In most use cases, these options will not need to be modified. 
```

Note: Instead of only showing the icon for in the bar below the wizard steps, can it be the icon with the service type? 


@vincent99 Can you help review these descriptions for wordsmith/language?

**Comment by codyrancher** [comment]
I created [GradientBox](https://github.com/rancher/dashboard/blob/master/components/GradientBox.vue) which you could use to replace the service type selector/heading you could replace the GradientBox just so we stay consistent.

Screen Shot 2020-07-29 at 3 12 45 PM

**Comment by westlywright** [comment]
> I created [GradientBox](https://github.com/rancher/dashboard/blob/master/components/GradientBox.vue) which you could use to replace the service type selector/heading you could replace the GradientBox just so we stay consistent.
> 
> Screen Shot 2020-07-29 at 3 12 45 PM

@codyrancher Awesome, I'll update my code.

**Pull request closed without merging**
