### PR TITLE
4600: add e2e test

### LINKED ISSUE #4600: Unable to create OPA Gatekeeper Templates & Save button missing from Constraints
**Setup**
Rancher version: 2.6.3-rc1 (3 node k3s v1.21.5 KVM setup, 2 node k3s downstream cluster v1.21.5, 2 node RKE1 downstream cluster v1.21.6)
Browser type & version: Chrome 89.0.4389.90 (Official Build)

**Describe the bug**
Add Tempate button is missing in OPA Gatekeeper -> Template.

**To Reproduce**
Deploy OPA Gatekeeper.
Go to Tempate page.

Go to Constraints page.

**Result**
Template page:
No Add Template button (or maybe Create)

Constraints page:
No Save button in Constraints.

**Expected Result**
Buttons missing.

**Screenshots**
image

image

**Additional context**

**Detailed Description**

**Context**

### PR DESCRIPTION
**Pull request by aalves08**
### Summary
Fixes #4600 

### Checklist
- [ ] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [ ] The PR has a Milestone 
- [ ] The PR template has been filled out
- [ ] The PR has been self reviewed 
- [ ] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [ ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Comment by aalves08** [comment]
@yonasberhe23 if this goes in, we can remove the label `automation-candidate` and remove the label `QA-manual-test`

**Review by momesgin — APPROVED** [review]
LGTM

**Review by yonasberhe23 — APPROVED** [review]
LGTM

**Comment by izaac** [comment]
Although this covers the validation of #4600 it isn't completing the e2e. Wouldn't unit tests be enough to validate the ui elements in this case?

**Comment by izaac** [comment]
After some more inspection I see this reached the constaint creation form that uses the default templates which require a Rancher installation. But doesn't validate the created constrain in the constraint table.

**Comment by aalves08** [comment]
@izaac, according to the issue #4600 , the problems raised are:
```
Result
Template page:
No Add Template button (or maybe Create)

Constraints page:
No Save button in Constraints.
```

I believe that the PR covers both, which was the ultimate goal.

**Pull request merged**
