### PR TITLE
restore crd create page

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
#1125  
I'm not really sure where to put the warning about the credential secret; @lvuch might have a better idea there.
Screen Shot 2020-09-02 at 3 48 21 PM

### CODE REVIEW

**Comment by lvuch** [comment]
maybe something like this 
Screen Shot 2020-09-02 at 3 52 15 PM

**Comment by mrajashree** [comment]
The field to accept encryptionConfig name should be a separate field, part of the first section, along with backup filename, delete timeout, prune:
Screen Shot 2020-09-02 at 3 52 29 PM

also to confirm, does clicking on the "Define Storage Location" tab expand s3 details?
Screen Shot 2020-09-02 at 3 53 58 PM

**Comment by mantis-toboggan-md** [comment]
Updated to include `encryptionConfig` and warning color for banner

The 'Storage Location' tab and everything in this screenshot is shown by default: 
Screen Shot 2020-09-02 at 4 10 08 PM

Other tab view:
Screen Shot 2020-09-02 at 4 10 56 PM

**Comment by vincent99** [comment]
- I don't really get this, almost all this info is already in the Backup object, why do I have to (perfectly) enter it again to restore a backup?

It seems like I should just be picking:
  1) Select a Backup I want to restore from
  2) Select the filename within there that I want to restore (which ideally would be picking from a list queried from S3, but not going to happen right now)
  3) Maybe some advanced options (timeout, prune)
  4) Go

Picking a name, labels, annotations for the restore serves no obvious purpose (name can be auto-generated by the UI or with generateName).  The API for restore could directly take a backupName, or the UI can read the backup and copy the relevant values over into the restore.

The only time you *need* to enter all the S3 config and stuff again is you've totally lost the cluster and are restoring from a clean slate.  So that could be a secondary option that exposes all the S3 config.  (Or document that in this case you go create a new Backup entry first, but this seems like you could risk shooting yourself in the foot and retention deleting the backup you actually wanted).

<hr/>

- What happens if there are multiple restores in flight at the same time?  Does something prevent it?

- Is there a reason backups and restores namespaced resources?  The whole feature is basically license to completely destroy the cluster so you already have to be admin to be using it and the usual RBAC reason doesn't seem to apply.

- If the backend named encrypted backups with an e.g. `.encrypted` suffix, then the UI could look at the filename entered and definitively tell you that you need to have the encryption config instead of having the user guess from the warning message.

- What does prune do?  It should be better explained. "Prune all resources that exist in this cluster but are not present in the backup"?

**Comment by mantis-toboggan-md** [comment]
Updated per design review meeting feedback
* autoGenerate is set and name field is hidden
* option to select a target backup crd and populate s3 fields from there
Screen Shot 2020-09-03 at 12 47 46 PM

**Comment by mrajashree** [comment]
Based on offline discussion with @vincent99 and @mantis-toboggan-md , when creating Restore CR:
1. "Target Backup" dropdown will display all Backups. User can select one Backup CR and following fields can be populated
    Backup Filename: Can be read from `Backup.status.filename`
    Encryption Config Name: Can be read from `Backup.spec.encryptionConfigName`
    But both these fields should be editable, so that user can provide other values if needed
2. Since the Backup.spec.encryptionConfigName field will indicate whether the backup is encrypted or not, I don't think we need to change the backup filename to include ".encrypted" suffix?
3. UI will set `generateName` to have the Restore CR name auto-generated so user doesn't have to specify it
4. And yes the Labels and Annotations section, or Description box too doesn't serve a purpose wrt Restore, so both can be removed.
5. Can we display this message next to the "Prune" checkbox to make its purpose clear
```
Enabling "Prune" will delete only those resources/CRs that are managed by the backed up application, and that were not present on the cluster when backup was performed.
```

So the first section for creating a Restore CR will look like this:
Screen Shot 2020-09-03 at 2 21 41 PM

S3 details are not a required field. The way this operator works is, user can configure a global backup location while launching/upgrading the operator (helm chart).
OR
User can specify a particular s3 bucket to restore from/backup to. So, after the first fields for Restore CR, this is what I think we should have

Select Backup Source
(Radio buttons)
Option 1: Use the Backup location configured at the operator level. (Note: Right now there is no way of displaying the exact value in UI)
Option 2: Specify details of the s3 compatible storage provider where the backup file is stored (s3/minio)
   If this option is selected, then we show the fields to configure s3.
Option 3: Use the s3 location specified on the Backup CR. (Question: Can we show this option only if the selected "Target Backup" has s3 details on it?)

**Comment by mantis-toboggan-md** [comment]
Updated per feedback:
* description of `prune` checkbox
* disable the targetBackup dropdown if none are available
* when a target backup is selected, populate `backupFilename`, `encryptionConfigName`, and s3 details if defined in backup
* disable `encryptionConfigName` field if the backup doesn't have `encryptionConfigName` set
* only show warning if no target backup chosen or the target backup `encryptionConfigName` doesn't match the `encryptionConfigName` field
* show radios to choose between using the default storage location from the chart install, specifying an s3 location, or using the target backup s3 location (when applicable)
* remove labels, annotations, and description fields
Screen Shot 2020-09-04 at 10 59 37 AM

**Comment by mrajashree** [comment]
@mantis-toboggan-md After yesterday's design meeting, Restore CRD along with Backup & ResourceSet CRD is now clusterscoped. So the `namespace` field won't apply here.

Also the field `Encryption Config Name` will now be `Encryption Config Secret` keeping it same as the Backup CR per [this](https://github.com/rancher/dashboard/pull/1179#issuecomment-687587459) comment

I know I said that presence of the field encryptionConfigName on Backup CR would be enough to show the encryption config dropdown/warning. But from offline discussion with @vincent99 I see that it won't work on clusters where Backup CR doesn't exist. So the backup file will now have an extension `.enc` for encrypted files. So I think UI should show the encryption config secret based on the backupfile's extension being `.enc`

Can we have a header above the radio buttons that says "Backup Source"?

**Comment by mantis-toboggan-md** [comment]
Based off feedback here and in the [backup CRD PR](https://github.com/rancher/dashboard/pull/1179):

* add label 'backup source' to storage location radio group
* determine if encryption is used by whether or not the backup file name ends with '.enc'
* disable the encryption secret field if the target backup is not encrypted
* show warning about encryption secret if the target backup is encrypted and no encryption secret is selected
* remove namespacing
* credential secret field will set credentialSecretName and credentialSecretNamespace in s3 config

**Comment by deniseschannon** [comment]
@mantis-toboggan-md As these CRDs are now cluster-scoped, we need to remove selecting namespace for this CRD.

**Comment by mantis-toboggan-md** [comment]
Screen Shot 2020-09-10 at 8 41 28 AM

**Comment by deniseschannon** [comment]
What's the label supposed to be for the first dropdown?

**Comment by deniseschannon** [comment]
Let's change storage location options to:
```
* Use the default storage location configured during installation
* Use an S3-compatible object store
```

**Comment by mantis-toboggan-md** [comment]
Missed one translation in cleaning up merge conflicts:
Screen Shot 2020-09-10 at 9 10 00 AM

**Comment by mantis-toboggan-md** [comment]
Updated to include #1186 (redirect from overview to backup list, added link to resourceset in backup list, changed display name from Backup to Backup Restore Operator)
Screen Shot 2020-09-10 at 11 56 57 AM

**Comment by vincent99** [comment]
I'm just going to merge this for now for additional feedback as a separate PR because denise can't test any of it right now

**Pull request merged**
