### PR TITLE
Make kubeconfig ttl global settings configurable

### PR DESCRIPTION
**Pull request by bashofmann**
This adds kubeconfig-token-ttl-minutes and kubeconfig-generate-token to the global settings page

Bildschirmfoto 2021-05-20 um 14 06 06

Addresses: https://github.com/rancher/dashboard/issues/3044

### CODE REVIEW

**Comment by vincent99** [comment]
Can you change just the lines you need in en-us without something linting it & making whitespace changes all over..  this leads to non-conflicts (like right now)

**Comment by bashofmann** [comment]
Done

**Comment by richard-cox** [comment]
Hi @bashofmann , Neil and I had a look and the settings make sense. We tested both ... `kubeconfig-generate-token` worked as expected however changing `kubeconfig-token-ttl-minutes` didn't. Should it change the ttl value of the token generated when downloading kube when `kubeconfig-generate-token` is true... or does it only effect the token generated by the rancher cli tool when `kubeconfig-generate-token` is false?

**Comment by bashofmann** [comment]
It only affects the ttl of the token that is generated by the rancher cli. This is currently documented here: https://rancher.com/docs/rancher/v2.5/en/api/api-tokens/#setting-ttl-on-kubeconfig-tokens.

If kubeconfig-generate-token is true, kubeconfig-token-ttl-minutes currently has no effect.

The rancher CLI currently generates two tokens, a kubeconfig token, which has a TTL, and some login/session token, which does not. This should be fixed in master though: https://github.com/rancher/rancher/issues/31593.

**Review by richard-cox — APPROVED** [review]

**Pull request merged**
