### PR TITLE
Bump rancher version to `v2.9-head` for e2e scripts

### PR DESCRIPTION
**Pull request by rak-phillip**
This bumps the rancher version to `v2.9-head` for e2e scripts

### CODE REVIEW

**Review by richard-cox — CHANGES_REQUESTED** [review]
Gonna be cheeky and request an additional change

This line i think is just a convenience method for dev. For CI the version is in `scripts/e2e-docker-start`, can that be updated too? I've double checked and the image exists

**Review by aalves08 — DISMISSED** [review]
LGTM mate

**Review by richard-cox — DISMISSED** [review]

**Comment by richard-cox** [comment]
I think everyone's given the failing e2e tests a bump. they're both the same issue, a missing link on the home page, probably something genuine with the new image

**Comment by rak-phillip** [comment]
> I think everyone's given the failing e2e tests a bump. they're both the same issue, a missing link on the home page, probably something genuine with the new image

@richard-cox Yeah, it looks to be related to the omission of release notes in `v2.9-head`. I'm not sure if the tests in question make sense, provided that I don't believe we will have 2.9 release notes for quite some time.

**Comment by richard-cox** [comment]
@rak-phillip that makes sense. i think maybe then the test can change to just check the format of the url?

**Review by aalves08 — APPROVED** [review]
LGTM

**Pull request merged**
