### PR TITLE
update kiali url

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
#1247 
Updated url url to `api/v1/namespaces/istio-system/services/http:kiali:20001/proxy/`

### CODE REVIEW

**Review by brendarearden — APPROVED** [review]
Looks good!

**Comment by vincent99** [comment]
@brendarearden Should the ui look for a particular service namespace/name or a label on a service or something instead?  It doesn't _need_ to be hardcoded.  Where would it be if you did a vanilla install of istio outside of our charts?

**Comment by brendarearden** [comment]
@vincent99 `api/v1/namespaces/istio-system/services/http:<name of the service>:20001/proxy/`, so if we could look for that particular service to use the name, that would work. on a vanilla install, I would do a port forward `kubectl port-forward svc/kiali 20001:20001 -n istio-system`

**Comment by vincent99** [comment]
Ok @mantis-toboggan-md can you load `await ...find({type: SERVICE, id: 'istio-ssytem/kiali'})` in fetch, disable the kiali button if not found, and use that to construct the proxy url if it is found?  This will end up with the same result you already have here for us, but handle cases where kiali is missing for 3rd-party installs or whatever reason.

I'd add a `proxyUrl(proto, port)` method to the service model to handle converting `links.viwe` to a proxy URL by slicing last segment off and reassembling it with the input proto (`http`) and port (`22001`) and `/proxy` added.

**Comment by mantis-toboggan-md** [comment]
Added #1184 - I don't think nav counts being updated is specific to Istio, there's another bug about the same type of thing here #1065

**Pull request merged**
