### PR TITLE
Update rancher image version for e2e tests

### LINKED ISSUE #12082: Update `master` to use `head` rancher image in e2e tests
- Think this is just https://github.com/rancher/dashboard/blob/master/scripts/e2e-docker-start#L10
- This will affect
  - Extension tests
  - check-plugin tests

### PR DESCRIPTION
**Pull request by momesgin**
### Summary
Fixes #12082 

### Technical notes summary

E2E test should point to the latest backend, this PR takes care of it.

The skipped tests will be addressed in separate issues:
https://github.com/rancher/dashboard/issues/12327
https://github.com/rancher/dashboard/issues/12325
https://github.com/rancher/dashboard/issues/12338

### Areas or cases that should be tested

n/a
### Areas which could experience regressions

n/a
### Screenshot/Video

n/a
### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Review by mantis-toboggan-md — CHANGES_REQUESTED** [review]
It would be good to update the local command too https://github.com/rancher/dashboard/blob/master/package.json#L29 otherwise the PR looks good

**Comment by momesgin** [comment]
> It would be good to update the local command too https://github.com/rancher/dashboard/blob/master/package.json#L29 otherwise the PR looks good

good catch, thank you

**Review by mantis-toboggan-md — APPROVED** [review]

**Comment by richard-cox** [comment]
the namespace picker flackyness could be down to https://github.com/rancher/dashboard/blob/43a3bfdab928c0d8b3d2ae9b2c3ad8fba3ac09f1/cypress/e2e/tests/pages/explorer2/namespace-picker.spec.ts#L203 being inline rather than gating the rest on `then`. just a guess though

**Comment by momesgin** [comment]
> the namespace picker flackyness could be down to
> 
> https://github.com/rancher/dashboard/blob/43a3bfdab928c0d8b3d2ae9b2c3ad8fba3ac09f1/cypress/e2e/tests/pages/explorer2/namespace-picker.spec.ts#L203
> 
> being inline rather than gating the rest on `then`. just a guess though

Tried it before locally but that didn't fix it, I'll re-try.

**Review by nwmac — APPROVED** [review]

**Pull request merged**
