### PR TITLE
Add wrap styling to image column

### LINKED ISSUE #9235: Image table column should wrap
Example on Pod table:

image

The image column does not wrap/break correctly, so long image names expand the column size.

The `image` column should use `word-break: break-all`.

### PR DESCRIPTION
**Pull request by momesgin**
### Summary
Fixes rancher/dashboard#9235 

### Screenshot/Video
https://github.com/rancher/dashboard/assets/135728925/0f753843-8bda-4adb-8866-18478cb04ecd

### CODE REVIEW

**Review by rak-phillip — COMMENTED** [review]
Does this style belong in the css for sortable table? I would expect styles for `col-pod-images` to be closer to the consumer of this component.

**Comment by momesgin** [comment]
> Does this style belong in the css for sortable table? I would expect styles for `col-pod-images` to be closer to the consumer of this component.

@rak-phillip That's a good point, my understanding from the ticket's description was that we should apply `word-break: break-all` to all the occurrences of image column but I might be wrong

**Comment by rak-phillip** [comment]
@momesgin My main concern is that we're introducing implementation details about consumers of Sortable Table into the component itself. In my opinion, it would be better if this component focused solely on generic concepts related to tables, such as paging, grouping, table headers, table actions, etc...

I believe we can find a better place for this specific style to live. One possible solution could be to utilize styles within our formatters. I think we might have an example of this approach in `shell/components/formatter/KeyValue.vue` and we have `shell/components/formatter/PodImages.vue` available to us. Could you please investigate to see if we can make use of a formatter to resolve this issue?

**Comment by momesgin** [comment]
@rak-phillip Thanks for the explanation, yeah you're right. I'll check the formatter you mentioned above

**Review by rak-phillip — APPROVED** [review]
The formatter implementation looks much better. Thanks for taking the time to follow-up on this approach 🙂

**Comment by momesgin** [comment]
> The formatter implementation looks much better. Thanks for taking the time to follow-up on this approach 🙂

Thanks for the suggestion and your help @rak-phillip

**Pull request merged**
