### PR TITLE
Enhancements for diagnostic page

### LINKED ISSUE #6739: Enhancements needed for the Diagnostic page
**Is your feature request related to a problem? Please describe.**
Enhancements needed for the Diagnostic page

1. Title - `Diagnostics` is vague and from users' pov, it isn't clear what is this page for. Could we add in something more appropriate since its for UI diagnostics?
Screen Shot 2022-08-24 at 11 22 11 AM

2. Download data button --> It isn't intuitive, what data is going to get downloaded. Everything from the page? or just the log? 

3. `Logs` and `Resource Counts` --> These sections must have more info on what logs (Rancher logs or downstream clusters' logs or in this case logs from the browser ) are these and what resources are there (local cluster? or downstream cluster?)

4. There are resources that have `0` count. can we _not_ display these ? 
Screen Shot 2022-08-24 at 11 25 43 AM

**Additional context**
Related to this feature - https://github.com/rancher/dashboard/issues/6544

### PR DESCRIPTION
**Pull request by jordojordo**
### Summary
Fixes #6739 

### Occurred changes and/or fixed issues

- Moved the latest logs to the bottom of the page
- Compacted the system info table into 3 groups:
  1. Browser
  2. System
  3. Javascript memory (doesn't show if not permitted)
- Resource counts table
  - Collapsed by default if more than one cluster
  - Ignored `0` count resources
  - Added to table headers:
    - Total resource counts
    - Total number of nodes
    - Split cluster name and namespace
  - Added column for timings when generated
  - Fixed coloring to match standard table colors
- Converted checkbox into async button for generating timings
- Added dialog when users attempt to download data before generating response times

### Technical notes summary

When the `Download Diagnostic Package` button is clicked it will check for response times with `promptDownload`, if the user has already generated the timings it will download the package as normal. 

### Screenshot/Video

diag

https://user-images.githubusercontent.com/40806497/192038575-35629e31-0582-4930-ba89-f13bcaa69521.mp4

### CODE REVIEW

**Review by aalves08 — APPROVED** [review]
LGTM

**Comment by jordojordo** [comment]
@kwwii Are either of these what you had in mind?

**Example 1**
table1

**Example 2**
table2

**Comment by nwmac** [comment]
@jordojordo We seem to have lost the memory usage, os type from the top section - can we add that back in - the info is not in the download either.

Can we change 'Resource Counts' to 'Resource Counts by Cluster (N clusters)` - where N is the cluster count - just so its super easy to see the number of cluster.

Can we also run timings on the top 15 resources rather than 10 - there are quite a few 'system' resources, so it would be good to ensure we capture some of the others.

**Review by nwmac — CHANGES_REQUESTED** [review]
See comment

**Comment by nwmac** [comment]
@jordojordo Still want this information:

image

to be shown - just in a more compact form.

**Comment by jordojordo** [comment]
@nwmac I have fixed the memory not showing up in the table/data, changed the title for 'Resource Counts', and changed the timing to add the top 15 resources.

diag

**Review by aalves08 — APPROVED** [review]
codewise LGTM

**Review by nwmac — APPROVED** [review]
LGTM

**Pull request merged**
