### PR TITLE
Add Nutanix icon while creating a RKE2/K3s cluster

### PR DESCRIPTION
**Pull request by devpro**
### Summary

Fixes the issue of a generic icon displayed for Nutanix while creating a RKE2/K3s cluster from Rancher, whereas we have the right icon for a RKE cluster.

2023-05-15 09_46_42-Rancher

2023-05-15 09_46_32-Rancher

### Occurred changes and/or fixed issues

New image in shell/assets/images/providers, identical to the one displayed for RKE.

### Technical notes summary

RKE2 references `~shell/assets/images/providers/${ id }.svg`.

### Areas or cases that should be tested

Enable Nutanix node driver then go to the cluster creation page and switch between RKE & RKE2/K3s.

### Areas which could experience regressions

None.

### Screenshot/Video

None.

### CODE REVIEW

**Comment by gaktive** [comment]
Moving to Q3. The issue we have to work around is that the custom Nutanix UI is for RKE1 so the mechanism for RKE2 has to be investigated. Curious how updating an image is causing all the failures.

**Review by richard-cox — APPROVED** [review]
I gave this a quick test and it works fine. 

Nutanix doesn't currently have a custom form for RKE2 machine config's. It does though falls back on the generic key value machine config form from the node driver's schema and it is possible to use (or at least create the prov cluster + machine configs). 

@gaktive there's not much QA can do on this one on top of just visually inspect the icon is there, which is part of the PR review. Any chance we can sqeeze in with `QA None`?

**Comment by tuxtof** [comment]
Hello @richard-cox @gaktive , i see this PR is always open, how we can fix this issue ???

**Comment by richard-cox** [comment]
> Hello @richard-cox @gaktive , i see this PR is always open, how we can fix this issue ???

Unfortunately this PR did not make it in to the next release (2.7.5, previously known as 2.7q2). It is targeted for 2.7q3 and is currently blocked until we fork or release 2.7.5.

**Comment by richard-cox** [comment]
@devpro we've branched for v2.7.5 and can get this one in now. We've beefed up our `e2e-test`s as well, if you rebase your it should pass

**Comment by devpro** [comment]
@richard-cox It should be done but I can't checkout the updated branch locally, there is a typo in one filepath:

image

**Comment by richard-cox** [comment]
> @richard-cox It should be done but I can't checkout the updated branch locally, there is a typo in one filepath:
> 
> image

There should be an update to `master` soon with a fix. @bisht-richa can you link the PR here in a comment for Bertrand to track?

**Comment by devpro** [comment]
@richard-cox all good 😃

**Pull request merged**
