### PR TITLE
add icons to name column in alertmanagerConfig and receiver tables

### LINKED ISSUE #5744: Add receiver icons to Alert Manager Config list page
On the list page for Alert Manager Configs, we need to add receiver icons to services like Slack.

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
Fixes #5744 

This PR adds a table formatter for alertmanagerConfigs and their receivers in order to add logos for each receiver type next to the name. I've moved the `getCustomDetailLink` logic from `LinkDetail` to the new formatter because I think it was only being used for receivers, correct me if I'm wrong @catherineluse 

Icons for alertmanagerconfigs:
Screen Shot 2022-05-04 at 4 49 25 PM

Icons for individual receivers:
Screen Shot 2022-05-04 at 4 49 33 PM

### CODE REVIEW

**Comment by catherineluse** [comment]
That looks like it's working perfectly. However - I'm sorry the issue wasn't clearly written enough. Can the icons be in a separate column with the name of the type next to the icon? Like "[pagerDuty icon] PagerDuty (x2)"? It's just that the icons aren't quite enough info to convey which type of receiver it is because the same icon is reused for email and opsgenie (the @ icon) and some may be ambiguous as to the meaning.
Screen Shot 2022-05-04 at 5 55 09 PM

**Comment by mantis-toboggan-md** [comment]
Updated to move type icons into their own column:
Screen Shot 2022-05-05 at 9 42 54 AM
Screen Shot 2022-05-05 at 9 45 45 AM

**Review by jordojordo — CHANGES_REQUESTED** [review]
There are a couple of oddities I'm noticing,
- Vue is complaining about duplicate keys for icons in the list and detail views
errors

- On the initial load of the 'Receiver in AlertmanagerConfig' page the layout is a bit wonky. If you then go to the detail view for the Receiver the layout fixes itself. (the video might make more sense)

https://user-images.githubusercontent.com/40806497/166976379-0869d3a4-8c7d-4f5b-9124-32b97c09817a.mp4
I tried this in both firefox and chrome with the same issue persisting.

Other than those two things it looks good to me.

**Comment by mantis-toboggan-md** [comment]
Updated to fix duplicate key and style issue. Nice catch @jordojordo, it seems that the style in the first receiver detail view you looked at was being overwritten by another rule, but the second receiver detail, which is actually a different component, overwrote both, so it worked out...I've made the selector more specific to avoid this.

**Review by jordojordo — APPROVED** [review]
Nice sleuthing @mantis-toboggan-md - LGTM

**Pull request merged**
