### PR TITLE
Expose `refreshInterval` input field for cluster repos

### LINKED ISSUE #12486: Add UI option for refreshInterval on a Helm Repository
Internal Reference: SURE-8898

The backend is going to add a new field called [refreshInterval](https://github.com/rancher/rancher/pull/46731/files#diff-b335c5d6572cc7826cac4d401e0534b1830b0744fdaaa5e22cee2dd03fd13bd7R67) to clusterrepo CRD. UI should expose this to the user if he wants to change it. The default is 6 hours for git and http based helm repositories. The default is 24 hours for oci based helm repositories. Refreshinterval defines at what interval the helm repository should be synced.

### PR DESCRIPTION
**Pull request by momesgin**
### Summary
Fixes #12486 

### Occurred changes and/or fixed issues

New labeled input added to the cluster repo page to let users to change the `refreshInterval` for their cluster repos.

### Areas or cases that should be tested

Test the create/edit modes with/without changing the `refreshInterval`
### Areas which could experience regressions

n/a
### Screenshot/Video

https://github.com/user-attachments/assets/7d4b48e4-dd5c-4b0f-8141-11e1c11cdd70

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Comment by edenhernandez-suse** [comment]
In terms of consistency (although I don't love the component itself), we probably should use the input field with unit:

image

If not, at least I would change the label and placeholder to:
- Label: `Refresh interval (hours)`
- Placeholder: `default: 6 hours`

And, ideally, it could just sit inside the "Target" section without its own header, since it's just a setting related to the repo target (how often it's fetched).

@kwwii are you ok with this?

**Comment by momesgin** [comment]
@kwwii @edenhernandez-suse thank you for reviewing, so does this mean we should update the OCI inputs as well to use the same unit input component for consistency?

**Comment by edenhernandez-suse** [comment]
Sorry @momesgin I didn't see the OCI options at the end of the video (in these cases I think having screenshots is a bit better to ensure we don't miss anything). 

Yes, if a field has units, ideally it should use the component with units. The number of retries has no units so that's fine, a regular input type number is perfect. However, the components with units are huge (we should redesign them at some point), so the layout might break. Please ping me in Slack or here if that happens and I'll try to provide a solution.

**Comment by momesgin** [comment]
> Sorry @momesgin I didn't see the OCI options at the end of the video (in these cases I think having screenshots is a bit better to ensure we don't miss anything).
> 
> Yes, if a field has units, ideally it should use the component with units. The number of retries has no units so that's fine, a regular input type number is perfect. However, the components with units are huge (we should redesign them at some point), so the layout might break. Please ping me in Slack or here if that happens and I'll try to provide a solution.

No worries at all @edenhernandez-suse , I had a meeting with Ken yesterday re this issue. I'm currently working on fixing e2e tests after switching to the UnitInput component, I'll reach out either here or on Slack once I'm finished with that.

**Comment by momesgin** [comment]
@edenhernandez-suse here is the final result:

image

image

image

please let me know if anything needs to be changed

**Review by edenhernandez-suse — APPROVED** [review]

**Comment by edenhernandez-suse** [comment]
All good!

**Review by codyrancher — APPROVED** [review]

**Pull request merged**
