### PR TITLE
Fix Harvester v1.0.3 issues

### PR DESCRIPTION
**Pull request by n313893254**
### Summary
Fixes Harvester v1.0.3 issues

### Occurred changes and/or fixed issues

- https://github.com/harvester/harvester/issues/2416
- https://github.com/harvester/harvester/issues/2438
- https://github.com/harvester/harvester/issues/2451
- https://github.com/harvester/harvester/issues/2471
- https://github.com/harvester/harvester/issues/2474
- https://github.com/harvester/harvester/issues/2475
- https://github.com/harvester/harvester/issues/2488

### Technical notes summary

- Add node scheduling for VM and VM template
- Add label filter for image

### Screenshot/Video

[Node scheduling]
image

[Label filter]
image

### CODE REVIEW

**Comment by n313893254** [comment]
CI failed requires this [PR](https://github.com/rancher/dashboard/pull/6356) fixes.

**Review by mantis-toboggan-md — APPROVED** [review]
LGTM, apart from questions around the image label filtering feature: we will need to review how this overlaps with https://github.com/rancher/dashboard/pull/6224 before merging this PR. Converted to 'draft' for the moment.

**Comment by mantis-toboggan-md** [comment]
This PR also addresses #5093 via 
> - https://github.com/harvester/harvester/issues/2438

**Comment by n313893254** [comment]
@mantis-toboggan-md Thanks for your review! I notice the https://github.com/rancher/dashboard/pull/6224 is at the v2.7.0 milestone. And I checked the PR has `hasAdvancedFiltering` property to decide whether enabled advanced filtering. If we do not use advanced filtering on the image page, I think it won’t have conflicts.

**Comment by mantis-toboggan-md** [comment]
@n313893254 I've discussed with @nwmac and we will include the FilterLabel component for the time being, so I will review the rest of this PR today.

 #6224 also allows filtering by label so there was some conversation around getting that merged sooner, but it's not ready, and we're reviewing the design to make it clearer that it supports filtering by label. In the future, when #6224 is completed, we'd like to use that component in Harvester instead of FilterLabel for consistent UX across the dashboard.

**Review by mantis-toboggan-md — CHANGES_REQUESTED** [review]

**Comment by n313893254** [comment]
@mantis-toboggan-md Done, thanks for your review. We will use the new component when https://github.com/rancher/dashboard/pull/6224 is completed.

**Review by mantis-toboggan-md — APPROVED** [review]
lgtm

**Pull request merged**
