### PR TITLE
Switch safemode to use the query param

### PR DESCRIPTION
**Pull request by codyrancher**
Making this switch because using the path can lead to undefined routes and some confusion on wildcard routes.

https://github.com/rancher/dashboard/pull/9135#discussion_r1232391119

### CODE REVIEW

**Review by aalves08 — APPROVED** [review]
lgtm! Thanks for the improvement @codyrancher ! 🙏

**Comment by richard-cox** [comment]
@codyrancher  What milestone is this for?

**Comment by codyrancher** [comment]
> I am sorry, but the approval was wrong here @codyrancher . Richard pointed out quite well that we are missing the route param, which isn't necessarily bad, but we should remove it from the docs and delete the page that it loads (`safemode.vue`) if we are not to use it 🙏

I thought we wanted to leave both options. I've gone ahead and removed the safemode page and route.

**Review by aalves08 — APPROVED** [review]
lgtm

**Pull request merged**
