### PR TITLE
[2.6] HARVESTER: Fix prefs compatibility with Rancher v2.6.x

### PR DESCRIPTION
**Pull request by n313893254**
### Summary
Fix prefs compatibility with Rancher v2.6.x

### Occurred changes and/or fixed issues

Reproduce Steps:
1. Install Rancher v2.6.10, and install Harvester v1.1.1
2. Login Rancher and go to the Global setting. Set `ui-dashboard-index` to `https://releases.rancher.com/dashboard/latest/index.html`. Set `ui-offline-preferred` to `Remote`.
3. Login to the Harvester UI, and go to settings. Set `ui-plugin-index` to `https://releases.rancher.com/harvester-ui/plugin/harvester-latest/harvester-latest.umd.min.js`. Set `ui-source` to `External `
4. Login Rancher and import Harvester.
5. Go to the Harvester cluster and then go to VM list page

The related Harvester PR is https://github.com/harvester/dashboard/pull/567

### Screenshot/Video

[Error]
image

### CODE REVIEW

**Comment by richard-cox** [comment]
@n313893254  Setting the `ui-dashboard-index` to `https://releases.rancher.com/dashboard/latest/index.html` with `remote` will serve up 2.7-head (which currently tracks `2.7.2`). For the latest 2.6 line it's `https://releases.rancher.com/dashboard/release-2.6/index.html` (which i think currently tracks `2.6.11`).

The `view-in-api` setting itself was introduced in 2.7.0 (https://github.com/rancher/dashboard/pull/6947).

I guess I'm not sure the angle of the bug, should dashboard related assets all be 2.6 based where i hope this bug isn't an issue?

**Comment by n313893254** [comment]
@richard-cox Sorry for my mistake with the URL. The URL should be `https://releases.rancher.com/dashboard/release-2.6/index.html.` 

Because the `view-in-api` setting was not introduced in 2.6, an error occurs when v2.6.11 Rancher manages v1.1.2 Harvester.

**Comment by richard-cox** [comment]
In essence a 2.7.x plugin is being loaded in to 2.6.x? I'll check with @nwmac but that doesn't sound like a supported setup.

**Comment by n313893254** [comment]
Yes, you are right. If it can't be supported, at least I hope it won't throw an unworkable error when using the 2.7.x plugin.

**Review by richard-cox — APPROVED** [review]
@n313893254 Ok, sold. Looking at the change it's pretty harmless and I've validated preferences work fine in 2.6-head. Can you raise a matching PR for 2.7 against `master` as well?

**Comment by n313893254** [comment]
@richard-cox, Thanks for your review. The forward port PR is https://github.com/rancher/dashboard/pull/8130

**Pull request merged**
