### PR TITLE
Bump Vue to 2.7.16

### LINKED ISSUE #10329: Bump Vue to 2.7.16
Bump Vue to version 2.7.16, which is the final release on the 2.x release branch.

## Tasks

- [ ] Update the Vue version 2.7.16
- [ ] Notify extension authors about the update

## Release Notes

- https://github.com/vuejs/vue/releases/tag/v2.7.16
- https://github.com/vuejs/vue/blob/main/CHANGELOG.md

### PR DESCRIPTION
**Pull request by rak-phillip**
Bumps Vue from 2.7.14 to 2.7.16.

Release Notes:

- https://github.com/vuejs/vue/releases/tag/v2.7.16
- https://github.com/vuejs/vue/blob/main/CHANGELOG.md

closes #10329

### CODE REVIEW

**Comment by rak-phillip** [comment]
Failing on the plugin check for kubewarden-ui

```
Error: 

Vue packages version mismatch:

- vue@2.7.16 (/home/runner/work/dashboard/dashboard/kubewarden-ui/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.7.14 (/home/runner/work/dashboard/dashboard/kubewarden-ui/node_modules/vue-template-compiler/package.json)
```

Investigating why kubewarden would have an issue here.

**Comment by jordojordo** [comment]
The tests for the Kubewarden UI have been fixed with: https://github.com/rancher/kubewarden-ui/pull/577

`vue-template-compiler` was initially added to the kubewarden package to enable unit-testing but is no longer necessary, the `test-plugin-build` step now [passes the unit tests successfully](https://github.com/rancher/dashboard/actions/runs/7402719993/job/20161944451?pr=10222#step:4:2323).

**Review by jordojordo — DISMISSED** [review]
lgtm

**Review by jordojordo — APPROVED** [review]

**Comment by rak-phillip** [comment]
@nwmac this needs a rebase before we can merge. Tagging you as a reviewer so you can take a look before we merge.

**Pull request merged**
