### PR TITLE
Revert "8712 - fixed plugin icons alignment"

### PR DESCRIPTION
**Pull request by momesgin**
This reverts commit 91b64bdbfe951014221ad5b2dbe79c1cd9a39a1d.

#8712

### CODE REVIEW

**Review by rak-phillip — APPROVED** [review]
LGTM

**Comment by richard-cox** [comment]
I'm entirely lost on this. From my understanding the original bug fix was targeted at 2.7q3 but was merged to master before we branched .. so was included in 2.7.5 branch.

Though 2.7.5 has basically been shipped and no further development will be made on it. At the moment the go forward branch for 2.7 releases is master and future 2.7.x releases will come from it.

It's kinda safe in, given nothing will happen with the 2.7.5 branch. If there's an emergency blocker which entails a new 2.7.5 rc though we would need to check this doesn't break anything

**Comment by richard-cox** [comment]
Please also note. All PRs should have a milestone. Strictly speaking this should have an issue (with milestone) as well

**Comment by momesgin** [comment]
@richard-cox Sorry for the inconvenience

**Pull request merged**
