### PR TITLE
fix advanced filtering issue 

### LINKED ISSUE #7452: Fix issue with advanced filtering
- Fix issue with advanced filtering where we might look for labels on items which don't have any labels associated causing a blocking error

**QA testing**
As for this feature is only available in Elemental (OS management) it's better to be covered by QA for the elemental team @juadk 

If there something to be tested, it's just to make sure the simple filtering of list views is working properly from the POV of `rancher/dashboard`

### PR DESCRIPTION
**Pull request by aalves08**
Fixes #7452 

- fix advanced filtering issue where we were trying to search for a specific value in all cols (including labels) and some items to be searched don't even have `metadata.labels`
- bump rancher icons version

**QA Testing**
**NOTE: This is dependent on republishing the `elemental-ui` extension! will move to testing once it's published.**

- Test on `rancher/dashboard`, `OS management` (elemental) product
- Add the `elemental-ui` repo to `Apps/repositories` so that `elemental-ui` extension becomes available to install
Screenshot 2022-11-07 at 11 40 48

- Install the `elemental-ui` on `extensions` in `rancher/dashboard`

- Install `elemental-operator`

Go to Local cluster -> open kubectl shell -> install helm chart:
```
helm install --create-namespace -n cattle-elemental-system elemental-operator \
             oci://registry.opensuse.org/isv/rancher/elemental/charts/elemental/elemental-operator
```

- Update `elemental-operator`

On the same kubectl shell run:
```
helm upgrade --create-namespace -n cattle-elemental-system --install elemental-operator oci://registry.opensuse.org/isv/rancher/elemental/stable/charts/elemental/elemental-operator
```

- Enter side-menu entry `OS Management`

- Go to `Machine Inventories` list view and create a few items of this resource type

- Make sure advanced filtering is working as expected

### CODE REVIEW

**Comment by cnotv** [comment]
I encountered 2 issues while testing the UI:
- For some reasons on first load the navigation does not show the filter, but it appears if I navigate
- The error is still persistent if I create a resource with a label

Left is local this PR, right is production on DO.

Screenshot 2022-11-15 at 17 12 15
Screenshot 2022-11-15 at 17 12 32
Screenshot 2022-11-15 at 17 13 35


https://user-images.githubusercontent.com/5009481/201972281-f5b7d75f-558b-42ff-b50d-b764f3b1e3ed.mov

**Comment by aalves08** [comment]
@cnotv I don't think this is testable since the extension installed has been built using an npm package called `@rancher/shell`  , from which it gets all of it’s @shell stuff from the core `rancher/dashboard`, including sortable table and filtering…. If I am correct, then I need the code to be approved, then update the `@rancher/shell` package which comes from rancher/dashboard, rebuild the extension and publish it  :sweating: :sweating: :sweating: :sweating:

**Comment by aalves08** [comment]
another way to test is to run the `elemental-ui` repo locally
https://github.com/rancher/elemental-ui
go to `node_modules/@rancher/shell` , modify the code manually and check if it’s running properly

**Comment by aalves08** [comment]
Screenshot from running the repo locally and modifying the code (just a couple of line):

Screenshot 2022-11-15 at 17 12 29

**Comment by aalves08** [comment]
> another way to test is to run the `elemental-ui` repo locally

`For some reasons on first load the navigation does not show the filter, but it appears if I navigate` -> will create a separate issue to deal with that as it's a non-blocker and should be self contained on the `elemental-ui` repo

**Comment by aalves08** [comment]
FYI @nwmac . This is untestable in the current scenario. There are a couple of ways to circumvent it, but not a "straight-line" to easy testing.

**Comment by cnotv** [comment]
As discussed today, we may test this PR by [linking the package with `yarn link`](https://classic.yarnpkg.com/lang/en/docs/cli/link/) as well.

**Comment by aalves08** [comment]
@cnotv can you give it another try, if possible? I need to merge this and release a new version of `@rancher/shell` package so that I can move forward with my Elemental work 🙏 🙇

**Comment by cnotv** [comment]
I am not able to retrieve the branched code and use `yarn link` for some reasons, as the code seems outdated and still cause issues.

Screenshot 2022-11-16 at 20 25 36

**Comment by cnotv** [comment]
Changing the code I still have the same issue 🤔 

Screenshot 2022-11-16 at 20 30 32

@aalves08 Since the `filter.js` file you are working on includes a function and we can setup the test it in 2 minutes, given the right data, I would recommend you to write a unit test out of it.

**Review by cnotv — APPROVED** [review]
LGTM

**Pull request merged**
