### PR TITLE
`Enable IPv6 support` does not work with `RKE2` + `Cilium`

### LINKED ISSUE #10047: `Enable IPv6 support` does not work with RKE2 + Cilium
Internal reference: SURE-7260

**Setup**
- Rancher version: 2.7.9
- Rancher UI Extensions:
- Browser type & version: Firefox 119.0.1 (64 bit)

**Describe the bug**
Enable IPv6 with Rancher UI but `enable-ipv6` is `false`.

```
$ kubectl -n kube-system get cm cilium-config -o json | jq '.data."enable-ipv6"'
"false"
```

**To Reproduce**
Enable IPv6 with Rancher UI and check the value with trailing command.

```
$ kubectl -n kube-system get cm cilium-config -o json | jq '.data."enable-ipv6"'
```

**Result**
```
"false"
```

**Expected Result**
```
"true"
```

**Screenshots**
rke2-cilium-ipv6

**Additional context**

### PR DESCRIPTION
**Pull request by masap**
### Summary
Fixes #10047.

SURE-7260.

### Occurred changes and/or fixed issues

Enable IPv6 with Rancher UI but enable-ipv6 is false.

```
$ kubectl -n kube-system get cm cilium-config -o json | jq '.data."enable-ipv6"'
"false"
```

### CODE REVIEW

**Comment by richard-cox** [comment]
@masap We have recently updated our  e2e gates, would you be able to rebase?

**Comment by masap** [comment]
@richard-cox I rebased and retested it.

**Comment by masap** [comment]
Fixed conflict because `Basics.vue` has been moved.

**Comment by nwmac** [comment]
Closing in favour of https://github.com/rancher/dashboard/pull/10304 (includes automated tests and migration)

**Pull request closed without merging**
