### PR TITLE
Review HTML formatting rules

### LINKED ISSUE #6495: Review HTML formatting rules
**Detailed Description**
Review current HTML formatting:
- Set multiple attribute for element tag in separated rows
- Remove whitespace for closing/opening tag

**Context**
In the current configuration we do not have a consistent rule nor automation for HTML formatting. One line code for HTML element has proven to be complex for review and solve conflicts, as it highlight several parts which are left untouched.
Changes also provide a lot of churn which can be skipped and speed up the review.

We currently do not use Prettier, nor other form of automation, which is rather left to personal IDE configuration. We should therefore set a global project configuration and remove personal ones.

### PR DESCRIPTION
**Pull request by cnotv**
### Summary
Fixes #6495
Add Vue/HTML template formatting rules.

### Occurred changes and/or fixed issues
- Extended ruleset
- Formatted all the HTML pages

### Technical notes summary
Please review using the commits due the extremely high amount of churn.

### Areas or cases that should be tested
CI linter output with the check below.

### Areas which could experience regressions
None.

### Screenshot/Video
Not required.

### CODE REVIEW

**Comment by cnotv** [comment]
Edited files for Merge fixes:
- shell/edit/workload/index.vue
- shell/edit/workload/types/Deployment.vue
- shell/edit/workload/types/Generic.vue

**Review by rak-phillip — COMMENTED** [review]
LGTM - I quite prefer style changes for templates that are represented here. 

I think we just need a rebase before moving forward.

**Review by rak-phillip — DISMISSED** [review]
LGTM - These changes are all tool-generated, based on the updates made to the `eslintrc`. I performed some smoke tests by testing out some basic functionality while observing console output while creating new clusters, deployments, etc..

Because this change touches just about every template across the repo, we should alert the rest of the developer group before merging. I anticipate that a rebase will be required for any WIP that modifies an existing template.

**Comment by cnotv** [comment]
> LGTM - These changes are all tool-generated, based on the updates made to the `eslintrc`. I performed some smoke tests by testing out some basic functionality while observing console output while creating new clusters, deployments, etc..
> 
> Because this change touches just about every template across the repo, we should alert the rest of the developer group before merging. I anticipate that a rebase will be required for any WIP that modifies an existing template.

I think it should suffice to discard incoming changes and save, being carefully of the last commit.

**Comment by nwmac** [comment]
@cnotv Let's not merge this for 2.7, given the timeline

**Comment by cnotv** [comment]
@nwmac not so sure why it was set as `2.7.2`.

**Comment by nwmac** [comment]
We pushed everything that was in 2.7.1 to 2.7.2 so that we can then deliberately bring stuff back in

**Review by richard-cox — CHANGES_REQUESTED** [review]
I've gone through a cross section of file types (components, detail, edits, formatters, etc) and testing some high important sections of the dashboard. All fine except for one blocker and one general comment

Blocker - We should avoid updating the `harvester` pkg. It's now legacy code and not included anywhere until built. It will only be built after very targeted bug fixes and at that stage we won't have done the general testing required for changes of this sort.

Comment - Might be worth reminding the team that empty non-container tags like `input` don't require the closing slashes (previous projects i've always added `/>` but it's optional... and extra bytes...).


cross section of file ttypes, or any particular interesting ones (high volume)

**Comment by cnotv** [comment]
@richard-cox Since to write an exception for something we do not want to maintain may require more efforts than just review the single file, I'll rather keep the configuration and avoid formatting the `pkg/harverster` path

**Comment by richard-cox** [comment]
@cnotv Unfortunately we would need to add an except for the harvester pkg's for the specific rules that make the big changes, otherwise our gates won't pass.

The harvester pkg will be maintained, but in the happy path will not need another release and will eventually be removed.

@mantis-toboggan-md It might be worth giving the Harvester team a heads up of these html formatting updates (to shell), given that they'll bring them in to their fork at some point

**Comment by cnotv** [comment]
> @cnotv Unfortunately we would need to add an except for the harvester pkg's for the specific rules that make the big changes, otherwise our gates won't pass.
> 
> The harvester pkg will be maintained, but in the happy path will not need another release and will eventually be removed.
> 
> @mantis-toboggan-md It might be worth giving the Harvester team a heads up of these html formatting updates (to shell), given that they'll bring them in to their fork at some point

Yeah, it looks like we have to exclude it anyway in somehow 😓

**Pull request merged**
