### PR TITLE
re-load user prefs on login

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
#3282 - This is happening because the `prefs` store data isn't re-loaded when the user changes. Dispatching `prefs/loadServer` on login should ensure the correct user's preferences are available before the index page redirects based off `afterLoginRoute`.

### CODE REVIEW

**Comment by vincent99** [comment]
Seems like this should have a "reset" type call that clears the store in [onLogOut](https://github.com/rancher/dashboard/blob/master/store/index.js#L602) rather than waiting until you login to another user

**Comment by richard-cox** [comment]
> Seems like this should have a "reset" type call that clears the store in [onLogOut](https://github.com/rancher/dashboard/blob/master/store/index.js#L602) rather than waiting until you login to another user

Agreed, we shouldn't have any user specific store state after log out... though hoping we still keep the light/dark theme via cookies.

**Comment by vincent99** [comment]
> though hoping we still keep the light/dark theme via cookies.

Yes there's a [separate mechanism](https://github.com/rancher/dashboard/blob/master/store/prefs.js#L54) ("asCookie") for that and a few others that a best guess is  needed on the login screen.

**Review by richard-cox — CHANGES_REQUESTED** [review]
As per comments

**Comment by mantis-toboggan-md** [comment]
Makes sense; updated to clear (non-cookie) prefs on logout.

**Pull request merged**
