### PR TITLE
Updating the logging installation options

### PR DESCRIPTION
**Pull request by codyrancher**
- Added the 'Additional Loggers' tab
- Added a Cluster Flow placeholder

rancher/dashboard#1109

K3S:
Screen Shot 2020-09-08 at 11 08 41 AM

Not K3S:
Screen Shot 2020-09-08 at 11 07 02 AM

### CODE REVIEW

**Review by paynejacob — APPROVED** [review]
From a design perspective this looks good.

**Comment by vincent99** [comment]
RKE2 should be labeled `RKE Federal`.

These are called services but look like cluster providers, is the user telling you what kind of cluster this is?  We already know that as a property on the cluster so we should be able to fill that in instead of prompting for it.

**Comment by codyrancher** [comment]
Updated to RKE Federal.

I'm using service to be consistent with the language provided here https://github.com/rancher/dashboard/issues/1109#issuecomment-683145943.

@paynejacob regarding Vince's comment. Should we just use the currently cluster provider or is this different in some way?

**Comment by paynejacob** [comment]
If we know the current cluster provider we should use that rather than prompting the user, we can drop the additional loggers tab entirely if that is the case.

**Comment by codyrancher** [comment]
@vincent99 is the container engine something we get back? I don't see it anywhere in the cluster object.

**Comment by vincent99** [comment]
A `management.cattle.io.cluster`'s `status.provider` should return one of [these](https://github.com/rancher/kubernetes-provider-detector/tree/master/providers)

**Comment by codyrancher** [comment]
It does. I've already started using that. I was just wondering if there was something for the K3S Container Engine field. systemd is the default value.

**Comment by vincent99** [comment]
@paynejacob That option seems poorly named (in the chart and therefore dashboard)? "Container engines" are docker, rkt, crio, containerd, etc.  openrc and systemd are "init systems".

@codyrancher yeah that's not going to be something available in the API, but should be renamed to match if the field is.

**Pull request merged**
