### PR TITLE
Ingore FOSSA failures

### PR DESCRIPTION
**Pull request by richard-cox**
- FOSSA checks are still failing with the same error, re-opening https://github.com/rancherlabs/eio/issues/1216
- Instead of removing the check entirely just ignore the failure as per suggested in https://github.com/rancherlabs/eio/issues/1216#issuecomment-1203957485

### CODE REVIEW

**Comment by cnotv** [comment]
Sorry for asking, but where have you seen the error?

**Review by cnotv — APPROVED** [review]
As I cannot verify, I'll just approve 😛

**Comment by saramaebee** [comment]
Hey team! I just wanted to follow up here because we received a support ticket. Can you link me to one of the failing scans that prompted this?

**Comment by richard-cox** [comment]
@saramaebee It's the drone-publish builds for this repo. Please reach out on slack for the url

**Pull request merged**
