### PR TITLE
Masthead update

### PR DESCRIPTION
**Pull request by codyrancher**
- Updated the colors of the mouseover tooltip
- Added a new Tag component to be used with labels
- Updated the masthead layout, changed the data present added a state badge
  - Changed the StateBadge as the borderless badge looked odd in the masthead
- Updated the DetailTop layout and changed the data present
  - If there is no content for DetailTop to display it will display a single line that's the same color of the border
  - If there are no details the details column will not be displayed
  - If there are no labels or annotations the second column will not be displayed
- Updated all the pages making use of detail top to make use of new interface and removed fields such as 'created'
  - I used an array and not weights to maintain order. If that's a problem let me know and I'll switch it.  
- Updated several usages of the CreateEditView mixin as it wasn't being added to the components properly.

**The table of annotations will be updated with Lauren's change**

rancher/dashboard#817

**Tooltip**
Screen Shot 2020-07-10 at 1 16 13 PM
Screen Shot 2020-07-10 at 1 15 48 PM
Screen Shot 2020-07-10 at 1 15 03 PM
Screen Shot 2020-07-10 at 1 13 36 PM

**Tag**
Screen Shot 2020-07-10 at 12 01 49 PM

**StateBadge**
Screen Shot 2020-07-10 at 3 13 35 PM
Screen Shot 2020-07-10 at 3 11 28 PM

**Variations of Layout/Look and Feel**
Screen Shot 2020-07-13 at 12 48 53 PM
Screen Shot 2020-07-13 at 12 38 21 PM
Screen Shot 2020-07-13 at 12 30 56 PM
Screen Shot 2020-07-10 at 3 57 00 PM
Screen Shot 2020-07-13 at 12 35 03 PM
Screen Shot 2020-07-10 at 3 41 37 PM

### CODE REVIEW

**Comment by deniseschannon** [comment]
- [ ] Is there a way to have the label vertically aligned with the words `Labels`? They look to b slightly lower than the text.
- [ ] Age is typically how old it is so it would be something like `2.9 hours` instead of `2.9 hours ago`. I'm not sure how/what you guys are using to calculate that in the code, but @vincent99 do you know what needs to be changed for it? 
- [ ] For labels, what is the max width set on it? So that it will cut off if you have a really long label name.

**Comment by vincent99** [comment]
The "ago" is just a suffix that can be removed.

Annotations should say how many there are ("Show 7 annotations")

I think Label key and value should be more separated (at least `[colon][space]`)

Type in the header should be singular for detail/edit, plural for list.

**Comment by westlywright** [comment]
The only major issue I noticed was the font baseline in the tag when aligned horizontally with a label.

**Comment by codyrancher** [comment]
- I updated the label alignment.
- Removed the Age 'ago' suffix
- There currently isn't a max width. Do we want to give it a pixel width or max it out to the width of the current row? Do we want to show a tooltip that shows the full label if it's too long?
- Added the count to annotations
- Made the type singular
  - I know this is consistent with the way navigation works but is this actually what we want? When click on 'Service' it takes me to a page with the heading 'Services'

Screen Shot 2020-07-14 at 10 29 59 AM
Screen Shot 2020-07-14 at 9 45 18 AM

**Comment by vincent99** [comment]
Can DetailTop just take in the model directly and get description/annotation/labels/etc from it instead of them all having to be individually passed in for every resource and silently breaking if missed (which some, e.g. GenericDetail, do)?

Does DetailTop even need to be a separate component from the Masthead anymore?

**Comment by codyrancher** [comment]
- Reduced the amount of DetailTop usage
  - Since there isn't much usage anymore I left the props as is
- Moved detail customization from slots to a property on the models and using formatters

@vincent99 let me know if you're okay with the changes.

**Pull request merged**
