### PR TITLE
Add support for Linode cloud credentials

### PR DESCRIPTION
**Pull request by jordojordo**
Reference #3599 

This adds support for Linode cloud credentials for rke2 clusters

_Note:_ Currently we do not have support for creating the clusters in Linode, that issue is tracked [here](https://github.com/rancher/dashboard/issues/3261).

**To Test**
- Go to Cluster Management => Cloud Credentials
- Add Linode Credentials

linode-creds

### CODE REVIEW

**Review by catherineluse — CHANGES_REQUESTED** [review]
I created a Linode cloud credential, then tried to provision a cluster using it. But I couldn't provision the cluster because I got the error `this.source.chart is undefined`. I tried the same Linode provisioning in master, but the error isn't in master.

Screen Shot 2022-01-13 at 6 27 56 PM

**Comment by jordojordo** [comment]
> But it seems like a regression because the form isn't visible when using the credential, whereas it is visible in master
I agree, I would say this PR may be premature as [this issue](https://github.com/rancher/dashboard/issues/3261) adds the cluster provisioning that would be using this new credential validation.
I'll switch this to a draft PR for now until the cluster provisioning is complete.

**Comment by jordojordo** [comment]
@catherineluse I've fixed a couple of issues with this PR - Mainly the problem of `this.source.chart` being undefined. This problem existed before my updates, but it was only shown in the console log. The route cause of this is because the backend is utilizing a generic driver for rke2/k3s clusters.
On `v2.6-head` - If you try to provision a rke2 cluster with Linode it will fail as it doesn't have the necessary properties for the [Linode API](https://www.linode.com/docs/api/linode-instances/#linode-create__request-body-schema).

With these updates the provisioning will still fail, but the error `this.source.chart` will not prevent a user from attempting to create a cluster. The main point of this PR is to update the Cloud Credentials page for Linode.

**Comment by catherineluse** [comment]
I tried again and the form rendered properly this time. LGTM

**Review by catherineluse — APPROVED** [review]

**Pull request merged**
