### PR TITLE
Cluster Explorer - Navigation Changes

### PR DESCRIPTION
**Pull request by lvuch**
https://github.com/rancher/dashboard/issues/4118
- apps and marketplace to apps
- add icons to top level

related removes folder and global icons for namespaced and non namespaced: https://github.com/rancher/dashboard/pull/4022

### CODE REVIEW

**Comment by lvuch** [comment]
@nwmac I'm stumped trying to find how to pull for "starred" and "more resources" - any pointers?

**Comment by nwmac** [comment]
not sure what you mean by "how to pull for" ?!

**Comment by richard-cox** [comment]
@lvuch We're close to being able to merge 2.6.2 issues now, if you update merge conflicts I'll take a look

**Comment by nwmac** [comment]
Closing in favour of https://github.com/rancher/dashboard/pull/5161/files - this PR is out of date and has merge markers in the files.

**Pull request closed without merging**
