### PR TITLE
Supress Warning message - v-for index as key

### LINKED ISSUE #8002: Module Warning - v-for index as key
**Setup**
- Rancher version: 2.7.0-head
- Browser type & version: any

**Describe the bug**

A compile warning is shown when running the dashboard in the local environment.

```
 WARN  in ./pkg/harvester-manager/machine-config/harvester.vue?vue&type=template&id=8ff58e0e&scoped=true&                                                           friendly-errors 18:16:46

Module Warning (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):                                                                                      friendly-errors 18:16:46
(Emitted value instead of an instance of Error) Do not use v-for index as key on <transition-group> children, this is the same as not using keys.
                                                                                                                                                                    friendly-errors 18:16:46
 @ ./pkg/harvester-manager/machine-config/harvester.vue?vue&type=template&id=8ff58e0e&scoped=true& 1:0-225 1:0-225
 @ ./pkg/harvester-manager/machine-config/harvester.vue
 @ ./pkg/harvester-manager/machine-config sync \.(vue|js|yaml)$
 @ ./@rancher/auto-import/harvester-manager
 @ ./pkg/harvester-manager/index.ts
 @ ./node_modules/@rancher/dynamic.js
 @ ./shell/core/plugins-loader.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js

```

**To Reproduce**

Run the `master` branch locally.

**Expected Result**

No warning messages should be shown

**Additional context**

Known issue: https://github.com/vuejs/eslint-plugin-vue/issues/726

### PR DESCRIPTION
**Pull request by torchiaf**
Signed-off-by: Francesco Torchia <francesco.torchia@suse.com>

### Summary
Fixes #8002

### CODE REVIEW

**Review by rak-phillip — CHANGES_REQUESTED** [review]
Utilizing `idx + 0` looks like a hack and its intent isn't immediately clear to me. 

I'm guessing that we don't have a unique id associate with any of these values. Maybe we could make use of something like `_.uniqueId` to satisfy this requirement?

https://lodash.com/docs/4.17.15#uniqueId

**Comment by nwmac** [comment]
@torchiaf https://github.com/rancher/dashboard/pull/8132/files appears to fix the first one of these - this PR fixes two more keys - @mantis-toboggan-md @aalves08 - do we need to fix the other two that are changed in this PR?

**Comment by aalves08** [comment]
From my side, I don't see any more warnings @nwmac but i don't have harvester credentials/setup so I never got to the actual cluster creation screen that loads the machine config. https://github.com/rancher/dashboard/pull/8132/files fixes the first one.

**Comment by nwmac** [comment]
@aalves08 okay - I suggest we close this one out in favour of https://github.com/rancher/dashboard/pull/8132/files

**Comment by richard-cox** [comment]
Closing as per https://github.com/rancher/dashboard/pull/8003#issuecomment-1425494602

**Pull request closed without merging**
