### PR TITLE
Fix dropdown styles for custom link and primary colors

### LINKED ISSUE #7501: Custom colors are not applied to dropdowns correctly

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
edit: fixes #7501 

Custom link colors are not applied to dropdowns/action menus because they're using the scss variable. This PR fixes that, along with a couple other tweaks:
* make ns filter border match other input borders (doesn't affect default colors where link and primary match)
* make dropdown selected and hover colors consistent between light and dark themes
* fix typo in SUSE theme

Existing UI with custom primary and link colors:
Screen Shot 2022-09-14 at 1 05 13 PM
Screen Shot 2022-09-14 at 1 13 40 PM
Screen Shot 2022-09-14 at 1 05 55 PM
Screen Shot 2022-09-14 at 1 06 13 PM

This pr with custom primary and link colors:
Screen Shot 2022-09-14 at 1 06 36 PM
Screen Shot 2022-09-14 at 1 07 30 PM
Screen Shot 2022-09-14 at 1 06 51 PM
Screen Shot 2022-09-14 at 1 07 46 PM

This PR with default colors:
Screen Shot 2022-09-14 at 1 08 44 PM
Screen Shot 2022-09-14 at 1 09 04 PM

This PR with SUSE theme (custom primary, default link):
Screen Shot 2022-09-14 at 1 10 08 PM
Screen Shot 2022-09-14 at 1 10 28 PM
Screen Shot 2022-09-14 at 1 09 43 PM
Screen Shot 2022-09-14 at 1 10 35 PM

### CODE REVIEW

**Comment by catherineluse** [comment]
@gaktive what milestone should this be in?

**Comment by gaktive** [comment]
@mantis-toboggan-md was there a Github issue related to this PR? I see the milestone was removed but I don't have context.

**Comment by mantis-toboggan-md** [comment]
@gaktive there was not: this was just something I found while working on a different issue that looked very quick to fix...not sure why I didn't make an issue but did attach a milestone...

**Comment by mantis-toboggan-md** [comment]
Since making this PR dropdown text has been changed from `primary` to `lightest` but there are still issues with custom colors resolved by this pr.

before:
Screen Shot 2022-11-18 at 12 05 01 PM
Screen Shot 2022-11-18 at 12 05 07 PM


after:

Screen Shot 2022-11-18 at 12 04 25 PM
Screen Shot 2022-11-18 at 12 04 36 PM

**Review by catherineluse — APPROVED** [review]
LGTM

**Pull request merged**
