### PR TITLE
automation: part 2 of fixing flaky tests

### PR DESCRIPTION
**Pull request by yonasberhe23**
### Summary
Fixes #
Add intercept/waits to address 
- [namespace-picker failure](https://github.com/rancher/dashboard/actions/runs/8650616959/job/23720789908#step:9:223) in GA 
- [git repo failure](https://jenkins.int.rancher.io/job/rancher_qa/job/ui-automation-job-yonas/45/testReport/junit/Git%20Repo/Create/Should_be_able_to_create_a_git_repo/) in Jenkins

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [ ] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [ ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Review by izaac — DISMISSED** [review]
LGTM

**Review by izaac — DISMISSED** [review]
:shipit:

**Review by izaac — APPROVED** [review]

**Comment by yonasberhe23** [comment]
The flakiness of the `namespace-picker` test was due to the Fleet check being in progress in a fresh Rancher install so the associated filters, such as `cattle-fleet-local-system`, aren't applied until after the Fleet check is complete. To fix this I updated the test to select ‘cattle-fleet-system’ instead because it exists upon user login which is more reliable.
cc: @izaac 

Screenshot 2024-04-16 at 3 03 15 PM

Screenshot 2024-04-16 at 3 05 31 PM

**Comment by izaac** [comment]
Awesome, nice find

**Pull request merged**
