### PR TITLE
Add support for toggle of UI elements based on runtime config

### PR DESCRIPTION
**Pull request by rak-phillip**
This introduces the ability to toggle certain UI elements based on the runtime config. Updates had to be made to the header in order to properly support toggling certain elements. For example, this is a rough outline of the structure for the header before the change:

Untitled-2022-01-24-0922

Removing any given element would still reserve space in the header

Untitled-2022-01-24-0922(2)

After the change, all actions are grouped in an area that is named `rd-header-right`:

Untitled-2022-01-24-0922(1)

Removing elements from `rd-header-right` causes `top` to fill the remaining space and display remaining elements to the right-hand side of the screen

Untitled-2022-01-24-0922(3)

We shouldn't see any observable changes as a result of this PR without making use of the environment variable during development

```
❯ API=https://127.0.0.1:9443 ROUTER_BASE=/dashboard RANCHER_ENV=desktop yarn dev --spa
```

Supports work for Rancher Desktop

rancher-sandbox/rancher-desktop#1364

### CODE REVIEW

**Comment by rak-phillip** [comment]
Raising this PR as a draft for now, we might want to wait for #4933 to merge beforehand to avoid conflicts

**Review by catherineluse — APPROVED** [review]
LGTM

**Review by lvuch — APPROVED** [review]

**Comment by rak-phillip** [comment]
Rebased on top of master and promoted from draft. This could use another good review.

**Review by catherineluse — APPROVED** [review]
LGTM

**Pull request merged**
