### PR TITLE
Vue files are not correctly instrumented by the tests

### LINKED ISSUE #7142: Coverage computation does not match the pull request
# Description

The Codecov report of the coverage is not matching the changed files and returns unreliable delta.

## Context

In [this issue where just an image and CSS has been changed](https://github.com/rancher/dashboard/pull/7071), the reported pointed out some JS files.

Screenshot 2022-10-11 at 08 49 07

In [this other issue](https://github.com/rancher/dashboard/pull/6897) where tests were added, the delta is negative.

Screenshot 2022-10-11 at 08 48 28

Furthermore, the log in the generate page lacks of all the informations reported. Supposedly the issue is related to the Ckeckout action in the CI.

Screenshot 2022-10-11 at 08 22 20

For some reasons it has been also not been reported [any change in `master`](https://app.codecov.io/gh/rancher/dashboard) and may be related to this scenario.

Screenshot 2022-10-11 at 08 53 46

### LINKED ISSUE #9590: Vue files are not correctly instrumented by the tests
# Description

Instrument correctly Vue files to generate code coverage. It is unclear which one of the report from the tests (unit or E2E) does not evaluate correctly.

For the unit tests the files return 0% or 100%, without analyze the script tag content, which explains the low coverage value of the whole project.
For the E2E tests the files are just not considered.

[File example on codecov](https://app.codecov.io/github/rancher/dashboard/blob/master/shell%2Fcomponents%2Fform%2FArrayList.vue)

[HTML report example](https://github.com/rancher/dashboard/suites/15443427144/artifacts/881911113) from the [action](https://github.com/rancher/dashboard/actions/runs/5965355876).

### PR DESCRIPTION
**Pull request by cnotv**
### Summary
Fixes #9590

#### Main fixes

- Added `.vue` extensions for unit tests and E2E in the Babel instrumentation ([example on Codecov from a commit of this PR](https://app.codecov.io/gh/rancher/dashboard/commit/1039e7e4763671e6b062ad93a5b4859526dbae2e))
- Added HTML report for E2E as CI artifact

#### Side changes

- Added alias to the instrumentation [due duplication conflicts](https://github.com/rancher/dashboard/actions/runs/5974244740/job/16208015189#step:5:23)
- Increased memory for tests due [failure](https://github.com/rancher/dashboard/actions/runs/5954375068/job/16155066546#step:5:64)
- Changed ref on the GH checkout action to [Checkout pull request HEAD commit instead of merge commit](https://github.com/actions/checkout#Checkout-pull-request-HEAD-commit-instead-of-merge-commit), avoiding wrong file changes reports and generating false deltas (see first screenshot and [here the log](https://app.codecov.io/github/rancher/dashboard/commit/3fe12acc9758939c624d46bf80a4b32c12cb5483)). 
- ~Restored HTML coverage generation and uploaded as artifacts~ HTML report cannot be used [due issues in generated HTML](https://github.com/rancher/dashboard/actions/runs/5974667702/job/16209244361#step:6:21); created [separated issue ](https://github.com/rancher/dashboard/issues/9602)with low priority 
- Removed deprecated `nyc` configuration in `package.json`, reintroduced with a wrong merge confllict
- Updated excluded paths such like `.nuxt` and `.nuxt-prod`
- Corrected included paths, as E2E skipped `pkg`
- ~Printed out list of changed files on coverage, to ensure correct computation~ Action requires permission, [kept point for records if necessary to debug](https://github.com/rancher/dashboard/pull/7166/commits/31a2c4e4f7dc742158a4088d6fe1214105cbdae6)
- Updated the [Codecov comment below by configuration](https://docs.codecov.com/docs/pull-request-comments), currently disabled by this repo but works in forks

Note: Commit info have been restored by toggling the app in the `rancher` user settings. Full enable triggers checks on coverage delta.

### Areas or cases that should be tested
Generated statistic in this page should solve all the mentioned issues. It's also possible to checkout from this branch and try a PR to own fork and see results, without polluting this repository.

### Areas which could experience regressions
None.

### Screenshot/Video

Screenshot 2023-08-25 at 16 12 46

### CODE REVIEW

**Comment by cnotv** [comment]
This PR is currently not really ready, but the status seems to be required to be listed on Codecov.

**Comment by richard-cox** [comment]
@cnotv PR looks a bit stale, do we need it in 2.7q3 or can it be moved out?

**Comment by cnotv** [comment]
> @cnotv PR looks a bit stale, do we need it in 2.7q3 or can it be moved out?

definitely moved.

**Comment by cnotv** [comment]
> @cnotv PR looks a bit stale, do we need it in 2.7q3 or can it be moved out?

As defined in the [other comment](https://github.com/rancher/dashboard/pull/7166#issuecomment-1285201435), this PR is needed to be set as ready since the results is going to be displayed here.

**Comment by cnotv** [comment]
They may have updated something as now it correctly report only the changed files.
It does not compare to `master` though, which has the same percentage.

Screenshot 2023-08-23 at 14 38 25

**Review by torchiaf — APPROVED** [review]
LGTM

**Pull request merged**
