### PR TITLE
Merge `master` into `epinio-dev`

### PR DESCRIPTION
**Pull request by richard-cox**
### Summary
Fixes https://github.com/epinio/ui/issues/203

### Technical notes summary
- Only changes within the `pke/epinio` folder need reviewing (changes made outside will be reviewed when we merge back to `master`)
- The arg `EXCLUDES_NUXT_PLUGINS` has been replaced with `EXCLUDE_OPERATOR_PKG=false`. Once this merges we need to update docs & inform wider epinio team

### CODE REVIEW

**Review by torchiaf — CHANGES_REQUESTED** [review]
- The `package.lock` file need to be updated. (fixed)
- There was a bug with gtilab apps, `gitlab.js` store was unregistered. (fixed)

- There are some issues with the layout in the creation form, probably regressions on master branch:

  - Table borders are not visible (fixed)
  - Overflow at the bottom

image

Except for the layout, LGTM.

**Comment by richard-cox** [comment]
@torchiaf Had a lot of fun with the wizard. It's now more aligned with how the app chart wizard is... including the required hack added there to be able to see scroll content at the bottom

**Review by torchiaf — CHANGES_REQUESTED** [review]
There is another issue on the bottom of edit page, I pushed another commits, please have a look and if it's all good we can merge for me:

image

**Comment by richard-cox** [comment]
@torchiaf  good spot. ive tweaked the fix to align with that applied to the create app flow

**Review by torchiaf — APPROVED** [review]
LGTM

**Review by torchiaf — APPROVED** [review]
I did a quick test locally. Everything looks good.

**Pull request merged**
