### PR TITLE
save harvester kubeconfig as secret

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**

### CODE REVIEW

**Comment by WuJun2016** [comment]
@mantis-toboggan-md  The backend is not ready, this pr temporarily do not merge.  thanks.

**Comment by mantis-toboggan-md** [comment]
Marking this as draft while the backend side investigates a strategy that will work for standard users (no permission to edit secrets)

**Comment by mantis-toboggan-md** [comment]
Per slack convo with @HarrisonWAffel I've updated this PR to remove the owner references after-save action, and add an annotation referencing the cluster name

**Comment by HarrisonWAffel** [comment]
The backend functionality for this issue has been merged, so this PR should be good for a review

**Comment by WuJun2016** [comment]
@mantis-toboggan-md  @HarrisonWAffel  I re-tested, using the rancher master-head version （2f85f56）,   but the RKE2 cluster created has been unsuccessful, because the RKE2 node startup keeps getting stuck in the system-agent error.
```
Aug 03 07:59:09 wj-4-9-1-pool1-ec250be0-b6tqr rancher-system-agent[1940]: E0803 07:59:09.183337    1940  reflector.go:139] pkg/mod/github.com/rancher/client-go@v1.24.0-rancher1/tools/cache/reflector.go:168: Failed to watch  *v1.Secret: failed to list *v1.Secret: the server has asked for the client to provide credentials (get secrets.meta.k8s.io)
```

The problem that the associated secrets could not be deleted when the cluster was deleted has been solved.


We will test it after upstream-rancher fixes the above issue.

**Comment by HarrisonWAffel** [comment]
@WuJun2016 Have you created an issue for the error you encountered?

**Review by richard-cox — APPROVED** [review]
Code looks good and hasn't broken general RKE2 provisioning (on my oldish backend). @mantis-toboggan-md you're happy that it works, and the Harvester team are happy this merges lets get it in. Is there an issue for this one too?

**Comment by WuJun2016** [comment]
> @WuJun2016 Have you created an issue for the error you encountered?
> 
> [rancher/rancher#38514](https://github.com/rancher/rancher/issues/38514) <- resolved
> 
> @WuJun2016 can you retest this? If it hasn't already been tested elsewhere


> @mantis-toboggan-md @HarrisonWAffel I re-tested, using the rancher master-head version （2f85f56）, but the RKE2 cluster created has been unsuccessful, because the RKE2 node startup keeps getting stuck in the system-agent error.
> 
> ```
> Aug 03 07:59:09 wj-4-9-1-pool1-ec250be0-b6tqr rancher-system-agent[1940]: E0803 07:59:09.183337    1940  reflector.go:139] pkg/mod/github.com/rancher/client-go@v1.24.0-rancher1/tools/cache/reflector.go:168: Failed to watch  *v1.Secret: failed to list *v1.Secret: the server has asked for the client to provide credentials (get secrets.meta.k8s.io)
> ```
> 
> The problem that the associated secrets could not be deleted when the cluster was deleted has been solved.
> 
> We will test it after upstream-rancher fixes the above issue.

@HarrisonWAffel  I re-tested it, and it's now fixed. thanks

image

**Pull request merged**
