### PR TITLE
Cherry picking

### LINKED ISSUE #8657: Support link should go to correct docs of what version is installed
**Setup**
- Rancher version: v2.7.2
- Browser type & version: Firefox SLE 150200

**Describe the bug**
Get support forwards to v2.7.1 page.

**To Reproduce**
Rancher Home -> Commercial Support -> Find out more about SUSE Rancher Support

**Result**
Opens  https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-1/

**Expected Result**
Should show info related to v2.7.2. 

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by momesgin**
Fixes #8657 

* added unit tests for generateSupportLink

* added one more test case for generateSupportLink

* use it.each method to combine separate tests that are related

### CODE REVIEW

**Comment by richard-cox** [comment]
Could you link to the issue that this PR resolved via the `fixes <issue link>` notation from the PR template? That makes it easier for everyone to review, connects it in the gh interface and ensure the issue gets to the correct state once this RR merges.

Having said that though, https://github.com/rancher/dashboard/issues/8657 looks like it targets v2.7.next3, is there a specific 2.7.5 issue?

**Comment by momesgin** [comment]
> Could you link to the issue that this PR resolved via the `fixes <issue link>` notation from the PR template? That makes it easier for everyone to review, connects it in the gh interface and ensure the issue gets to the correct state once this RR merges.
> 
> Having said that though, #8657 looks like it targets v2.7.next3, is there a specific 2.7.5 issue?

I linked the issue, but I am not really sure about the milestone. I'll ask Neil about it and come back to you.

**Comment by richard-cox** [comment]
The target branch of this PR is release-2.7.5 and needs a specific github issue with a v2.7.5 milestone. 

The one linked is for v2.7.next3, the github automation has run and changed the PR milestone to match that issue. However if no-one has requested a backport of that issue, no need to backport the feature. Given where we are with 2.7.5 guessing that's the case  (we're pretty much only fixing blockers).

**Comment by momesgin** [comment]
> The target branch of this PR is release-2.7.5 and needs a specific github issue with a v2.7.5 milestone.
> 
> The one linked is for v2.7.next3, the github automation has run and changed the PR milestone to match that issue. However if no-one has requested a backport of that issue, no need to backport the feature. Given where we are with 2.7.5 guessing that's the case (we're pretty much only fixing blockers).

@richard-cox So here's the problem, my changes related to the issue #8657 was merged into master branch before release-v.2.7.5 branch being created, then I created another PR just writing unit tests for that fix which this backport is all about.

I mentioned this to Gary and he thinks it's better to revert my change to not be included in 2.7.5 at all.

**Comment by momesgin** [comment]
@richard-cox I have created a PR to revert, once it's merged I'll close this PR

**Pull request closed without merging**
