### PR TITLE
Creating the flow and clusterFlow pages

### PR DESCRIPTION
**Pull request by codyrancher**
rancher/dashboard#1127
rancher/dashboard#1126

Screen Shot 2020-09-14 at 9 08 58 AM

Notes:
I need to update outputRefs to local/globalOutputRefs but I'll do this in a followup after I update my cluster and retest.

### CODE REVIEW

**Comment by deniseschannon** [comment]
Is it obvious that you need to select the outputs from that list? Should it say "Select Outputs" somewhere? Either the tab name or a head above the table?

**Comment by codyrancher** [comment]
Which would you prefer?

So far hasn't all of our tab labels and headings been nouns?

**Comment by deniseschannon** [comment]
Workloads CRD has a tab called `Define Container`, but Restore CRD has a label called `Restore from` above a radio button. So it's mostly nouns but have had some verbs.

@vincent99 @lvuch What do you think?

**Comment by vincent99** [comment]
I don't have an immediately better idea but am having a hard time seeing that table as an "input" that I must select something in rather than just a "view" of some tabular data like it normally is.

**Comment by deniseschannon** [comment]
Instead of using a checkbox, what about a link in front of each row that has `Enable` or `Disable` on it so either enable the flow to that output or not? and there's a column with a status of the flow on whether or not it's enabled? 

Is there anywhere else in the UI that we use a multi-select of existing objects? @vincent99 I couldn't think of any better solution or existing example.

**Comment by codyrancher** [comment]
Namespaces for opa constraints.
Screen Shot 2020-09-14 at 4 58 25 PM

But that was abandoned once we decided we wanted to display the outputs.

**Comment by deniseschannon** [comment]
Let's plan to add a banner above the table. @codyrancher @lvuch and I discussed our options and this was the best solution given what we want to represent (outputs and configured providers). 

`Select which output(s) you want your logs shipped to.`

**Comment by codyrancher** [comment]
@deniseschannon do we want to add messaging if there aren't any existing outputs?

Screen Shot 2020-09-15 at 9 28 01 AM

**Comment by deniseschannon** [comment]
@codyrancher 

Let's do `There are no namespaces in the selected namespace.`

**Comment by codyrancher** [comment]
I no longer disable the namespace selector for clusterflow and I added the no outputs messaging banner.

Screen Shot 2020-09-17 at 10 41 05 AM

**Pull request merged**
