### PR TITLE
Fixed focus state for namespace filter

### LINKED ISSUE #7757: Namespace filter, focus
**Setup**
- Rancher version: any
- Browser type & version: any

**Describe the bug**

https://github.com/rancher/dashboard/pull/7665#pullrequestreview-1222589162
The focus effect on the selected option doesn't change the font and icon colors, making them the same color as the bg and therefore invisible.
This is noticeable when navigating through the namespace filter options with the arrow keys.

**To Reproduce**

Click on Namespace filter

**Result**
Focus effect on the selected option doesn't change the font and icon colors.

**Expected Result**

Focused option should be clearly distinguishable from the other ones.

**Screenshots**

namespaces_focus_2
namespace_focus_1

### PR DESCRIPTION
**Pull request by bisht-richa**
### Summary
Fixes #7757

Fixed focus state of the selected option in the Namespace filter

### How to test

Check the focus state of the selected option in the Namespace filter, it should be visible.

### Screenshot/Video

https://user-images.githubusercontent.com/18264463/222056635-75f7251b-756e-49d7-b842-ca23bb3796e1.mov

### CODE REVIEW

**Review by aalves08 — APPROVED** [review]
LGTM @bisht-richa ! Please don't merge this as it's a `v2.7-next2`. 

Curiously, this is a bug introduced by our work for `v2.7.2` since it worked good on `v2.7.1`.

**Comment by richard-cox** [comment]
I can remember there was some fun when implementing the force namespace feature and highlighting. @bisht-richa Can you double check the highlighting is fine by enabling the feature in Global Settings --> Performance and going to a resource list which exceeds the configured limit/threshold?

**Comment by bisht-richa** [comment]
@richard-cox 
You mean this
Screenshot 2023-03-09 at 15 39 04

**Comment by richard-cox** [comment]
> @richard-cox You mean this Screenshot 2023-03-09 at 15 39 04

@bisht-richa That's the one. You'll need to reduce the threshold to avoid creating many many resources. Then go to any explorer list, like Deployments, and if the number of resources exceeds the threshold the feature will be enabled and the namespace filter should change it's behaviour. The highlighting on hover and focus shouldn't be broken there

**Comment by bisht-richa** [comment]
> > @richard-cox You mean this Screenshot 2023-03-09 at 15 39 04
> 
> @bisht-richa That's the one. You'll need to reduce the threshold to avoid creating many many resources. Then go to any explorer list, like Deployments, and if the number of resources exceeds the threshold the feature will be enabled and the namespace filter should change it's behaviour. The highlighting on hover and focus shouldn't be broken there

@richard-cox I have tested above mention use case and it is working fine.

**Comment by richard-cox** [comment]
@bisht-richa Thanks, feel free to merge

**Pull request merged**
