### PR TITLE
HARVESTER: fix Visual Bug during the Harvester upgrade

### PR DESCRIPTION
**Pull request by WuJun2016**
### Summary
Fixes #

- https://github.com/harvester/harvester/issues/4040

### Technical notes summary

When loading the Harvester plugin, `mounted` methed will not re-execute, we need to load the plugin's header component when the route changes

### CODE REVIEW

**Comment by richard-cox** [comment]
Yesterday was code freeze for 2.7q2, so have targeted 2.7q3

**Comment by WuJun2016** [comment]
> Yesterday was code freeze for 2.7q2, so have targeted 2.7q3

Hi,  @richard-cox  This is a issue raised by the customer, can we consider moving it to `2.7.5` ?

**Comment by gaktive** [comment]
Hi @WuJun2016 this part of the code touches a lot of other things, including extensions for other products. This feels risky for something that hasn't been touched in several months; do you have more context about the impact here? 

cc @rebeccazzzz

**Comment by WuJun2016** [comment]
> Hi @WuJun2016 this part of the code touches a lot of other things, including extensions for other products. This feels risky for something that hasn't been touched in several months; do you have more context about the impact here?
> 
> cc @rebeccazzzz

I think if you think this is a risk to other products, then pr can be merged in the next version as it has less impact on users who can refresh the page normally to see the upgrade icon.     cc @rebeccazzzz    @guangbochen

**Review by mantis-toboggan-md — APPROVED** [review]

**Pull request merged**
