### PR TITLE
Porting StorageClass to Dashboard from Ember

### PR DESCRIPTION
**Pull request by codyrancher**
rancher/dashboard#2185

Notes:
- I'm not sure if my provisioner type for custom is correct. Ember didn't function at all for custom. Mine does save and can be retrieved but I'm not sure how I'd verify further.
- The view page is just the edit page in view mode

image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by vincent99** [comment]
- Custom is poorly labeled but that field is "taggable" in Ember so you type the name you want into the dropdown (and then it does work).  So you need the same thing, or a separate field if you choose custom to enter what the provisioner name is.

image

- Reclaim Policy and Binding mode show up as radios with no default selected.

- There are a bunch more provisioners that exist and are available in Ember if you enable the "unsupported-storage-drivers" feature flag.  We don't necessarily have to do these now (or at all) since you can still use them with "custom", but there should be an intentional decision one way or the other.

**Review by vincent99 — CHANGES_REQUESTED** [review]
- Custom is poorly labeled but that field is "taggable" in Ember so you type the name you want into the dropdown (and then it does work).  So you need the same thing, or a separate field if you choose custom to enter what the provisioner name is.

image

- Reclaim Policy and Binding mode show up as radios with no default selected.

- There are a bunch more provisioners that exist and are available in Ember if you enable the "unsupported-storage-drivers" feature flag.  We don't necessarily have to do these now (or at all) since you can still use them with "custom", but there should be an intentional decision one way or the other.

**Comment by codyrancher** [comment]
>     * There are a bunch more provisioners that exist and are available in Ember if you enable the "unsupported-storage-drivers" feature flag.  We don't necessarily have to do these now (or at all) since you can still use them with "custom", but there should be an intentional decision one way or the other.

@vincent99 Who do we need to talk to to make this decision? Neil or Denise?

**Comment by codyrancher** [comment]
- I made custom taggable and the necessary changes to support that.
- I gave reclaim and binding default values.

Let me know who I should read out to and I'll get an answer on the provisioners behind the feature flag.

**Comment by vincent99** [comment]
We'll add a separate issue for providers hidden by the unsupported-storage-providers flag.

**Pull request merged**
