### PR TITLE
Storybook improve landing page

### PR DESCRIPTION
**Pull request by nwmac**
Improves the storybook landing page:

- Adds the same graphics we use elsewhere
- Adds a link to the developer documentation
- Adds a note that this is work in progress

Preview:

image

### CODE REVIEW

**Review by bisht-richa — COMMENTED** [review]
Looks good, but I think instead of two headings can have one.

**Review by bisht-richa — DISMISSED** [review]
LGTM

**Comment by nwmac** [comment]
@bisht-richa Can you check over again - some of the changes in this PR went in with another one - this updates to only have a single title.

**Review by bisht-richa — APPROVED** [review]
Approved

**Pull request merged**
