### PR TITLE
HARVESTER: Fix failed to pass guest cluster name into Harvester cloud provider

### PR DESCRIPTION
**Pull request by n313893254**
### Summary
Fix failed to pass guest cluster name into Harvester cloud provider

### Occurred changes and/or fixed issues

- https://github.com/harvester/harvester/issues/4232

### CODE REVIEW

**Review by mantis-toboggan-md — APPROVED** [review]

**Comment by gaktive** [comment]
Candidate for 2.7.6

**Comment by TachunLin** [comment]
Verified **fixed** on Rancher `v2.7.6-rc2` with Harvester `v1.2.0-rc5`. 

### Result
* We can create load balancer on Rancher, running correctly and assigned by IP pool created of given RKE2 guest cluster name on customized `test1` namespace
  image

  image


* Check the HelmChartConfig in the RKE2. we can find the guest cluster name have been passed to `spec.valuesContent.global`

  ```
  > kubectl get helmchartconfigs.helm.cattle.io -n kube-system harvester-cloud-provider -o yaml
  apiVersion: helm.cattle.io/v1
  kind: HelmChartConfig
  ...
  spec:
    valuesContent: '{"cloudConfigPath":"/var/lib/rancher/rke2/etc/config-files/cloud-provider-config","global":{"cattle":{"clusterId":"c-m-plm7gw9j","clusterName":"rke2-v1267"}}}'
  ```

* Also confirm we can create load balancer on Rancher, running correctly and assigned by IP pool created of given RKE2 guest cluster name on the `default` namespace

  image


### Test Information
* Test Environment: single nodes Harvester on kvm machine
* Harvester version: v1.2.0-rc5
* Rancher version: v2.7.6-rc2

### Verify Steps
<details><summary>Execution Steps</summary>

  1. Import Harvester to Rancher 
  2. Access Harvester from Rancher
  3. Create a namespace test1 under default project
  4. Provision a RKE2 cluster and select test1 as the namespace 
  5. Access Harvester from Rancher
  6. Create an IP pool, select Project default, namespace: test1 and select the RKE2 cluster name 
  7. Access RKE2 guest cluster on Rancher 
  8. Create a nginx deployment on the customized namespace test1 
  9. Create a load balancer service, 
  10. On the ipam mode, select the Pool mode  
  11. Use other namespace like `default` and `harvester-public` and follow above steps  

</details>

**Pull request merged**
