### PR TITLE
Increase restart modal timeout to 5 seconds

### LINKED ISSUE #11087: Modal shown whilst waiting for Rancher to restart given Feature Flag change is broken
**Setup**
- Rancher version: pre 2.9.0

**Describe the bug**
- Feature Flags that require rancher to restart show a warning modal before changing the setting
- Upon executing the change the modal should remain open until Rancher comes back up
- The modal however goes away i think once FF api request completes
- UI is unresponsive given Rancher is restarting
- When rancher comes back up it looks like we continue polling
- User is unable to activate/deactive any other FF (guessing because it thinks the modal is shown) without refreshing

**To Reproduce**
- Global Settings --> Feature Flags
- `Activate` `provisioningv2-fleet-workspace-back-population`
  - This shows modal

**Result**
- as per description

**Expected Result**
- Modal remains until rancher comes back up, and then polling stops

**Screenshots**
image

**Additional context**
- Could be a regression in 2.9.0... or before

### PR DESCRIPTION
**Pull request by rak-phillip**
### Summary
This increases the timeout for the restart modal to 5 seconds. 

Fixes #11087

### Technical notes summary

While troubleshooting this issue, I noticed that we were receiving a 200 response from the server before the Rancher backend finished restarting. It must be that the backend is taking longer to shutdown and responding to our request when it does so.

I'm not a fan of increasing the timeout to an arbitrary number, but this is the most straightforward approach to resolve the issue at this point. The obvious issue with this approach is that we will see the same regression in the future if the backend takes any longer to shut down.

I also considered that we might be able to implement a function that initially polls at a greater duration and then incrementally steps down the timeout for each successive attempt. This would give us the flexibility to increase our timeout to something larger to give us more certainty that the backend has stopped before we first polled. I think this refactoring would be out of scope for resolving this issue. 

### Areas or cases that should be tested

See the description in #11087

### Areas which could experience regressions

See the description in #11087

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Comment by richard-cox** [comment]
It's a little bit more complicated, but we could wait for a non-200 before then waiting for a 200

**Comment by rak-phillip** [comment]
That's not a bad idea, we already know that Rancher must go down before coming back up and it could resolve my issue with just increasing a timeout to resolve the issue. Thanks for the suggestion!

**Comment by rak-phillip** [comment]
Hmm, it might not be that simple. A quick test makes it look like the timeout is waiting in the queue while the event loop gets flooded while polling the websocket.

**Review by jordojordo — CHANGES_REQUESTED** [review]
This does fix the initial issue of the modal closing before the re-connection, but after the request is successful the console is flooded with:

<details open>

```console
[Vue warn]: Computed property "rows" was assigned to but it has no setter.

found in

---> <Management.cattle.io.feature> at shell/list/management.cattle.io.feature.vue
       <ResourceList> at shell/components/ResourceList/index.vue
         <ClusterResourcedList> at shell/pages/c/_cluster/_product/_resource/index.vue
           <Shell/components/templates/default.vue> at shell/components/templates/default.vue
             <Root> [vue.js:5129](webpack:///node_modules/vue/dist/vue.js)
    VueJS 2
    _callee3$ management.cattle.io.feature.vue:166
    Babel 11
    (Async: setTimeout handler)
    waitForBackend management.cattle.io.feature.vue:161
    _callee3$ management.cattle.io.feature.vue:173
    Babel 11
    (Async: setTimeout handler)
    waitForBackend management.cattle.io.feature.vue:161
    _callee3$ management.cattle.io.feature.vue:173
    Babel 11
    (Async: setTimeout handler)
    waitForBackend management.cattle.io.feature.vue:161
    _callee3$ management.cattle.io.feature.vue:173
    Babel 11
    (Async: setTimeout handler)
    waitForBackend management.cattle.io.feature.vue:161
    _callee3$ management.cattle.io.feature.vue:173
    Babel 11
    (Async: setTimeout handler)
    waitForBackend management.cattle.io.feature.vue:161
    _callee3$ management.cattle.io.feature.vue:173
    Babel 2
```

</details>

This seems to cause an issue when attempting to change another feature flag that requires a restart after the connection has been established, the modal will no longer stay open while the connection is lost. 

_Sorry for the long video, it takes awhile for rancher to restart_

https://github.com/rancher/dashboard/assets/40806497/0f10ee2e-31e8-4b60-84fd-733e8e5544f6

**Review by jordojordo — APPROVED** [review]
In that case it looks good to me.

**Pull request merged**
