### PR TITLE
Remove fetching charts when editing an RKE1 cluster

### LINKED ISSUE #10362: Remove the need to fetch helm charts when editing an RKE1 cluster
Internal Reference: ~SURE-7218~ A workaround has been found (using new OCI helm repo support to restrict number of third-party charts fetched)

**Is your feature request related to a problem? Please describe.**
- The create/edit component for prov clusters fetches (all) charts
- It does this to allow the user to choose to deploy RKE2 via cluster template and also if RKE2 is selected (to handle addon configuration)
- However when a user goes to Edit an RKE1 cluster we're still fetching the charts. For systems with a large number of charts this results in a step which can take a while to complete... which isn't needed

**Describe the solution you'd like**
- We should optimise the component to not fetch those charts if the user is editing an existing RKE1 cluster
- This comes with the caveat that the user will hit the same long download of charts when
  - Creating a cluster
  - The Apps pages in the local / upstream cluster
  - Managing extensions
  - Possibly others as well

**Additional context**
- We should be very careful not to break existing cluster based functionality that depends on charts

### PR DESCRIPTION
**Pull request by momesgin**
### Summary
Fixes #10362 

### Technical notes summary

Added a guard in the fetch block of `shell/edit/provisioning.cattle.io.cluster/index.vue`, so we don't make api calls for getting charts only when you're in the Edit mode of an RKE1 cluster.
### Areas or cases that should be tested

Create an RKE1 cluster, then go to its Editing mode page, check the network tab and ensure there's no api call for getting charts

### Areas which could experience regressions

1. While creating an RKE2 or RKE1 clusters check the network tab to ensure we still call for getting charts
2. When going to Edit page for an RKE2 cluster ensure you see the network calls for getting charts

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Comment by momesgin** [comment]
@richard-cox I've tested RKE2 clusters in create/edit modes to check that we're still making the call, same as the create mode of RKE1 clusters. I've also checked the Apps section in Explore page even though this change shouldn't have any impacts there. Is there anything else you might think of that we would need to test?

**Comment by richard-cox** [comment]
As long as you can reach a provider's create page for both rke1 and rke2, and rke2 edit page (and charts are requested) plus for rke2 things like selecting different `Container Network`s result in matching yaml in `Add-On Config` work (powered by charts)... we should be good

**Comment by momesgin** [comment]
@richard-cox thanks for your suggestion, I've tested it and it works as expected. In order to not merge this by mistake I will convert this draft PR to 'Ready For Review' once we've branched for 2.9.0.

**Comment by richard-cox** [comment]
@momesgin Sorry, I've been so slow on this it's hit the vue3 migration. Would you be able to rebase and I'll take a look?

**Comment by richard-cox** [comment]
Thanks for updating. Had a quick look but now blocked on https://github.com/rancher/dashboard/issues/12016

**Comment by momesgin** [comment]
@richard-cox no worries at all, we've all been busy with the vue3 issues, I'm gonna convert this PR to a draft until we're unblocked

**Review by richard-cox — APPROVED** [review]

**Pull request merged**
