### PR TITLE
Align wizard title row

### PR DESCRIPTION
**Pull request by richard-cox**
### Summary
Fix issue where app chart wizard header alignment was off

image

### Occurred changes and/or fixed issues
- Ensure step vertical bar is aligned correctly
- For App Chart Install ensure the os warning tag is placed correctly WITHOUT borking the alignment of the header or changing wizard classes
- Tested
  - Wizard in app chart install - linux only warning and no warning
  - Wizard in cru resource (fleet git repo)
  - Will also validate in epinio wizard later on

Supersede https://github.com/rancher/dashboard/pull/9079

### Screenshot/Video
image

image

image

### CODE REVIEW

**Review by bisht-richa — COMMENTED** [review]
It looks fine just when there is no top banner logo is stuck to the topline

Screenshot 2023-06-09 at 14 38 37

**Review by bisht-richa — COMMENTED** [review]
Looks good only, instead  of `mt-` can use the `pt-` class for the top space

https://github.com/rancher/dashboard/assets/18264463/914534d8-139f-4c98-bdf4-c255c998d7bb

**Comment by richard-cox** [comment]
After a whole day of bumping the e2e gate, this is finally ready to re-review

**Review by bisht-richa — APPROVED** [review]
LGTM

**Pull request merged**
