### PR TITLE
Add script to update docker image

### LINKED ISSUE #6602: Create basic script to update Rancher in Docker containers
**Detailed Description**
Based on the provided [official documentation](https://rancher.com/docs/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/single-node-upgrades/), create script with all the mentioned steps.

**Context**
As it is not possible to update Rancher within the instance, several steps are required for such a task. These operations seem quite straightforward and potentially fully automated for trivial standard cases based on internal guidelines.
This translates into creation of a single Docker image and container with `rancher:2.x.x` version without a name.

Further cases, type of script and operation type are open and not binding, as no alternative is currently provided.

### PR DESCRIPTION
**Pull request by jordojordo**
### Summary
Fixes #6602

This script will update a running instance of Rancher in Docker to a specified image and will create a backup of the original image.

The script needs 2 arguments:
- A container name to be updated
- An image tag for which to update the container with  

### To Test
Run the script:
```console
./scripts/update-docker-image <container-name> <image-tag>
```

### CODE REVIEW

**Comment by cnotv** [comment]
Could you kindly add the info also somewhere in the documentation or as comment within the script if we do not want to make kinda official?

**Comment by cnotv** [comment]
There's an issue with the command which just killed my Rancher 😭 
Although it created the backup.

This is the output:
```
root@gleo-local-rancher:~# docker ps
CONTAINER ID   IMAGE                       COMMAND           CREATED       STATUS       PORTS                                                                      NAMES
60718b326a0f   rancher/rancher:v2.7-head   "entrypoint.sh"   4 weeks ago   Up 3 weeks   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   rancher-27head

root@gleo-local-rancher:~# ./update-docker-image rancher-27head rancher:v2.7-head
Updating Rancher instance rancher-27head to rancher:v2.7-head
rancher-27head
6f97114c71866c0ad015f4c88b70d36e6dec6f3c38425dd53c71c6011c421847
Creating backup
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
22b70bddd3ac: Pull complete 
Digest: sha256:6bdd92bf5240be1b5f3bf71324f5e371fe59f0e153b27fa1f1620f78ba16963c
Status: Downloaded newer image for busybox:latest
tar: removing leading '/' from member names

invalid reference format

root@gleo-local-rancher:~# ls
2022-11-07-data-backup.tar.gz  snap  update-docker-image

root@gleo-local-rancher:~# docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

**Comment by cnotv** [comment]
To reduce the verbosity of the command, we should suppress the list of files printout or at least collect them in a log.

**Comment by jordojordo** [comment]
@cnotv I've updated the docs to include how to run the script. Also have taken the output generated from the backup file creation to a log file rather than the console. 

As for the error you ran into, `rancher:v2.7-head` is not the tag to update your container with, `v2.7-head` would be the correct tag.

**Comment by cnotv** [comment]
Very good job 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 

Screenshot 2022-11-07 at 21 57 41
Screenshot 2022-11-07 at 22 00 08

**Review by cnotv — APPROVED** [review]
LGTM

**Pull request merged**
