### PR TITLE
Remove legacy global configuration

### LINKED ISSUE #12343: Remove Global DNS from UI
Internal reference: SURE-9237

In support of Mapps and their removal of the other Catalog v1, they're taking out code from their side. UI needs to remove links to it.

Support was removed in 2.10 via https://github.com/rancher/rancher/pull/47590

### LINKED ISSUE #12364: Remove Global Catalogs (legacy v1) from the UI
Internal reference: SURE-4858

In support of Mapps and their removal Catalog v1, they're taking out code from their side. UI needs to remove links for the global catalogs.

### PR DESCRIPTION
**Pull request by nwmac**
### Summary
Fixes #12343
Fixes #12364

### Occurred changes and/or fixed issues

This PR removes the legacy menu item from the app bar and the associated pages/code.

This removed 3 pages (embedded from Ember):

- Global Catalogs
- Global DNS Entries
- Global DNS Providers

These are currently only accessed when the legacy feature flag is enabled:

### Areas or cases that should be tested

Enable the `legacy` feature flag and the legacy icon should no longer show in the side bar.

Check that the `legacy` menu item still appears correctly when you browse to a downstream cluster.

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Review by richard-cox — APPROVED** [review]
Do we need to remove MANAGEMENT.MULTI_CLUSTER_APP as well, which is used in one place `shell/models/catalog.cattle.io.app.js` `deployedAsMultiCluster` --> `shell/pages/c/_cluster/apps/charts/install.vue` `this.mcapp` --> which enables custom handling of mcapps in helm chart install/upgrade wizard?

**Comment by nwmac** [comment]
@richard-cox Yeah, I left it in for now. Shall I create another ticket for that and we remove it in 2.10.1 or 2.11?

**Comment by richard-cox** [comment]
@nwmac i'd vote 2.11. looking at the code it's about stopping multi-cluster app functionality rather than supporting it, so safe to leave in for a bit

**Comment by nwmac** [comment]
Created https://github.com/rancher/dashboard/issues/12365

**Pull request merged**
