### PR TITLE
Fix e2e tests failing on 2.9 because of extension version that shouldn't be available to install

### LINKED ISSUE #11996: e2e tests failing on 2.9 because of extension version that shouldn't be available to install
**Setup**
- Rancher version: 2.9
- Rancher UI Extensions: any
- Browser type & version:

**Describe the bug**

1. E2E tests on `release-2.9` are failing because the extension tests are trying to install the `clock` extension `0.3.0`, which is not compliant with `2.9`, despite the presence of the annotation https://github.com/rancher/ui-plugin-examples/blob/main/index.yaml#L10

2. Elemental QA automated tests are failing because Elemental `2.0.0` is not available to install anymore on Rancher `2.9`, which should be compliant and available

**To Reproduce**

**Result**
1. `clock` extension `0.3.0` is wrongfully available to install 
2. `elemental` extension `2.0.0` is not available to install

**Expected Result**

1. `clock` extension `0.3.0` should not be available to install
2. `elemental` extension `2.0.0` should available to install

**Screenshots**

**Additional context**

- Problem lies with `semver.satisfies` not considering suffixed version strings when doing a comparison, ex: 
```
semver.satifies('2.9-4535jda324sff324-head, '>= 2.9') will return false

semver.satifies('2.0.2-rc.1', '>= 2.0.0') will return false
```

**Note: Will need forward-porting to `master`**

### PR DESCRIPTION
**Pull request by aalves08**
### Summary
Fixes #11996 

### Occurred changes and/or fixed issues

- fix problem with `semver.satifies` and version strings with suffixes by removing them using `semver.coerce` (removes `-rcXXX`, `-head`, `-013565asd123sdf34-head`, etc)
- have special logic to do a rancher version check as in `-head` versions of Rancher, the rancher version check is not employed by the backend, therefore we can't rely on it and do it on the frontend side
- remove duplicated method `isChartVersionAvailableForInstall ` as it was duplicated with `isSupportedChartVersion ` and adjust logic
- This will also fix a related problem that Elemental QA just reported. Check issue body

### Technical notes summary

- Will need forward-porting to `master`

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Review by richard-cox — CHANGES_REQUESTED** [review]
Changes looks good, however

1. At some point, not now, we should handle the case where `-head` translating to a patch of 0 will incorrectly exclude some plugins. For example 2.9-head tracking 2.9.10, however translates to 2.9.0... which would exclude extensions blocking on 2.9.5. We could consider making the patch version of head builds super high, given that extensions shouldn't be blocking things higher than the possible rancher version :man_shrugging: 
2. On v2.9-head i see the clock app as available, however all three versions are marked as disabled. Would expect 0.3.0 to be disabled and other's ok 
image

**Comment by aalves08** [comment]
> Changes looks good, however
> 
> 1. At some point, not now, we should handle the case where `-head` translating to a patch of 0 will incorrectly exclude some plugins. For example 2.9-head tracking 2.9.10, however translates to 2.9.0... which would exclude extensions blocking on 2.9.5. We could consider making the patch version of head builds super high, given that extensions shouldn't be blocking things higher than the possible rancher version 🤷‍♂️
> 2. On v2.9-head i see the clock app as available, however all three versions are marked as disabled. Would expect 0.3.0 to be disabled and other's ok
>    image

1. You've got a great point here! We can check for the string `-head` and forcefully change the patch number `0` to `999`. I also think this is the best time to do this since we are merging this now and we will lose the window of opportunity before a release.

2. 3 problems spotted here:

1 - So, I've added an extra `!` in the change of line 199 where it shouldn't be one. Should read `requiredUiVersion && ...` instead of `!requiredUiVersion && ...`. 

2 - After fixing `1 -`, there's another problem which is that Rancher will not serve the helm chart version of an extension **IF** we are on a **non-head** world (simply doesn't serve it on the network request), but we are on a `head` world, which means that check is not done by the backend, but it can't be ignored by the frontend on that specific case, hence why after fixing `1-` the `0.3.0` was appearing as available to me in `2.9-head`. I'll add an extra check for this.

3 - Even after fixing `1 -` and `2 -`, the remaining problem is that it's now failing on the kube version check (view screenshot). What I can do is change manually the annotations on `index.yaml` to fix this.
I had my 1-1 with Neil and he will work on a mechanism that will allow us to fix annotations in already published versions. It's a must-have with all these breaking changes that we provide a way for developers to fix their annotations from previous versions. 
Now we will have to do a "manual" fix on `index.yaml` for the examples, which won't be re-published any time soon (hence, won't overwrite the manual changes on index.yaml)

Will update the PR accordingly

**Review by richard-cox — CHANGES_REQUESTED** [review]
Ran through code, only a couple of suggestions. Removing `isChartVersionAvailableForInstall` is great.

Gave it a quick try as well, clock working as expected for 2.9.1, 2.9-head and head.

Will give everything a last pass test tomorrow after changes

**Review by richard-cox — APPROVED** [review]
tested in head (2.10), 2.9-head, 2.91, all working fine.

we do need to sort out the fallback for extension versions that haven't explicitly set a post 2.9 restriction, but that cna be done in another PR

image

**Pull request merged**
