### PR TITLE
fix(explorer/index): add cpu unit to the cores capacity section

### PR DESCRIPTION
**Pull request by ly5156**
### Summary
Fixes #

https://github.com/rancher/dashboard/issues/6327

### CODE REVIEW

**Comment by aalves08** [comment]
FYI @richard-cox couldn't run this fork+branch of Rancher Dashboard (tried with node versions 14 and 16...) 🤷  Same error for both.

```
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):                                                                                   friendly-errors 18:07:22
Thread Loader (Worker 0)
[BABEL] /Users/aalves/Desktop/PROJECTS/ly-dashboard/.nuxt/client.js: Invalid Option: The plugins/built-ins '@babel/plugin-proposal-private-property-in-object' passed to the 'exclude' option are not
    valid. Please check data/[plugin-features|built-in-features].js in babel-preset-env (While processing: "/Users/aalves/Desktop/PROJECTS/ly-dashboard/node_modules/@nuxt/babel-preset-app/src/index.js$0")
    at PoolWorker.fromErrorObj (/Users/aalves/Desktop/PROJECTS/ly-dashboard/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at /Users/aalves/Desktop/PROJECTS/ly-dashboard/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at invariant (/Users/aalves/Desktop/PROJECTS/ly-dashboard/node_modules/invariant/invariant.js:40:15)
    at expandIncludesAndExcludes (/Users/aalves/Desktop/PROJECTS/ly-dashboard/node_modules/@nuxt/babel-preset-app/node_modules/@babel/preset-env/lib/normalize-options.js:64:26)
    at normalizeOptions (/Users/aalves/Desktop/PROJECTS/ly-dashboard/node_modules/@nuxt/babel-preset-app/node_modules/@babel/preset-env/lib/normalize-options.js:180:19)
    at /Users/aalves/Desktop/PROJECTS/ly-dashboard/node_modules/@nuxt/babel-preset-app/node_modules/@babel/preset-env/lib/index.js:239:37
    at /Users/aalves/Desktop/PROJECTS/ly-dashboard/node_modules/@nuxt/babel-preset-app/node_modules/@babel/helper-plugin-utils/lib/index.js:22:12
    at async (/Users/aalves/Desktop/PROJECTS/ly-dashboard/node_modules/@babel/core/lib/gensync-utils/async.js:44:33)
    at async (/Users/aalves/Desktop/PROJECTS/ly-dashboard/node_modules/gensync/index.js:186:15)
    at /Users/aalves/Desktop/PROJECTS/ly-dashboard/node_modules/gensync/index.js:216:13
    at Generator.next (<anonymous>)
    at /Users/aalves/Desktop/PROJECTS/ly-dashboard/node_modules/@babel/core/lib/config/full.js:217:21
                                                                                                                                                       friendly-errors 18:07:22
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
```

**Comment by aalves08** [comment]
@kwwii from a UX perspective, do we to show units on the areas marked as red on the screenshot? It would be "cores". 
Also, we don't that for Pods.

Screenshot 2022-07-14 at 18 12 57

**Comment by kwwii** [comment]
I think that anything that is a simple number like pods or cores can be shown without a label because the title is the label itself and the value will always be a natural number. Something ambiguous like memory needs clarification on the other hand.

**Comment by catherineluse** [comment]
@ly5156 Do you have time to make the requested changes? If not, someone from our team could do it.

**Comment by ly5156** [comment]
> @ly5156 Do you have time to make the requested changes? If not, someone from our team could do it.

Sorry for the late reply, I have redone the rebase operation

**Review by aalves08 — APPROVED** [review]
LGTM

**Pull request merged**
