### PR TITLE
automate docs team notification for release notes

### PR DESCRIPTION
**Pull request by martyav**
### Summary

This solely pertains to the Github repo and internal processes.  It adds a Github action that automatically emails the docs team about release notes.

---

We use the `release-note` label to indicate issues that should be added to the release notes. However, unless an engineer or manager alerts the docs team, the docs team receives no notice that the issue needs to be added. Docs writers need to manually check the repo frequently to make sure they don't miss any issues during the release cycle. This can be especially hectic and failure-prone towards the end of a release.

This PR adds a brief (10-14 second) Github action that automatically adds a comment to issues labeled with `release-note`. The comment pings the docs team recipients listed in the .yml, which triggers an email notification that alerts them that an issue needs a release note.

See https://github.com/jenschelkopf/issue-label-notification-action for details on the Github action.

### CODE REVIEW

**Comment by martyav** [comment]
See https://github.com/rancher/rancher/pull/42926 for more detailed comments and links to an example on a fork of rancher/rancher

**Review by richard-cox — CHANGES_REQUESTED** [review]
This will add a comment on every issue with a label.

You'll need to add a gate to the job, something like 

```
if: ${{ github.event.label.name == 'release-note' }}
```

Edit: Ah, unless jenschelkopf/issue-label-notification-action does the filtering automatically? Does that automatically stop the workflow from running if there's no config for the label that changed (as there label action runs a looooot)

**Comment by martyav** [comment]
@richard-cox Line 15 maps a particular label to a particular recipient or recipients. 

You can see how the action does the filtering here: https://github.com/jenschelkopf/issue-label-notification-action/blob/master/index.js. 

Line 10 looks at the label applied to the issue. Lines 17 and 18 match the label we specify in the yaml against the label applied to the issue. If the labels match, it creates a comment to trigger a notification. If not, it logs "No matching recipients found for label ${label}." (lines 23 to 33).

**Review by richard-cox — APPROVED** [review]

**Comment by richard-cox** [comment]
@martyav can you rebase? that should hopefully resolve issues with gates

**Comment by richard-cox** [comment]
@martyav sounds good!

**Comment by martyav** [comment]
closing as my attempt at rebasing just made the commit history more confusing, instead of less.

**Pull request closed without merging**
