### PR TITLE
Initialize always auth errors as empty list

### LINKED ISSUE #5615: Rancher Dashboard UI - Auth Provider Page - When selecting "Github", a blank page displays with no instructions
**Setup**
- Rancher version: 2.6-head 15b8f2c
- Browser type & version: Chrome Browser (Version 99.0.4844.83)

**Describe the bug**
When you click inside of the external auth provider "Github" you get a blank page

**To Reproduce**
1. Sign into Rancher on a Node which has a RKE1 cluster 
2. On the top-right menu, click the "Users and Authentication" option
3. Select the "Auth Provider" option.
4. Click the "Github" Authentication Provider option on the screen

**Result**
The screen displays as blank and you DO NOT get any instructions for setting up Github as your external authentication provider.

**Expected Result**
You should see instructions display on the screen for setting up your github external authentication.

**Screenshots**
image

**Additional Notes**
Attached is also a screenshot of the console logs once on that page for Github External Auth provider.
image

### PR DESCRIPTION
**Pull request by cnotv**
### Summary
Fixes #5615
Prevent to break application while entering in authentication provider edit view.

### Occurred changes and/or fixed issues
In case of authentication, Initialized errors are not defined as list.

### Technical notes summary
It seems like the rendering also differ in case of SSR, so the component is also always loaded.

### Areas or cases that should be tested
Auth provider edit view `/c/local/auth/config/github?mode=edit`

### Areas which could experience regressions
Any view containing form which has the errors initialized, which is pretty much anything from the last commit.

### Screenshot/Video
Screenshot 2022-04-11 at 21 33 35

### CODE REVIEW

**Review by richard-cox — CHANGES_REQUESTED** [review]
A lot of these aren't associated with the CruResource which is the root of the problem. Changing the other locations could bring in other issues. Making the `if` safe with something like below would be much safer
```
hasErrors() {
  return errors?.length;
}
...
:v-if="hasErrors"
```

**Comment by cnotv** [comment]
What if somewhere in the code they change the errors into a string?

**Comment by cnotv** [comment]
I also added the check if is an Array, since we allow to manipulate to any type of data.

**Review by richard-cox — APPROVED** [review]
I've sneaked in some unrelated fixes regarding the auth config warning, for some providers it wasn't correctly in the CruResource

**Review by nwmac — APPROVED** [review]

**Pull request merged**
