### PR TITLE
NamespaceFilter: add Enter shortcut

### LINKED ISSUE #5798: [UI] - Search box - Select on Enter
Rancher 2.6.4 - UI

On the Search box
image

In this sample, when input "data", and press enter : Nothing happends

It would be great to add "data" to the filter on Enter press, cause one item match exactly : 
image

And also clean the filter box to let user input another filter, and so on...

### PR DESCRIPTION
**Pull request by torchiaf**
- add Enter key shortcut in case of searching word returns exactly one result.
- fix css

Signed-off-by: Francesco Torchia <francesco.torchia@suse.com>

### Summary
Fixes #5798

### Areas or cases that should be tested

- Namespaces Search box

### CODE REVIEW

**Comment by torchiaf** [comment]
@aalves08 I am not sure that to clean the filter after pressing Enter makes the life easier to the users.

https://github.com/rancher/dashboard/blob/ce031f26e127198735f692bb3bfa8f0206e663b1/shell/components/nav/NamespaceFilter.vue#L443

One of the use cases that comes to my mind is for example when a user  wants to filter a group of namespaces that all starts with the same prefix:

image

when one of these is selected, typing the full name and pressing Enter, the filter is automatically cleaned and the user have to type again the prefix if he wants to select the second namespace.
It's much more simpler to delete a few characters from the previous keyword to find again the remaining namespaces.

**Comment by aalves08** [comment]
Was able to test the feature and it seems to work as expected. One thing that I noticed was that I could never enter the homepage properly... Got some issues with the `CommunityLinks` component (check screenshot). I think your branch might not be updated with the latest `master` on `rancher/dashboard`.

```
git remote add upstream git@github.com:rancher/dashboard.git
git fetch upstream
git rebase upstream/master
```

You should also check what backend version you are using as well as there's a new one out `v2.7-head`.

Otherwise, LGTM. 

Let me know once this is resolved. Thanks! 🙏 

Screenshot 2022-10-12 at 11 06 53

**Comment by torchiaf** [comment]
> Was able to test the feature and it seems to work as expected. One thing that I noticed was that I could never enter the homepage properly... Got some issues with the `CommunityLinks` component (check screenshot). I think your branch might not be updated with the latest `master` on `rancher/dashboard`.
> 
> ```
> git remote add upstream git@github.com:rancher/dashboard.git
> git fetch upstream
> git rebase upstream/master
> ```
> 
> You should also check what backend version you are using as well as there's a new one out `v2.7-head`.
> 
> Otherwise, LGTM.
> 
> Let me know once this is resolved. Thanks! pray
> 
> Screenshot 2022-10-12 at 11 06 53

Thanks Alex. It seems to be resolved after the rebase.

**Review by aalves08 — APPROVED** [review]
Sorry for the delay here @torchiaf . LGTM 🙏

**Review by aalves08 — APPROVED** [review]
LGTM

**Pull request merged**
