### PR TITLE
[master] Ensure we wait for required resources before leaving cluster import / create rke2

### LINKED ISSUE #3396: [V2 Provisioning] Registration tab not selected by default during cluster creation
When you create a custom RKE2 cluster, the registration tab is not selected by default, once you created the cluster. Instead the empty machine pool tab is shown.

Bildschirmfoto 2021-06-30 um 12 01 32

The registration tab should be selected to guide users through the next steps of creating a custom cluster.

### PR DESCRIPTION
**Pull request by richard-cox**
1) Ensure we don't nav away while calling `this.save`
2) Ensure we don't nav away when errors in `this.save`

This should resolve #3396 and most of #3677

2.6 PR #3711

### CODE REVIEW

**Comment by vincent99** [comment]
Shouldn't the whole saving members just be implemented as a registered after save hook?  There's already an existing mechanism there for "do some extra stuff between save and done".  

And the hooks fire in the edit yaml mode, which this (& current) probably don't and just leave you with no members?

**Comment by richard-cox** [comment]
Mostly left this as was, also thought the hooks weren't blocking so avoided (i missed out some error handling in this PR which i had in the non-admin one where the change came from).

Not sure how the member stuff would work in yaml mode, given that it's all bindings outside of the core provisioning cluster yaml.

Either way will switch both to use the hooks

**Comment by richard-cox** [comment]
Actually. thinking about it, we shouldn't block on role create failure. The user might try and create the cluster again. We should return to the cluster list and show a growl?

**Comment by vincent99** [comment]
Hooks are supposed to be blocking (as in awaitable until they're finished) but weren't until yesterday-ish because they were using `await emit('applyHooks')` and you can't return a value from emit so awaiting did nothing.  This caused pools to not get saved right sometimes from the before hook that wasn't finished before regular save tried to use the result of it.

I'd just leave it as a hook and if there's an error in the binding create it leaves you where you are for now.  That should be rare since we shouldn't let you ask for invalid bindings, and is probably handled ok anyway. The the cluster save() should do an update if called again as if it were an edit instead of another create at that point.

For the yaml edit, I added a way it to show all the objects we're going to create as a multi-document yaml and then let you edit/apply that for this cluster-creates-several-resources case.  The bindings could go in there too.  But it's commented out for 2.6.0 because we currently have to pre-save the machine configs to tie the name into the pool and our "kubectl" apply endpoint only supports creates, not updates.

After 2.6.0 we can improve this to accept updates in apply or do some kind of variable substitution so that they're not pre-saved.

**Review by nwmac — APPROVED** [review]
LGTM

**Pull request merged**
