### PR TITLE
feat(workload/storage): support add emptyDir volume

### LINKED ISSUE #7533: [Bug] Rancher 2.6 is missing emptyDir from volume types.
Duplicating issues:
https://github.com/rancher/rancher/issues/34638
https://github.com/rancher/rancher/issues/36760

**Setup**
- Rancher version: 2.6.*
- Browser type & version: FF, Chrome, latest

**Describe the bug**
If you create a deployment and want to add an emptyDir volume, you cannot select that from volume type dropdown
```
      volumes:
      - emptyDir: {}
        name: somename
```

**To Reproduce**
1. Create a deployment
2. Storage -> Add Volume
3. emptyDir not existent

1. Import a deployment with an empty dir
2. update the deployment
3. storage, you are unable to change the name of the emptyDir mount, no field available

**Result**

**Expected Result**
1. EmptyDir is available in dropdown
2. EmptyDir name can be changed on update of an deployment

**Screenshots**
grafik
grafik

### PR DESCRIPTION
**Pull request by ly5156**
### Summary
Fixes #7533

workload support add emptyDir volume

ref: https://kubernetes.io/docs/concepts/storage/volumes/#emptydir

### Occurred changes and/or fixed issues

https://github.com/rancher/dashboard/issues/7533

### CODE REVIEW

**Review by aalves08 — APPROVED** [review]
LGTM in terms of testing and code

**Comment by aalves08** [comment]
@richard-cox can this be merged?

**Comment by richard-cox** [comment]
@aalves08 Yes, but won't be available for QA until https://github.com/rancher/rancher/pull/39899 merges

**Comment by aalves08** [comment]
Ok. Thanks @richard-cox . I've added myself to https://github.com/rancher/rancher/pull/39899 so that I know when it's merged. After that I'll move this issue to testing. 🙇

**Pull request merged**
