### PR TITLE
update Chinese translation

### PR DESCRIPTION
**Pull request by vickyhella3**

### CODE REVIEW

**Comment by richard-cox** [comment]
@WuJun2016 / @n313893254 Would it be possible if someone gave this a quick review, is this required for 2.6.4?

**Review by n313893254 — APPROVED** [review]
LGTM

**Review by WuJun2016 — APPROVED** [review]
LGTM

**Comment by WuJun2016** [comment]
I think it should be merged to 2.6.4

**Comment by richard-cox** [comment]
Thanks all!

**Pull request merged**
