### PR TITLE
Revert vue-js-modal removal as required in Harvester

### PR DESCRIPTION
**Pull request by torchiaf**
### Summary
Fixes https://github.com/rancher/dashboard/issues/10675

### Technical notes summary

Modal dialogs in Harvester embedded-mode require vue-js-modal package.

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Review by rak-phillip — COMMENTED** [review]
We need to drop this dependency so that we'll have a path forward. Do you think that we'll be able to migrate Harvester away from `vue-js-modal` instead of reintroducing it into dashboard?

**Comment by torchiaf** [comment]
> We need to drop this dependency so that we'll have a path forward with the Vue3 migration. Do you think that we'll be able to migrate Harvester away from `vue-js-modal` instead of reintroducing it into dashboard?

@rak-phillip yes, there will be a porting of the modals migration on Harvester, but this will work for newest Harvester versions.

In the case the users updates their Rancher version to `v2.9-head`, having an older Harvester version, they will still get the error.
I think this is the only way we have to preserve the compatibility until they upgrade Harvester.

**Review by rak-phillip — DISMISSED** [review]
@torchiaf Thanks for the additional context. I think it makes sense that we merge this, but we'll need to take extra care not to introduce new usages of `vue-js-modal` as we develop new features moving forward.

**Comment by torchiaf** [comment]
@rak-phillip I pushed a new change to fix a build error: https://github.com/rancher/dashboard/actions/runs/8417966453/job/23047462028
Could you have another a look ?

**Review by rak-phillip — APPROVED** [review]
LGTM

For reference, this appears to be the build error that we encountered[^1] 

```
 $ ./node_modules/.bin/vue-cli-service build
Build: Production
Version: undefined
API: 'http://localhost:8989'. Env: 'web'

-  Building for production...
 ERROR  Failed to compile with 1 error9:41:48 AM

This dependency was not found:

* vue-js-modal/dist/ssr.index in ./node_modules/@rancher/shell/plugins/vue-js-modal.js

To install it, you can run: npm install --save vue-js-modal/dist/ssr.index
 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

Which is quite curious, as this is how we previously imported the module for the plugin.. However, we don't rely on ssr anymore, and the fix makes sense. 

[^1]: https://github.com/rancher/dashboard/actions/runs/8417966453/job/23047462028

**Pull request merged**
