### PR TITLE
add e2e test for issue 10412

### LINKED ISSUE #10412: RKE2 Registries - When multiple registry authentication hosts exist and one is removed, an incorrect secret name is rendered
**Setup**
- Rancher version: 2.9-head

**Describe the bug**

When you have multiple registry authentication hosts if you remove one of them the other one doesn't show its original secret name anymore. This is just a rendering issue since after save the payload still has the original secret name.

**Screenshots**

https://github.com/rancher/dashboard/assets/135728925/2eee1e79-98ff-45ce-90b4-c92ca87735e7

### PR DESCRIPTION
**Pull request by aalves08**
### Summary
Fixes #10412 (e2e testing)

### Occurred changes and/or fixed issues

- Adds pattern to e2e tests for editing a fake cluster (`edit config`)
- Add e2e test to prevent regression of issue #10412  , related to Registries tab in Cluster `Edit Config`, which should retain the value of the `Authentication` field when removing `Registry Authorization` blocks in the UI.

### Checklist
- [ ] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [ ] The PR has a Milestone 
- [ ] The PR template has been filled out
- [ ] The PR has been self reviewed 
- [ ] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [ ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Comment by aalves08** [comment]
@torchiaf @momesgin I've rebased https://github.com/rancher/dashboard/pull/10872 so this should be ready for a review 🙏

**Review by momesgin — APPROVED** [review]
LGTM

**Comment by izaac** [comment]
Is this something that can be accomplished provisioning real Clusters? There are provisioning capabilities to provision AWS and Azure RKE2 clusters in the framework now. @aalves08 @momesgin

**Comment by izaac** [comment]
I'll keep the referred issue opened.

**Pull request merged**
