### PR TITLE
Updating the source of internal/external ips for nodes

### PR DESCRIPTION
**Pull request by codyrancher**
rancher/dashboard#680

### CODE REVIEW

**Comment by vincent99** [comment]
RKE-specific annotations can't be the __only__ source of this data; those will be totally missing for AKS/EKS/GKE/imported clusters.

Norman/2.x [registers](https://github.com/rancher/types/blob/ecd764720a0f00cef7726c67f1383a7bb2c2828f/apis/management.cattle.io/v3/schema/schema.go#L163-L187) two mappers which [determine](https://github.com/rancher/types/blob/c29523994dfa724b4baddf6494d441523aa5615e/mapper/node_address.go) the `ipAddress` and `externalIpaddress` that show up in the API (that the Ember UI then [displays](https://github.com/rancher/ui/blob/1ebc4d7a3dd8d625459aea6f47d172aa592c06c2/lib/shared/addon/components/node-ip/template.hbs) with some checks.

`externalIpAddress` looks at:
1. The last (not first, though usually there's 0 or 1...) `status.addresses` entry with `type=ExternalIp`
2. The value of the `rke.cattle.io/external-ip` annotation

I _think_ mappers are applied in order so if both are present then the annotation wins, but awaiting confirmation.

`[internal]ipAddress` looks at just the last `status.addresses` entry with `type=InternalIp`.  The `rke.cattle.io/internal-ip` annotation is not involved (it's used only by RKE and Rancher code to hook up RKE).

**Comment by codyrancher** [comment]
Updated based on my understanding of what you said. If the order changes or we don't default to label for external ip let me know and I'll update.

**Comment by vincent99** [comment]
Darren said status should take priority, so `statusAddress || annotationAddress`.

The 2.x UI also has some extra filtering to only show the 2 addresses if they're different, which you may want to replicate so it doesn't say the same IP twice in the common case (`62.227.123.234 / 62.227.123.234`)

**Comment by codyrancher** [comment]
I made the swap.

> The 2.x UI also has some extra filtering to only show the 2 addresses if they're different, which you may want to replicate so it doesn't say the same IP twice in the common case (62.227.123.234 / 62.227.123.234)

@deniseschannon it does look a little odd when there's a duplicate ip. Would you like me to open an issue and talk to lauren about changing it?

**Comment by deniseschannon** [comment]
@codyrancher Yes, can you open an issue and follow up with @lvuch

**Pull request merged**
