### PR TITLE
RKE2 cluster create/edit screen allows saving invalid configuration

### PR DESCRIPTION
**Pull request by cnotv**
### Summary
Fixes rancher/dashboard#6763

### Occurred changes and/or fixed issues
- Prevent to continue if any node pool error is displayed
- Allows to create cluster without machine pool requirement

### Technical notes summary
- Adopted existing logic used for the badge to evaluate errors
- Replaced hardcoded i18n value
- Replaced hardcoded CSS classes with constants

Note: Although string check may be not the optimal choice, a change of logic or duplicated logic with a lack of tests would lead to an high risk of regression.

### Areas or cases that should be tested
As defined in the issue.

### Areas which could experience regressions
Cluster creation with and without pool cases.

### Screenshot/Video

https://user-images.githubusercontent.com/5009481/231116961-1799effb-da89-41d8-bf27-d1fd404e0c18.mp4

### CODE REVIEW

**Review by aalves08 — APPROVED** [review]
Gave it a test and works as expected. Nice touch on moving the colors to a constant. Much neater.

The only remark is it looks a bit odd (to me) to have the logic for `hasRequiredNodes` bound to colors instead of the checkbox values... But it works. Approved ✅

**Comment by cnotv** [comment]
> Gave it a test and works as expected. Nice touch on moving the colors to a constant. Much neater.
> 
> The only remark is it looks a bit odd (to me) to have the logic for `hasRequiredNodes` bound to colors instead of the checkbox values... But it works. Approved ✅

Yeah I totally agree, but to refactor such thing is too much effort, considering the E2E is failing 😄

**Comment by cnotv** [comment]
The issue was not with E2E, rather it always required machine pools to be checked.
Updated video with both cases.

**Review by aalves08 — APPROVED** [review]
Same comment as before on the `hasRequiredNodes`, otherwise testing and code LGTM 🙏

**Pull request merged**
