### PR TITLE
Interview tasks

### PR DESCRIPTION
**Pull request by RazorSiM**
### Summary
This pr implements the technical interview tasks given by the recruiter.

### CODE REVIEW

**Comment by richard-cox** [comment]
Hi @RazorSiM, thanks for joining the technical interview. In order to avoid other candidates getting a head start would you be able to clear our your `technical-interview` branch?

**Comment by RazorSiM** [comment]
> Hi @RazorSiM, thanks for joining the technical interview. In order to avoid other candidates getting a head start would you be able to clear our your `technical-interview` branch?

Sure thing :)

**Comment by RazorSiM** [comment]
@richard-cox It seems like I cannot modify my pull request because I've previously deleted my fork! 
Let me know if I can do something to help.

**Comment by richard-cox** [comment]
@RazorSiM Thanks for trying. We're checking out other ways to remove it. We'll make sure to update our process in the future

**Pull request closed without merging**
