### PR TITLE
show secret volume type correctly in workload detail

### PR DESCRIPTION
**Pull request by mantis-toboggan-md**
#1645 - check if secret volume is actually a certificate and label appropriately
Screen Shot 2020-10-20 at 9 47 23 AM

### CODE REVIEW

**Comment by vincent99** [comment]
I don't get why certificates are presented as own type here at all?  They're just one of the many kinds of secrets

**Comment by mantis-toboggan-md** [comment]
Purely because they're presented as a separate option in the Ember UI, and that was my reference for which volume types should be available in this UI.

**Comment by vincent99** [comment]
Yeah we should just not do that (for view or edit).  They are not a real separate type and dashboard supports many subtypes of secret rather than just 2 in ember.

When selecting the secret it would be nice if the options showed the type in addition to the name, e.g. "somesecret (Certificate)" instead.

**Review by vincent99 — CHANGES_REQUESTED** [review]
Let's drop the special certificate handling and let it just be a secret.

**Comment by mantis-toboggan-md** [comment]
Updated to remove the certificate type from workload storage, and fix an issue with the 'Add Volume' button

**Pull request merged**
