### PR TITLE
Monitoring/Alerting V2 Bugs

### PR DESCRIPTION
**Pull request by westlywright**
This PR contains fixes for a few different issues

Hides the external Monitoring links on overview page when the endpoints don't exist.

Slips a fix for create yaml where we do not want to process always add for array types.

Expose the Prometheus pods in the warning on Monitoring Config. This was a request from @aiyengar2.
Screen Shot 2020-09-22 at 5 11 11 PM

Tooltips on each external link was a bit awkward. Dropped tooltips and moved abbreviated content inline with link.
Screen Shot 2020-09-22 at 5 15 06 PM

@vincent99 sorry about the extra white space changes in the translations. For some reason VS code is ignoring the workspace setting to NOT trip white space for YAML only even though my user setting doesn't trim it as well. I can fix it if you want but I keep battling with it so I figured I might as well strip them all now.

### CODE REVIEW

**Comment by vincent99** [comment]
How does pointing the user to pods help me disable the old monitoring?

**Comment by aiyengar2** [comment]
> How does pointing the user to pods help me disable the old monitoring?

It doesn't help you disable old monitoring, but it helps you identify if you are going to encounter issues due to multiple Prometheus Operator pods already existing in your cluster (the actual reason why Monitoring V1 / V2 are incompatible).

This is a broader warning message that would also cover use cases like users deploying Prometheus Operators through sumologic or other charts that call a dependency on it, re: https://github.com/rancher/rancher/issues/25044

**Comment by vincent99** [comment]
And the static text of the message does that.  But pointing me at [potentially many] individual pods is actively unhelpful... clicking on them and taking an action there, like deleting them (which the text suggests I do) is not going to help the situation.  I'm just going to get an identical-looking (with different random suffix) rescheduled pod when I go back to try to install v2 again.

If you want to list resources, it should be looking for the Workloads (Deployment, DaemonSet, etc etc) which have a podspec with a container using those images.  Deleting those might not be the ideal way to uninstall the existing install, but at least it actually effective at stopping it.

**Comment by westlywright** [comment]
@vincent99 Updated. I slipped one more change in to fix the nav and remove the resource gauges. 

#1260

**Pull request merged**
