### PR TITLE
ClusterOutput and Output implementation

### PR DESCRIPTION
**Pull request by codyrancher**
rancher/dashboard#1102
rancher/dashboard#1103

Note:
Preview yaml doesn't seem to render the spec because it has a type of '.spec'. Do we want to pursue correcting `createYaml` or have the backend fix the type?

Screen Shot 2020-09-16 at 7 07 25 PM
Screen Shot 2020-09-16 at 7 07 08 PM
Screen Shot 2020-09-16 at 7 07 02 PM
Screen Shot 2020-09-16 at 7 06 55 PM
Screen Shot 2020-09-16 at 7 06 49 PM

Screen Shot 2020-09-16 at 7 08 14 PM
Screen Shot 2020-09-16 at 7 08 01 PM
Screen Shot 2020-09-16 at 7 07 49 PM
Screen Shot 2020-09-16 at 7 07 33 PM

### CODE REVIEW

**Comment by paynejacob** [comment]
Is there any way we could indicate to users that fluentd is called forward in the crd? I am concerned that users who start in the UI will get confused searching banzai docs if they need to do anything more advanced.

**Review by paynejacob — COMMENTED** [review]
Is there any way we could indicate to users that fluentd is called forward in the crd? I am concerned that users who start in the UI will get confused searching banzai docs if they need to do anything more advanced.

**Comment by codyrancher** [comment]
Is there a reason to keep fluentd instead of just renaming it to forward?

**Comment by deniseschannon** [comment]
View/Detail
- [ ] Hide overview tab 
- [ ] Tabs only show enabled/configured outputs

Create/Edit
- [ ] Change `Overview` text on tab to `Select Outputs`
- [ ] On "overview" page, show all providers and remove the pop-out icon. Add heading to `Select to configure an output.`
- [ ] By default, hide providers from side tab, when the button is selected, show provider.
- [ ] Remove "Enabled" checkbox on each config page
- [ ] Move username/password to top of "access" section

**Comment by codyrancher** [comment]
Here's what the updates look like:
Screen Shot 2020-09-18 at 5 55 30 PM

Screen Shot 2020-09-18 at 5 38 52 PM

And since I made some modifications to the GradientBox I verified that it appears the same on the overview page.
Screen Shot 2020-09-18 at 5 43 13 PM

**Pull request merged**
