### PR TITLE
Editing Secret object in Rancher UI corrupting binary data

### PR DESCRIPTION
**Pull request by aalves08**
Addresses Github issue: [#5574](https://github.com/rancher/dashboard/issues/5574)
Addresses Zube issue: [#5602](https://zube.io/rancher/dashboard-ui/c/5602)

**This PR is branched off of [PR 5602](https://github.com/rancher/dashboard/pull/5602). To be reviewed and merged after 5602**

- change permissions to generic template for `KeyValue` component for secrets 
- update `KeyValue` component to handle enconding and decoding of base64 dissociated from rendering of binary data

**UPDATE**
I believed that I've cracked the problems we were having with encoding/decoding of base64, so I restored all the functionalities we previously had...
With that in mind, most of the comments in this PR should not be considered when reviewing because they were done when we thought the best of course of action was limiting some actions so that we wouldn't risk compromising base64 data

### CODE REVIEW

**Comment by aalves08** [comment]
Sorry for the overload in PR reviews @nwmac but this has a continuation of work following https://github.com/rancher/dashboard/pull/5602 and the binary issues 🙏 

Thanks in advance

**Review by nwmac — CHANGES_REQUESTED** [review]
Can we make this consistent with the way Config Maps handles binary data - i.e. add a nwe Binary Data tab

**Comment by aalves08** [comment]
**new secrets changes**
Screenshot 2022-04-12 at 15 43 45
Screenshot 2022-04-12 at 15 39 41

**Review by nwmac — CHANGES_REQUESTED** [review]
I think we should try and put back in editing of secrets where the value is simple text and we should allow adding new ones - especially the read from file.

I think users will see this as a regression.

**Comment by richard-cox** [comment]
@aalves08 This one is superseded by #5662 as well?

**Comment by aalves08** [comment]
Correct @richard-cox . I am going to close this PR. Thanks

**Pull request closed without merging**
