### PR TITLE
added translation to keep up with the English version

### PR DESCRIPTION
**Pull request by vickyhella3**

### CODE REVIEW

**Review by kingsd041 — APPROVED** [review]
LGTM

**Comment by richard-cox** [comment]
@vickyhella3 There's some new conflicts, if you address and @WuJun2016 approves I'll merge. Thanks!

**Comment by WuJun2016** [comment]
LGTM

**Comment by vickyhella3** [comment]
@richard-cox The conflicts have been addressed.

**Review by richard-cox — APPROVED** [review]

**Pull request merged**
