### PR TITLE
Adding the ability to paste multiline strings into ArrayLists

### PR DESCRIPTION
**Pull request by codyrancher**
rancher/dashboard#1584

Kapture 2020-10-05 at 16 04 43

### CODE REVIEW

**Comment by vincent99** [comment]
This seems like it conflicts with `valueMultiline`.  And that's on by default, though probably shouldn't be.  If you flip the default, check existing usages of it (most of them don't look like they need multiline).

**Comment by codyrancher** [comment]
So it does conflict with `valueMultiline` but I don't think it conflicts in the way you assumed. Without `valueMultiline` this doesn't actually work. Inputs strip the `\n` before I get to see the value.

I decided to add `pasteMultipleAllowed` and change the default of `valueMultiline` to false. This allows us to support both pasting and the existing valueMultiline as it was intended if the user wants it.

**Comment by vincent99** [comment]
That's an extra problem then (which can maybe be dealt with by getting the paste contents earlier instead of from the value) but I don't see how multiline value + paste multiple ever makes sense, you don't know if three lines in the clipboard is 3 values of one line each or one value of 3 lines.

**Comment by codyrancher** [comment]
I updated to use the paste event as you mentioned. This was definitely the better option. It works with single and multiline and there's no flicker from having to wait for the rows value to change.

**Pull request merged**
