### PR TITLE
Port changes from `release-2.8.patch1` to `master`

### LINKED ISSUE #10642: Add Last Login Column to Users Table
As a Rancher Manager Admin, I would like to see the last time a user logged on, so that I could better understand who is actively using using Rancher.

### LINKED ISSUE #10819: Add User Login Labels to User Detail Page
As a Rancher Manager Admin, I would like to see the last time a user logged on, time to deactivation, and time to deletion for individual users, so that I could better understand who is actively using using Rancher.

### LINKED ISSUE #10892: [forwardport v2.9.0] Last Login field does not sort properly
This is a forwardport issue for #10821, automatically created via [GitHub Actions workflow](https://github.com/rancher/dashboard/actions/runs/8854491142) initiated by @rak-phillip

Original issue body:

Sorting for Last Login field in the Users table will sort by alphabetical order instead of the date. 

image

## Steps to Reproduce

1. Create 2 local users
2. Login as both the users
3. From users and Authentication >> Users >> sort by last login

## Expected Behavior

Users are properly sorted by Ascending/Descending based on the date. 

## Actual Behavior

Users are sorted by Ascending/Descending based on the alphabetical order.

### LINKED ISSUE #10980: [forwardport v2.9.0] Update user labels
This is a forwardport issue for #10978, automatically created via [GitHub Actions workflow](https://github.com/rancher/dashboard/actions/runs/9009213629) initiated by @rak-phillip

Original issue body:

Given the Users List & User Details pages, the Disabled/Deleted fields should read "Disable After"/"Delete After", so that the fields better communicate what will happen after the duration has passed.

## Additional Context

The current labels of "Disabled In"/"Deleted In" give the impression that these hooks might trigger immediately when the duration is up. This is not the case, and updating the labels better communicates this behavior.

### LINKED ISSUE #11073: [forwardport v2.9.0] Disabled In time is displaying for a user which is already in Disabled state
This is a forwardport issue for #11071, automatically created via [GitHub Actions workflow](https://github.com/rancher/dashboard/actions/runs/9178131437) initiated by @rak-phillip

Original issue body:

**Rancher Server Setup**
- Rancher version: v2.8.s4-318b423a3124919eb59fe0f4af024f2699645ffd-head
- Installation option (Docker install/Helm Chart): HA
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
Admin

**Describe the bug**
Disabled In column displaying the value for a user who is already in Disabled/Inactive state

**STEPS To Reproduce**

1.  Provision rancher HA
2. Create a user test1
3. Login as user test1 and logout
4. Login as  admin and Update  settings 'disable-inactive-user-after' to 5 mins 
        ` kubectl edit setting disable-inactive-user-after`
5. Check for the Disabled In time before and after 5mins (Rancher->users)

**Result**
1. The user is Inactive after 5mins, after 5mins the time keep getting increased and it is showing the time till it got deleted.

**Expected Result**
1. Once the user is Inactivated, the date on that user should be blank, it should not continue to display the time after it got disabled

**Screenshots**
image

**Additional context**

### LINKED ISSUE #11077: [forwardport v2.9.0] Deleted In column is displaying the value and it keep increasing like Age of the user
This is a forwardport issue for #11074, automatically created via [GitHub Actions workflow](https://github.com/rancher/dashboard/actions/runs/9178206873) initiated by @rak-phillip

Original issue body:

**Rancher Server Setup**
- Rancher version:
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Rancher Server Setup**

Rancher version: `v2.8.s4-318b423a3124919eb59fe0f4af024f2699645ffd-head`
Installation option (Docker install/Helm Chart): HA
If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
Proxy/Cert Details:
User Information: Admin

**Describe the bug**
When the CRON Job values are set to NULL, Deleted In column is displaying the value and it keep increasing like Age, it never deleted. This gives wrong information to the user.

**STEPS To Reproduce:**

1. Provision rancher HA
2. Create a user test1
3. Login as user test1 and logout
4. Login as admin and Update settings 'delete-inactive-user-after' to 5 mins `kubectl edit setting delete-inactive-user-after`
5. Make sure the UserRetention Cron value should set to NULL
6.  Check for the Deleted In time before and after 5mins (Rancher->users)

**Result**

UI says the user is Delete after 5mins, and the value keep decreasing & after 5mins the time keep getting increased and like the age of the User, it never got deleted.

**Expected Result**
The value should display from the CRON job, in this case the Cron job is not set and this user will not be deleted. 

**Screenshots**
image

**Additional context**

### PR DESCRIPTION
**Pull request by rak-phillip**
### Summary
This ports features from `release-2.8.patch1` into `master` to ensure that all changes introduced in the `patch1` branch are present for upcoming releases.

closes #10819
closes #10642
closes #10892
closes #10980
closes #11073
closes #11077

#### List of PRs associated with this merge

https://github.com/rancher/dashboard/pulls?q=is%3Apr+author%3Arak-phillip+is%3Aclosed+milestone%3Av2.8.patch1

### Occurred changes and/or fixed issues

All changes introduces from the following PRs should be represented in this change:

- #10653
- #10817
- #10818
- #10977
- #11078

### Technical notes summary

The rebase PR has been omitted:

- #11093

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Comment by rak-phillip** [comment]
@mantis-toboggan-md we will need to test this change against a `v2.8.5` backend as we work on porting the whole feature into 2.9

**Review by mantis-toboggan-md — APPROVED** [review]
LGTM

**Comment by richard-cox** [comment]
@rak-phillip i couldn't see where this PR resolves https://github.com/rancher/dashboard/issues/11013, would you be able to confirm?

**Comment by rak-phillip** [comment]
@richard-cox #11013 inadvertently got pulled in with the forward porting effort for user retention. Removing the link from this PR.

**Comment by rak-phillip** [comment]
The remainder of the linked issues are accurate after giving them a review.

**Pull request merged**
