### PR TITLE
Harvester shell integration - add translations

### PR DESCRIPTION
**Pull request by torchiaf**
### Summary
Contributes to https://github.com/rancher/dashboard/issues/12347

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

### CODE REVIEW

**Comment by a110605** [comment]
Some "VM" can extend to "Virtual Machine"
 
image

**Comment by a110605** [comment]
Do you mind update `Add-On` to `Add-on`? This is what we did in harvester repo ([PR](https://github.com/harvester/dashboard/pull/1176))
image

**Review by codyrancher — DISMISSED** [review]
I feel like someone else above needs to approve this. Even though I'm okay with expanding the contractions and replacing things like & I don't know if others are okay with that.  I guess worst case scenario we could always revert back if an issue arises.

**Review by a110605 — APPROVED** [review]
LGTM for current translation change.

**Comment by torchiaf** [comment]
@a110605 I removed the existing labels changes and moved them in a separate PR for simplicity. Can you approve it again ?

**Comment by gaktive** [comment]
@kwwii based on NA standup discussion, can you sweep through this and see if the wording and abbreviations are standardized?

**Pull request merged**
