### PR TITLE
Adding translation for OVHCloud Managed Kubernetes Service

### PR DESCRIPTION
**Pull request by belgaied2**
Signed-off-by: Mohamed Belgaied Hassine <belgaied2@hotmail.com>

### Summary
This PR adds a translation for `ovhcloudmks` kontainer driver, so that it can show correctly `OVHcloud MKS` in the UI.

### Occurred changes 
Adds 2 lines with a mapping ovhcloudmks: OVHCloud MKS in the translation yaml files.

### Technical notes summary
Simple

### Areas or cases that should be tested
Nothing in particular, OVH will test this.

### Areas which could experience regressions
Risk is extremely low for regressions

### Checklist
- [X] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [X] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] tests are not needed
- [x] there are no UX changes

### CODE REVIEW

**Review by aalves08 — APPROVED** [review]
Overall, LGTM @belgaied2 

One thing to notice is that if the milestone is correct  `2.8.9`, then you'll need to redo this PR against the branch `release-2.8` as `master` is currently tracking this upcoming release of `2.10`.

We should also backport it for 2.9 -> branch `release-2.9`

FYI @richard-cox

**Review by richard-cox — APPROVED** [review]
As per Alex's comment i've updated the milestone to 2.10 as it tracks `master`.

For 2.9 the change needs to be backported to release-2.9.

For 2.8 the change needs to be backported to release-2.8.

@belgaied2  Would you be able to confirm any translations when provisioning a hosted cluster using this provider are correct? I'm not 100% sure but there might need to be similar changes in rancher/ui

**Comment by richard-cox** [comment]
SURE-9091

**Comment by belgaied2** [comment]
I got the information from OVHcloud that it works correctly (at least for the `Create Cluster` View, I do not know more details) if they rebuild the Rancher container image. I did not test myself however.
Seeing the structure of `rancher/ui` translations, it might be that credentials also need additional custom translations, but I am not sure. I will have to check with them.

**Pull request merged**
